### ISSUE TITLE
Add events to know when location was enabled/disabled. Same for bluetooth/wifi

### ISSUE THREAD

**Issue by heroic** [react-native-device-info/react-native-device-info#1035]
# Feature request

Currently the package provides a way to know if location/bluetooth/wifi is available or not, but there is no event to subscribe to for when these are changed from outside the app.

## Why it is needed

If we need this functionality we need to use a different package for this, which makes the presence of isLocationEnabled, et all, functions useless from this package. Subscriptions to listen to changes to these hardware settings will make this package complete in the value provided.

## Possible implementation

Add subscriptions for hardware on/off events, much like how we have battery value update events.

**Comment by mikehardy** [comment]
PRs happily accepted :-)

**Comment by mikehardy** [comment]
if anyone wants to try this, the react-native-community/netinfo object shape for the event, event listener etc are a great model

**Comment by heroic** [comment]
@mikehardy I'd like to help with this, but I'm afraid I'm not great with iOS

**Comment by mikehardy** [comment]
Usually people are good with one or the other, I'm pretty sucky at Objective-C too. Propose an Android implementation and we can start from there, I won't let perfect get in the way of good
