### ISSUE TITLE
getPhoneNumber() not returning mobile number

### ISSUE THREAD

**Issue by coolarun900** [react-native-device-info/react-native-device-info#1045]
While I am tried to get phone number (inserted sim). But I am getting empty. Could you please help me in this.

OS:Android 9 (pie)
Checked with real device only.

React : 16.11.0
React Native : 0.62.2
React Native Device Info : 5.6.2

**Comment by mikehardy** [comment]
We are the most thin wrapper around device APIs possible.
Maybe you don't have device phone permission
Maybe this phone model does not return the phone number
Maybe the SIM is in the second slot, I don't think we support that...

You should try diving in the code to instrument what the API is returning 

I'll be curious to see what you find

https://github.com/react-native-community/react-native-device-info/blob/5ba1d210403dadb0b16ff05f2c2b33f9a34d4c6d/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L749-L761

**Comment by whenmoon** [comment]
OS:Android 11 / 10 - physical Pixel 2 XL and physical Samsung A9.

React : 16.13.1
React Native : 0.63.3
React Native Device Info : 7.4.0

Related permissions are:
```xml
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
    <uses-permission android:name="android.permission.READ_SMS" />
```

This method is returning `unknown` for me. I dived in to the package code and logged the variables used in the conditionals:

```java
  public String getPhoneNumberSync() {
		Log.i("Build.VERSION.SDK_INT",  Integer.toString(Build.VERSION.SDK_INT));

    Log.i("Build.VERSION_CODES.M", Integer.toString(Build.VERSION_CODES.M));

    Log.i("Build.VERSION_CODES.O", Integer.toString(Build.VERSION_CODES.O));

    Log.i("getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_SMS", Integer.toString(getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_SMS)));

    Log.i("getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_PHONE_NUMBERS)", Integer.toString(getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_PHONE_NUMBERS)));

    Log.i("Build.VERSION_CODES.O", Integer.toString(Build.VERSION_CODES.O));
    if (getReactApplicationContext() != null &&
```

Logs are as follows:

> 2021-03-04 19:24:42.133 2568-2691/com.xyz I/Build.VERSION.SDK_INT: 30
2021-03-04 19:24:42.134 2568-2691/com.xyz I/Build.VERSION_CODES.M: 23
2021-03-04 19:24:42.134 2568-2691/com.xyz I/Build.VERSION_CODES.O: 26
    [          1614882282.134  2568: 2691 I/getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_SMS -1
    [          1614882282.134  2568: 2691 I/getReactApplicationContext().checkCallingOrSelfPermission(Manifest.permission.READ_PHON-1
2021-03-04 19:24:42.134 2568-2691/com.xyz I/Build.VERSION_CODES.O: 26

**Comment by mikehardy** [comment]
So, what do those -1's tell you?
Perhaps you can never get those permissions on Android 10/11 because of platform changes with regard to privacy / security? Have you looked at the Android 10, Android 11 release notes to see what they changed with regard to how those APIs will work?

I don't remember off-hand, but that's what I suspect. Similar to the hardware identifiers they have probably secured them.

**Comment by whenmoon** [comment]
Thanks @mikehardy, so yep you need those permissions and you need to prompt the user to grant those permissions which is too much to ask for something like pre-populating a sign up form. Will give it a miss.

https://developer.android.com/about/versions/11/privacy/permissions#phone-numbers

**Comment by mikehardy** [comment]
@jega07 I asked the internet for you:
https://stackoverflow.com/search?q=ios+get+phone+number

No.

https://stackoverflow.com/a/193284/9910298

Open source repositories are maintained by volunteers, please do your own research on questions prior to posting, it leaves more maintainer time to make the libraries better vs user support, and is always appreciated
