### ISSUE TITLE
getInstallReferrer not working | throwing error utm_source=(not%20set) utm_medium=(not%20set)

### ISSUE THREAD

**Issue by SachArora** [react-native-device-info/react-native-device-info#1061]
I'm using Play Install Referrer API.
Version  "react-native-device-info": "^5.5.3"

info 
  React Native Environment Info:
    System:
      OS: macOS 10.15.4
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 18.54 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

https://play.google.com/store/apps/details?id=com.EXAMPLE&referrer=utm_source%3Dgoogle%26utm_medium%3Dcpc%26anid%3Dadmob

**Comment by mikehardy** [comment]
Versions, example code, actual stack trace please.
Imagine some programmer walks up to you and says "I have a problem", provide all the details you would want, in order to troubleshoot

**Comment by SachArora** [comment]
Can someone please help me out with the solution.

**Comment by mikehardy** [comment]
@SachArora perhaps you could supply information useful to help you

**Comment by Sine99** [comment]
@mikehardy ... hi, I am having issue with getInstallReferrer()

![image](https://user-images.githubusercontent.com/3010749/94828523-2f602d80-0427-11eb-9b83-18c5cfeb29c8.png)

this is the following result

![image](https://user-images.githubusercontent.com/3010749/94828690-5ae31800-0427-11eb-9e38-2ef4332381b2.png)

**Comment by Sine99** [comment]
@mikehardy as u could see in the above pics, i m getting google-play as  utm as referrer while docs say something else....Please let me know if i m making some mistakes. I shared the below link on whatsapp which redirected me to goole play store, then i downloaded the app.
https://play.google.com/store/apps/details?id=com.swagitapps.swagit.social_media&referrer=mike_hardy

**Comment by mikehardy** [comment]
@Sine99 some quick thoughts

- please use text, images don't work well in multiplatform environment (like if I'm mobile), and they aren't quotable sharable etc - just generally not good for troubleshooting.

Here's how we call the APIs

https://github.com/react-native-community/react-native-device-info/blob/2052b76b0276eae3f1ab9aa8c25f095fd9df83ec/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java#L15-L31

They are documented like so https://developer.android.com/google/play/installreferrer/igetinstallreferrerservice
https://developer.android.com/reference/com/android/installreferrer/api/ReferrerDetails

It's possible there are multiple redirects prior to the final URL, hard to say, but if we are using the APIs incorrectly please propose a PR supported by testing evidence and we can check it out

**Comment by waqas-tr** [comment]
In case anyone getting utm_source=(not%20set) utm_medium=(not%20set)
You can check following answer on stackoverflow

> Google play store checks all the mail accounts which are logged into Google play and if you are logged in with work email (enterprise domain email id)it sets the UTM property as utm_source=(not%20set)&utm_medium=(not%20set).
> 
> So try removing work email from google play store and verify.

[This answer](https://stackoverflow.com/a/65475325)

**Comment by kotsh23** [comment]
for anyone have same issue 
the fix is just add referrer= query param to the link look at example url and yes its 2 = in same query :D

example:

https://play.google.com/store/apps/details?id=app.id.anything&referrer=refcode=basha
