### ISSUE TITLE
Add time since boot

### ISSUE THREAD

**Issue by xcarpentier** [react-native-device-info/react-native-device-info#1064]
# Feature request

Add `time since the boot` of the system.

## Why it is needed

Time since boot may affect mobile performance.
It will be great to know it when an app relies on performance and that may affect some features (ie. need a huge amount of CPU or memory).

## Possible implementation (Code sample)

https://gist.github.com/stecman/71a5cead43eeef8fbc4c54eb97fe5ebd

**Comment by mikehardy** [comment]
Sure, I'd accept a PR implementing that
