### ISSUE TITLE
getDeviceId() returns Build.BOARD for Android

### ISSUE THREAD

**Issue by GEllickson-Hover** [react-native-device-info/react-native-device-info#1069]
# Bug report

## Summary

getDeviceId() for Android will return Build.BOARD ([see line here](https://github.com/react-native-community/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L171)), but it seems that the correct intent would be to use Build.DEVICE. Or is there a reason this uses Build.BOARD that I'm not understanding?

Build.BOARD seems to return a string that helps identify the board / chip set, which seems like it could be the same on different device models, while Build.DEVICE should return a proper codename for the device.

For example: on my Samsung s10+ the Build file yields the following for key constants:
MODEL: SM-G975F
DEVICE: beyond2
BOARD: exynos9820

Using the above value in Google Play's current device catalog, if I want to filter by "Device model", I can use that Build.DEVICE codename to filter for that model, but that doesn't seem to be true with the Build.BOARD value. Though if I search by "System on Chip", I can find the chipset Samsung Exynos 9820, which has multiple devices associated with it.

## Environment info

Any Android Device

Library version: the latest

## Steps to reproduce

N/A see link to code

## Reproducible sample code

N/A see link to code

**Comment by mikehardy** [comment]
Interesting - probably just an oversight. If I recall I was the one that added all those and I was typing pretty quickly during the v2-v3-v4 thing while trying to handle the "we want constants" / "we want fast startup so it should be async" difference of opinion, so in other words likely just a bug.

If you proposed a PR that re-directed the API to the constant that seems like a better fit and added an API that gave the old information, then we'd have a semver major breaking change but it would be pretty painless for people that needed return-value consistency to handle existing data etc

If you see anything else missing from here https://github.com/flutter/plugins/blob/90924b5727a9dbadbff8aa51db704c007188dd71/packages/device_info/device_info/android/src/main/java/io/flutter/plugins/deviceinfo/MethodCallHandlerImpl.java#L41-L52 it wouldn't hurt to add it either

Cheers

**Comment by GEllickson-Hover** [comment]
@mikehardy thanks for the reply. I will take a look into a PR then, when I get a chance. Cheers!

**Comment by bryce0516** [comment]
@mikehardy Hi,
I have one other issue. 
I'm using this module since now ,but it's not working right now.
Problem is, I switched to api level 29 for android X, and the module threw java.lang.securityexception: getdeviceid
How can I solve this problem? I think this is a problem caused by a change in Google policy. So I can't use it anymore?

**Comment by mikehardy** [comment]
If that API throws SecurityException (a RuntimeException so they did not have to declare that they were introducing a breaking change, how nice of them...) now on compile target 29, then we should catch it.

If you propose a PR that wraps that API in a try/catch for 'Exception' and returns the default value, I can merge it

**Comment by bryce0516** [comment]
> If that API throws SecurityException (a RuntimeException so they did not have to declare that they were introducing a breaking change, how nice of them...) now on compile target 29, then we should catch it.
> 
> If you propose a PR that wraps that API in a try/catch for 'Exception' and returns the default value, I can merge it

I appriciate for your help. Thank you so much! i did invite for you.

**Comment by mikehardy** [comment]
Excellent @bryce0516 ! I don't need an invite though, once you have code you think works, just make a PR here and we may review it and merge it in this repo

**Comment by bryce0516** [comment]
> Excellent @bryce0516 ! I don't need an invite though, once you have code you think works, just make a PR here and we may review it and merge it in this repo

    googlePlayServicesIidVersion = "17.0.0"
    buildToolsVersion = "28.0.2"
    minSdkVersion = 19
    compileSdkVersion = 29
    targetSdkVersion = 29
    supportLibVersion = "28.0.0"
    excludeAppGlideModule = true
    mediaCompatVersion = '1.0.1'
    supportV4Version = '1.0.0'

i forgot something in your manual.. sorry i have to read more carefully. It's my fault. Your module is working perfectly!
