### ISSUE TITLE
Port C# Windows implementation to C++

### ISSUE THREAD

**Issue by kmelmon** [react-native-device-info/react-native-device-info#1073]
# Feature request

This PR recently added Windows support:
https://github.com/react-native-community/react-native-device-info/pull/1059

First I just wanted to say thanks so much for doing this!  It's great to see so much enthusiasm for Windows support in this space.

I have a suggestion here, to port this code over to C++.  See next section for rationale.

## Why it is needed

There are a couple reasons to consider porting the module to C++:

**Performance:**  
The core of react-native-windows is written in C++ and the standard template is a C++ app.  This is for performance reasons.  Bringing in a C# native module adds the overhead of the CLR to the app which is significant, and isn't strictly necessary.

**Issue https://github.com/microsoft/react-native-windows/issues/5858**:  
This currently prevents apps from using C# native modules from the standard C++ based template app, which is the default.  We are talking within Microsoft on how to address this, and that process will take time.  In the mean-time there are workarounds but they aren't easy for customers to understand, so we have a short to medium term problem, which could be avoided altogether if the module was converted to C++
## Possible implementation

The react-native-windows website has a guide on how to author a C++ native module.    
Start here:   
 https://microsoft.github.io/react-native-windows/docs/native-modules  
See section called "Sample Native Module (C++)"

### Code sample

For a working example of a C++ native module, see:
https://github.com/react-native-community/async-storage/tree/master/windows/ReactNativeAsyncStorage

**Comment by mikehardy** [comment]
I believe https://github.com/react-native-community/react-native-device-info/releases/tag/v6.0.2 solves the specific issue you have with things working or not even working?

That said, in general sure! PRs happily accepted

I have no react-native-windows setup so I am relying on the community for progress in the area.

**Comment by kmelmon** [comment]
Thanks!  @tero-paananen - if you were interested in helping with this that would be awesome!

**Comment by chrisglein** [comment]
Here's some documentation on converting C# to C++/winrt: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp
Not an automated process, but also there seem to be good resources for powering through it.
