### ISSUE TITLE
Adding Jest Mocks

### ISSUE THREAD

**Issue by schie** [react-native-device-info/react-native-device-info#1101]
## Description

Through-out the various apps I work on, we always end up writing jest mocks for this lib.

Is there any opposition to adding file like `<root>/jest/react-native-device-info-mock.js` that can be imported into an app's jest setup ?

There are a few other libs that follow a similar approach:
- [react-native-netinfo](https://github.com/react-native-netinfo/react-native-netinfo/blob/master/jest/netinfo-mock.js)
- [react-native-async-storage](https://github.com/react-native-async-storage/async-storage/blob/master/jest/async-storage-mock.js)

## Use Case

As mentioned in various other issues related to mocks, this would greatly improve `Developer Experience` .

<hr />

If we're cool with it, I can make a PR adding it.

**Comment by mikehardy** [comment]
It would be a fantastic DX improvement, it would be most welcome

**Comment by schie** [comment]
awesome! I'll get this in soon.

**Comment by sem4phor** [comment]
hello,

i tried to use the mocks to change the return value of the hasNotch function but I can not get it working especially when doing two tests with different return values.

Is there a way you could provide an example usage for the mocks where you change the return value of a device info?

**Comment by pke** [comment]
I guess you would have to use `jest.spyOn(RNDeviceInfo, "hasNotch").mockReturnValue(false)` and reset the jest spies between tests. @mikehardy would that be correct?

**Comment by euclidesdry** [comment]
> import mockRNDeviceInfo from 'react-native-device-info/jest/react-native-device-info-mock'
> jest.mock('react-native-device-info', () => mockRNDeviceInfo)

Thank you, this worked well for me! @sem4phor

**Comment by thepavangollapalli** [comment]
If you prefer to set up your mocks using Jest's [convention for automatically mocking modules](https://jestjs.io/docs/manual-mocks#mocking-node-modules), this approach also worked for me:
- Create a file called `react-native-device-info/index.ts` inside your project's `__mocks__` folder
- Set the contents of that file to 
```
export default 'react-native-device-info/jest/react-native-device-info-mock';
```

**Comment by react06** [comment]
> hello,
> 
> i tried to use the mocks (by registrating it in the jest setup file) to change the return value of the hasNotch function but I can not get it working especially when doing two tests with different return values.
> 
> Is there a way you could provide an example usage for the mocks where you change the return value of a device info?
> 
> My Code: in setup setup.js
> 
> ```
> import mockRNDeviceInfo from 'react-native-device-info/jest/react-native-device-info-mock'
> jest.mock('react-native-device-info', () => mockRNDeviceInfo)
> ```

Hi @sem4phor, wanted to do the same for test cases if you found any solution regarding this, it will be so much help. Thank you

**Comment by retyui** [comment]
> export default 'react-native-device-info/jest/react-native-device-info-mock';

That is correct syntax @thepavangollapalli 

as in the code, it will be resolved as string
```jsx
import RNDeviceInfo from 'react-native-device-info';
console.log(' --- xdebug', { RNDeviceInfo });
// --- xdebug {
//      RNDeviceInfo: 'react-native-device-info/jest/react-native-device-info-mock'
//    }
```

better

```diff
-export default 'react-native-device-info/jest/react-native-device-info-mock';
+export default jest.requireActual('react-native-device-info/jest/react-native-device-info-mock');
```
