### ISSUE TITLE
metro bundler error: ::ffff:127.0.0.1 - - [DATE] “GET <class-module-name” HTTP/1.1“ 404 208 ”-“ ”okhttp/3.12.1"

### ISSUE THREAD

**Issue by rahamin1** [react-native-device-info/react-native-device-info#1103]
- I am using react-native-device-info (version 6.0.2) with react-native 0.62.2 and it is working properly
- Because of poor performance of the app (not related to the package) on android, I downgraded to 0.59.9 where it is much faster
- However, when I add react-native-device-info and I am calling it from within the app, and I  am running the app ('react-native run-android') I get the error written in the title:

`metro bundler error: ::ffff:127.0.0.1 - - [DATE] “GET <class-module-name” HTTP/1.1“ 404 208 ”-“ ”okhttp/3.12.1"`

- If the app is included in the build but it is not used by the app, there is no problem.
- After removing the app, when I tried to get the app's version number by accessing Platform.constants.Release, I get the same error message

Any idea why this happens and how to fix it?

**Comment by mikehardy** [comment]
With apologies, I will make no effort whatsoever to support RN59 and lower, if there are performance problems they should be figured out rolling forward, not backward

**Comment by rahamin1** [comment]
Apology accepted :)
