### ISSUE TITLE
getLine1Number() implementation for Android11

### ISSUE THREAD

**Issue by firdaussoberi** [react-native-device-info/react-native-device-info#1105]
## Description
My app crashed today when testing on Android11 device, simulator also shows same crashlog.
I believe this is related to changes in permission behavior starting from Android11 as pointed here:
https://developer.android.com/about/versions/11/privacy/permissions#phone-numbers

![7e3180af-ee0b-4d22-ae38-e4058670b801](https://user-images.githubusercontent.com/8426299/96553009-20aebd00-12e7-11eb-927c-98741ece9d75.jpeg)

Currently, I only include this related permission in my AndroidManifest:
```
    ...
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
``` 
and then proceed to call DeviceInfo.getPhoneNumber() after requesting PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE from react-native.

I saw in RNDeviceModule.java that both ```READ_SMS``` and ```READ_PHONE_NUMBERS``` are already included in getPhoneNumberSync().
For android11 and higher, I should include also ```READ_PHONE_NUMBERS``` explicitly in my manifest right?
Would appreciate if anyone who tested successfully on Android11 can shed a light on this.

Am using v5.6.5 of the package, RN0.60.4, targetSDK 30.

**Comment by firdaussoberi** [comment]
Updating manifest permission  to
```
    <uses-permission android:name="android.permission.READ_PHONE_STATE" android:maxSdkVersion="29" />
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
```
solves the issue for targetSDK 30.

Closing issue.

**Comment by mikehardy** [comment]
Interesting - could use a PR for the docs to solve future developer issues :pray:  :smile:
