### ISSUE TITLE
Adding general tests

### ISSUE THREAD

**Issue by schie** [react-native-device-info/react-native-device-info#1108]
## Description
Scope: Adding tests of the TS code
- [x] setup jest
- [x] add tests for internal functions
  - [x] asyncHookWrappers.ts
  - [x] supported-platform-info.ts
- [ ] add lib tests
  - _'ensure that exported `getX` calls expected Native Module function'_
  - [x]  getUserAgent
  - [x] getUserAgentSync
  - [ ] getSystemName
  - [ ] getReadableVersion
  - [ ] hasNotch
  - [ ] getTotalDiskCapacityOld
  - [ ] getTotalDiskCapacityOldSync
  - [ ] getFreeDiskStorageOld
  - [ ] getFreeDiskStorageOldSync
  - [ ] syncUniqueId
  - [ ] hasSystemFeature
  - [ ] hasSystemFeatureSync
  - [x] getPowerState
  - [x] getAvailableLocationProviders
  - [ ]  hasGms
  - [ ] hasGmsSync
  - [ ]  hasHms
  - [ ] hasHmsSync
  - Hooks
    - [ ]  useBatteryLevel
    - [ ] useBatteryLevelIsLow
    - [ ] useDeviceName
    - [ ] useFirstInstallTime
    - [ ] useHasSystemFeature
    - [ ] useIsEmulator
    - [ ] usePowerState
    - [ ] useManufacturer
    - [ ] useIsHeadphonesConnected
- [x] run tests through GitHub Action

## Use Case

Adding the above should help the review process.

**_note_**: after this is complete, I plan to work on Native Code tests, but I might need some guidance on that.

**Comment by schie** [comment]
@mikehardy,

Any experience testing `NativeEventEmitter` ? 

I'm having trouble testing emitting events in jest, so I'm a little stuck.

 If you have time, I can push up what I have so far to take a look in a bit

**Comment by mikehardy** [comment]
I'm sorry, I do not, I'm pretty much mocked to empty stubs for RNDI in my work project

**Comment by schie** [comment]
Gah! I was hoping others might help. Writing tests are the worst!

I'll be working on this a bit more soon.
