### ISSUE TITLE
Pixel 3a does not have notch

### ISSUE THREAD

**Issue by systemride** [react-native-device-info/react-native-device-info#1115]
## Summary

|             |     |
| ----------- | --- |
| Version     | v7.0.2 |
| Affected OS | Android |
| OS Version  | any |

## Current behavior

With #1107, the Pixel 3a now returns `true` for hasNotch.

## Expected behavior

Pixel 3as do NOT have a notch, and this should return `false`.
https://store.google.com/us/product/pixel_3a

**Comment by mikehardy** [comment]
I trust the community to do it right, if they have not, please propose a PR to remove that block, I'll happily merge it
