### ISSUE TITLE
.hasNotch() not working on iphone 12

### ISSUE THREAD

**Issue by KDKHD** [react-native-device-info/react-native-device-info#1118]
## Summary
the .hasNotch() function does not detect iPhone 12 notches.

| Version     |     "react-native-device-info": "^5.6.4",
| Affected OS |  IOS14

## Current behaviour

.hasNotch() does not seem to work on iPhone 12 ios14

## Expected behavior

.hasNotch() should detect that an iphone12 has a notch

**Comment by mikehardy** [comment]
search before logging: https://github.com/react-native-device-info/react-native-device-info/pull/1099/files

upgrade: https://github.com/react-native-device-info/react-native-device-info/releases

integrate + release!

**Comment by harisshk** [comment]
the .hasNotch() function does not detect iPhone 13 series notches.

**Comment by mikehardy** [comment]
@harisshk you've posted a comment in two areas, with zero details, and this thread is for iphone 12 so it is not relevant.

**Comment by zoobibackups** [comment]
not working on iOS 17 iPhone 15 Pro Max
