### ISSUE TITLE
Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.

### ISSUE THREAD

**Issue by black-nijar** [react-native-device-info/react-native-device-info#1121]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.63.2  |
| Affected OS | macOS  |
| OS Version  | 10.15.6 (19G2021)   |

**Comment by Hoai-Phong** [comment]
I also got the same error[](url)
![image](https://user-images.githubusercontent.com/83800555/132989782-974279f2-a9ca-4691-bfb7-e29c96a6118f.png)
![image](https://user-images.githubusercontent.com/83800555/132989796-22c8922b-2d9d-4207-9992-43e7e4443d22.png)

**Comment by black-nijar** [comment]
@Hoai-Phong  please follow these steps it may help you.
1. remove node_modules
2. reinstall node_modules
3. cd ios && pod install
4. take rebuild
