### ISSUE TITLE
Device Token is too long

### ISSUE THREAD

**Issue by enisinanaj** [react-native-device-info/react-native-device-info#1123]
## Summary

The device token returned is too long and not the same as the notifications device token.

|             |     |
| ----------- | --- |
| Version     | 7.0.2   |
| Affected OS | iOS 14+   |

## Current behavior

I'm trying to get the device token but the returned string is way too long. AWS SNS is complaining with the following error:

`iOS device tokens must be no more than 400 hexadecimal characters (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter`

## Expected behavior

I expected to get the notification token of the device.

**Comment by mikehardy** [comment]
How would you propose to fix it, taking in to account what device tokens are available to us and how you would implement it in a PR, along with transition capabilities for installed user base if it's a breaking change?

**Comment by enisinanaj** [comment]
I think it's useless in the end. I looked and I couldn't find an API that could return that. But I noticed that the usual flow `didRegisterUserNotificationSettings` -> `didRegisterForRemoteNotificationsWithDeviceToken` is being triggered everytime the app starts.

I would close the issue

**Comment by tanoto-the-explorer** [comment]
@mikehardy did you got the device token in the end?
