### ISSUE TITLE
getUniqueId behaves inconsistently 

### ISSUE THREAD

**Issue by exotexot** [react-native-device-info/react-native-device-info#1124]
Hello, 

I can see the return value of getUniqueId changing slightly. Can please someone tell me, if this value changes in specific modes, e.g. running in debug mode, oder release more, or as an app in the store?

Specifically on Windows I have the case, where once the return value of getUniqueId is
“625ad674-042f-3862-91ca-797ac7df09d2”

but also got return like
“{625ad674-042f-3862-91ca-797ac7df09d2}”

But based on my usecase between my testings I saw devient device ids. 

Just curious if this is a known issue or something to do about it.

using "react-native-device-info": "^7.0.2", and react-native 0.62.2

**Comment by mikehardy** [comment]
this would be something new. It should not have the curly brace around it, that looks to me like it's wrapped in an object before printout as opposed to the raw value. Can you verify that you haven't done anything in processing that would cause it to be different? Can you reproduce it in the example app?

**Comment by exotexot** [comment]
Just realized that I was runnign on this fork: https://github.com/jaimecbernardo/react-native-device-info/tree/windowscpp
But with here, I',m always getting {8579ceff-XCAB-e512-1666-3765254a181b} as return value. Need to test on master branch

**Comment by mikehardy** [comment]
yes - that's some pending work I need to do to get that released. Have been backlogged handling a massive breaking react-native-firebase release 😅

**Comment by Rob2k9** [comment]
maybe you could help me here i am using the latest version of device-info on my android project when users open my app the app runs a login request to check there account is active and to limit accounts to no more than two devices the unique id is sent with the request but sadly it seems that on androidTV devices the id seems to keep changing testing on my firestick and nvidia shield i found that every time i opened and closed the app i got a completly diffrent id every time

**Comment by mikehardy** [comment]
@Rob2k9  I have no help to offer, you'll need to trace through the underlying code down to native to see what's happening. This sounds like the platform APIs aren't behaving well but we're not in control of them

**Comment by exotexot** [comment]
I also found no real solution to this. Depending on how critical this is for you, you could try to use a workaround and find some other values the are device specific and are likely not my going to change, like the device name maybe.

**Comment by scaralfred** [comment]
Has anyone found a robust solution to fix this inconsistent behaviour and always get a "unique id" for iOS devices, even after re-installation?

**Comment by schie** [comment]
@mikehardy @exotexot,

 I'm not sure if this is directly related, but from my experience w/ windows applications and MSSQL, `{8579ceff-XCAB-e512-1666-3765254a181b}` is a way that they present UUIDs (GUIDs for windows/MSSQL).

PER MS docs, [curly-braced GUID String](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpfr/ac10a1cc-128a-4942-a120-363f74e1953d)

Hopefully, this helps in some way.
