### ISSUE TITLE
In Catalyst, app using getSystemName() reports as "iOS" on Big Sur

### ISSUE THREAD

**Issue by exotexot** [react-native-device-info/react-native-device-info#1127]
In Catalyst, app using getSystemName() reports as "iOS" on Big Sur. Probably be an easy fix though.

**Comment by mikehardy** [comment]
Could be - and PRs always happily accepted - but if you are on Catalyst what APIs are available to you? i.e., what should it actually report? Should it report "catalyst", "macOS" or is "iOS" more or less correct? I admit to being oblivious 😅 , I haven't played with the cross-platform ios/catalyst/macos space at all to know what APIs are available with what compilation / execution profiles

**Comment by exotexot** [comment]
On Catalina it reports "Mac OS X". Which i would expect to happen also on Big Sur. Strickly speaking, Big Sur ist not Mac OS X anymore but macOS.

**Comment by mikehardy** [comment]
Oh goodness - forgot that Big Sur also finally got off the 10.x train. As ever PRs happily accepted to make all this stuff work + stay usable

**Comment by exotexot** [comment]
Had a look at this just now and I'm not sure on how to proceed here, as i dont know how to debug the UIDevice class. The naitve code is also only few lines 

- (NSString *) getSystemName {
    UIDevice *currentDevice = [UIDevice currentDevice];
    return currentDevice.systemName;
}


The same is also relevant for the getSystemVersion. As of right now on BigSur, using Catalyst, device info return 14.2, instead of 11.x

I attached all debug info from BigSur maybe someone can spot more inconsistencies. 

![Screenshot 2020-12-06 at 21 45 51](https://user-images.githubusercontent.com/10153413/101291961-bc02df80-380c-11eb-8ae5-1478ab1b070a.png)
![Screenshot 2020-12-06 at 21 45 53](https://user-images.githubusercontent.com/10153413/101291964-be653980-380c-11eb-88a1-81b07f6be74a.png)
![Screenshot 2020-12-06 at 21 45 59](https://user-images.githubusercontent.com/10153413/101291966-bf966680-380c-11eb-9a75-d6cb8412bff6.png)
![Screenshot 2020-12-06 at 21 46 14](https://user-images.githubusercontent.com/10153413/101291967-c02efd00-380c-11eb-88ed-a60edb47cf60.png)

**Comment by mikehardy** [comment]
Fixed by #1137
