### ISSUE TITLE
How can i use syncUniqueId method?

### ISSUE THREAD

**Issue by yoojeen126** [react-native-device-info/react-native-device-info#1130]
Ok, i know when a ios device moved to restored b ios device. This can be same unique id.
So how can i call this syncUniqueId  function when this was restored device?

**Comment by mikehardy** [comment]
Unsure - if you can dig in to the related PR for the functionality and tag in the author they might know? I haven't exercised this use case and have no special / helpful knowledge in the area, sorry

**Comment by Bardiamist** [comment]
@yoojeen126 Hello, I'm fronted developer and I added `syncUniqueId`.

In my app: backend somehow detecting it and returns error code on which I should to log out user. On that error I calling `syncUniqueId`. That helped for my case.

Also we thought about add the button for it in the settings.
Maybe you can to call `syncUniqueId` once and store flag in `AsyncStrage`.
Then if user will have problem, you can ask him to press the button or reinstall app.

There are many options. Depends on your goals and imagination:)
