### ISSUE TITLE
Support ipv6 addresses

### ISSUE THREAD

**Issue by yoshisuga** [react-native-device-info/react-native-device-info#1135]
## Summary

https://developer.apple.com/support/ipv6/

Apple requires (but hasn't really enforced?) supporting ipv6, and the usage of `inet_ntoa` (an ipv4 specific method) causes some validators to flag this as not supporting ipv6 as required by the Apple App Store rules:

https://github.com/react-native-device-info/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L548

|             |     |
| ----------- | --- |
| Version     |  7.2.1   |
| Affected OS | iOS  |
| OS Version  | 14.2  |

## Current behavior

Usage of `inet_ntoa` is causing a security validator to flag RNDeviceInfo as non-compliant with App Store rules.

## Expected behavior

Support ipv6 addresses by calling `inet_ntop`?

**Comment by mikehardy** [comment]
Interesting - I saw this come up on the netinfo package: https://github.com/react-native-netinfo/react-native-netinfo/pull/431

I'm okay with this strategy, if you want to propose a PR I could review it + merge + release

**Comment by greenantdotcom** [comment]
@mikehardy @yoshisuga Feel free to strip the PR for parts, and the discussion for considerations on the IPv6 front. If y'all are willing to participate in the discussion, we can align the approach across the two products. Thx!

**Comment by mikehardy** [comment]
Just to set expectations: I will be doing no stripping for parts or alteration of anything. I will review and merge a PR that looks good and passes tests but that's the limit on my involvement. If someone proposes a PR, we're in business
