### ISSUE TITLE
how to test getInstallReferrer in local machine, it is being null when i run through emulator

### ISSUE THREAD

**Issue by mobhupath** [react-native-device-info/react-native-device-info#1138]
const referrer = DeviceInfo.getInstallReferrer()
When i log referrer, it is being null, any extra user permissions we need to add?
We already have READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE permissions, any other thoughts would be helpful, thanks.
react-native-device-info version is 2.3.2

**Comment by mikehardy** [comment]
Use a play store emulator image, install from app store?
You should read the docs on the APIs that we call to furnish the getInstallReferrer implementation, such that you are aware of the limitations

https://developer.android.com/google/play/installreferrer/igetinstallreferrerservice
