### ISSUE TITLE
getFreeDiskStorage invalide value

### ISSUE THREAD

**Issue by gh-pro** [react-native-device-info/react-native-device-info#1148]
## Summary
real device ios 14.3 iphone 11pro 
|             |     |
| ----------- | --- |
| Version     |  7.3.1   | 
| Affected OS | ios  |
| OS Version  |  14.3   |

## Current behavior

Value returned if not valid. Systeme os return 23go free space or, method getFreeDiskStorage return 6.9 go
## Expected behavior

i Would like return the real system free disk storage

**Comment by mikehardy** [comment]
No template, no device details, no help, sorry

**Comment by gh-pro** [comment]
> No template, no device details, no help, sorry

hi thanks fo reply, but i don't understand to add details ?

**Comment by gh-pro** [comment]
I use method getFreeDiskStorage in my app real ios 14.3 iphone 11pro and value returned is 6.98go, or in settings->general->about availabie is show 23go,

**Comment by mikehardy** [comment]
Thanks for providing more details.

If you maintained this package, you'd be curious what version of react-native-device-info you were using, right? Please provide that.

Either way, interesting. Is the iPhone configured for any kind of "auto-magical storage management" like "allow the phone to free space used by photos if space is below X%"? Are there any other storage-space / device-info apps you could try to compare values for?

When you reach in to the ios code in node_modules to examine the APIs we call and read their documentation from apple's site, does anything look relevant? Have you tried using any other calls that might be better (from stackoverflow suggestions or similar?)

**Comment by gh-pro** [comment]
I use version 7.3.1, and compare in another app, value i correctly 23go. I use this code directly in xcode `
  long long freeSpace = [[[[NSFileManager defaultManager] attributesOfFileSystemForPath:NSHomeDirectory() error:nil] objectForKey:NSFileSystemFreeSize] longLongValue];
  NSLog(@"super cool %lld", freeSpace);` and return 6go

**Comment by mikehardy** [comment]
That's current version, and that's the API we're using. Very strange. I wonder if similar to Android there are multiple paths we need to check, and aggregate the values? Did anyone else turn up anything like that?

I notice flutter doesn't handle storage free size https://github.com/flutter/plugins/blob/master/packages/device_info/device_info/ios/Classes/FLTDeviceInfoPlugin.m

I wonder if this API is better? https://stackoverflow.com/a/46317698/9910298

**Comment by gh-pro** [comment]
Strange I tested and I still have 6,8go

**Comment by gh-pro** [comment]
I tested in simulated and value freespaceDisk is right. is very stange

**Comment by mikehardy** [comment]
This is vague, and maybe not correct for Apple mobile operating systems, but on macOS at least I see unexpected differences between `df -kh` in Terminal and what the UI shows me, because it "auto-magically" manages storage of iCloud full res photos and TimeMachine local snapshots etc. The disk space is actually taken, but because it is "freeable on demand by some operating system background process" the UI shows you have that space as available.

As a user I find it confusing and sometimes harmful, as a programmer it makes the APIs hard to use.

Perhaps something like this is happening.

**Comment by gh-pro** [comment]
> This is vague, and maybe not correct for Apple mobile operating systems, but on macOS at least I see unexpected differences between `df -kh` in Terminal and what the UI shows me, because it "auto-magically" manages storage of iCloud full res photos and TimeMachine local snapshots etc. The disk space is actually taken, but because it is "freeable on demand by some operating system background process" the UI shows you have that space as available.
> 
> As a user I find it confusing and sometimes harmful, as a programmer it makes the APIs hard to use.
> 
> Perhaps something like this is happening.

Yes i suppose this, in iTunes, my photo library + document  = 56go in total 64gb

**Comment by gh-pro** [comment]
I tester in another iPhone on Photo library is empty and return 3.43go on my app, and in the systeme info 4.71go

**Comment by gh-pro** [comment]
someone has an idea to help ?

**Comment by gh-pro** [comment]
I tested this code and is work correctly in ios.

` uint64_t totalFreeSpace = 0;
    if (@available(iOS 11.0, *)) {
        NSURL *fileURL = [[NSURL alloc] initFileURLWithPath:NSHomeDirectory()];
        NSError *error = nil;
        NSDictionary *results = [fileURL resourceValuesForKeys:@[NSURLVolumeAvailableCapacityForImportantUsageKey] error:&error];
        if (!results) {
            NSLog(@"Error Obtaining System Memory Info: Domain = %@, Code = %ld", [error domain], (long)[error code]);
        } else {
            NSLog(@"Available capacity for important usage: %@", results[NSURLVolumeAvailableCapacityForImportantUsageKey]);
            totalFreeSpace = ((NSString *)results[NSURLVolumeAvailableCapacityForImportantUsageKey]).longLongValue;
        }
    } else {
        NSError *error = nil;
        NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
        NSDictionary *dictionary = [[NSFileManager defaultManager] attributesOfFileSystemForPath:[paths lastObject] error: &error];
        
        if (dictionary) {
            NSNumber *freeFileSystemSizeInBytes = [dictionary objectForKey:NSFileSystemFreeSize];
            totalFreeSpace = [freeFileSystemSizeInBytes unsignedLongLongValue];
        } else {
            NSLog(@"Error Obtaining System Memory Info: Domain = %@, Code = %ld", [error domain], (long)[error code]);
        }
        
    }
          
         
    NSLog(@"Error Obtaining System Memory Info: Domain = %lld", (uint64_t)(totalFreeSpace));`

**Comment by mikehardy** [comment]
triple-backticks with code type for pretty formatting - I fixed your comment

PRs happily accepted!

**Comment by tomgreco** [comment]
@mikehardy you're listed as the top contributor on here so I assume you're the maintainer.

https://github.com/react-native-device-info/react-native-device-info/issues/1148#issuecomment-764748934

This fixes the super busted `getFreeDiskStorage` and hasn't been merged into the code base for over 2 years now... 

cmon guy

**Comment by mikehardy** [comment]
@tomgreco  yeah, let me drop the paid work I have that's behind schedule and ignore my child and workouts for the day and hop right on the issue that's important to you that you haven't patch-packaged ?

Oh wait, YOU DID NOT ACTUALLY POST A PR

POST A PR

From that issue:

>  PRs happily accepted!

As you say, "cmon guy"

**Comment by ryanbourneuk** [comment]
Hey! Been following this thread for a project - @gh-pro's code works and I'd be happy to open a PR over the next few weeks if nobody beats me to it.

_However,_ I must also note that we need to consider that if the app tries to save files whilst 'thinking' it has enough space but actually iOS is secretly consuming some. For example, in my app, I noticed that if I was to copy multiple 2GB+ directories from a USB drive to the app documents, some of the later copies might fail despite the app saying there was ample space available. If I waited a few minutes, it seemed like iOS would catch up and the copies would be successful.

So, is this something we actually want, if the app may not have enough space regardless? If we did want this, then there's some follow up questions:

1. Should we have a new function specifically for this? It feels iffy to change an existing function's behaviour (especially if as mentioned it could impact write operations later on)
2. What should the behaviour on Android be? My app isn't on Android (yet) so I haven't seen if this type of issue exists there too. Should we just proxy on to the existing implementation?

The only reason I see this being helpful is more for informational purposes. We use the existing function for the app-available free space, and a new function for the 'actual' device free space, and then developers could check for differences and handle their flows accordingly.

As mentioned, happy to PR if my schedule stays free & no-one beats me to it :D

**Comment by mikehardy** [comment]
I believe both operating systems now dynamically manage storage by projecting what space you "could" use (perhaps with some latency" *if* they were to delete local items that are also stored in the vendor's cloud systems and the user has allowed the operating system to dynamically manage space.

How do we handle that when we want to really know how much space is available right now with no latency? Honestly, no idea, but I'll consider any reasonable PR.

**Comment by tgreco** [comment]
> @tomgreco  yeah, let me drop the paid work I have that's behind schedule and ignore my child and workouts for the day and hop right on the issue that's important to you that you haven't patch-packaged ?
> 
> 
> 
> Oh wait, YOU DID NOT ACTUALLY POST A PR
> 
> 
> 
> POST A PR
> 
> 
> 
> From that issue:
> 
> 
> 
> >  PRs happily accepted!
> 
> 
> 
> As you say, "cmon guy"
> 
> 

Over a year later and you still couldn't find the time to do a simple fix for this? lol I'm surprised you have any paid work with that work ethic <3

**Comment by mikehardy** [comment]
@tgreco you are a shining example of why open source maintainers burn out, the amount of effort it took to shape up the PR that was posted even was quite a few hours I didn't have to spare but I honored the PR contributors work by seeing it through.

What have you done?

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/7d1a82bf-34d9-4ec2-9e31-e01ed9f421e2">


Nada! Be it hereby known on the internet that Tom Greco is a troll that provides no value

Cheers

**Comment by tgreco** [comment]
Off to do more paid work and abandon your repo? ^_^
