### ISSUE TITLE
Support building without com.android.installreferrer

### ISSUE THREAD

**Issue by saghul** [react-native-device-info/react-native-device-info#1149]
## Description

Would it be acceptable to support building this library without com.android.installreferrer support? I can work on a PR if that is ok.

## Use Case

It's not open source and thus any app using this library cannot be released on F-Droid.

**Comment by mikehardy** [comment]
Very good point, and I'm an F-Droid fan, I'd love to do anything necessary to make sure we support it.
I just merged a change related to install referrer (removing the previous / deprecated style) so that area of code should be free+clear for development, I'd welcome a PR

Thanks!

**Comment by saghul** [comment]
Very nice to hear! I'll try to work on a PR for this tomorrow.

**Comment by saghul** [comment]
✨  https://github.com/react-native-device-info/react-native-device-info/pull/1153 ✨
