### ISSUE TITLE
Use of undelcared identifier 'UIUserInterfaceIdiomMac' [iOS]

### ISSUE THREAD

**Issue by abdullahizzuddiin** [react-native-device-info/react-native-device-info#1151]
## Summary
I'm facing Intent Redirection issue that discussed [here](https://github.com/react-native-device-info/react-native-device-info/issues/1146). Someone has created [PR](https://github.com/react-native-device-info/react-native-device-info/pull/1150) to resolve that issue, hopefully. But, that PR had not been released as official release version. So, I point `react-native-device-info` on `package.json` to `master` branch of this repo to get that changes.

Unfortunately, I got this error below when I built my app.
```
Duplicate case value 'UIUserInterfaceIdiomPad'
---
Use of undeclared identifier 'UIUserInterfaceIdiomMac'; did you mean 'UIUserInterfaceIdiomPad'?
Replace 'UIUserInterfaceIdiomMac' with 'UIUserInterfaceIdiomPad'
```

on `RNDeviceInfo.m`
```
- (DeviceType) getDeviceType
{
    switch ([[UIDevice currentDevice] userInterfaceIdiom]) {
        case UIUserInterfaceIdiomPhone: return DeviceTypeHandset;
        case UIUserInterfaceIdiomPad: return TARGET_OS_MACCATALYST ? DeviceTypeDesktop : DeviceTypeTablet;
        case UIUserInterfaceIdiomTV: return DeviceTypeTv;
        case UIUserInterfaceIdiomMac: return DeviceTypeDesktop;
        default: return DeviceTypeUnknown;
    }
}
```

This issue didn't appear on 7.3.1 version. Seems, it was related to this changes https://github.com/react-native-device-info/react-native-device-info/pull/1137

|             |     |
| ----------- | --- |
| Version     | `master` https://github.com/react-native-device-info/react-native-device-info/commit/9f286d724be1041ec4816c677ff2fff713115f07  |
| Affected OS | iOS   |
| Xcode Version | 11.7   |
| Variant | debug   |
| OS Version  | ?   |

## Current behavior
Failed to build

## Expected behavior
Succeed to build

**Comment by mikehardy** [comment]
Thanks for reporting this, let me check through it and (finally) do the 7.4.0 release that contains the intent redirection fix

**Comment by mikehardy** [comment]
I believe this is mis-diagnosed as originally stated. The error message is actually about a missing symbol, the suggested fix is to replace but that's the wrong direction, the original error is what should have been reported here

When adding catalyst detection support it may be that compilation on non-catalyst builds was broken and that's the avenue I will pursue.

**Comment by mikehardy** [comment]
I can't reproduce this, and it's your Xcode I bet.
Running the example works fine.
Old versions of Xcode are not and will not be supported. For iOS development in general you must be on the latest stable version of Xcode or you are on your own (i.e., use patch-package to maintain a patch that makes it work for you - like just commenting out that line)

**Comment by todorone** [comment]
@mikehardy I experience this same issue trying to upgrade `react-native-device-info` from `7.2.1` to `7.4.0`. I have XCode 11.7, and so far it's not outdated version as React Native 0.63 still has some edge-case incompatibilities with XCode 12. I believe the right way was to publish this version as major update as XCode 12 requirement is pretty breaking change on it's own. In any case, tanks for Your generous contributions to RN OSS...🙏

**Comment by mikehardy** [comment]
Upgrade xcode please

**Comment by mikehardy** [comment]
Wait, you are telling me that xcode 12 is not compatible with react native? Evidence please

**Comment by mikehardy** [comment]
v8 release, v7.4.0 contains a warning

**Comment by abdullahizzuddiin** [comment]
Like this? @todorone 
https://github.com/facebook/react-native/issues/29215

**Comment by mikehardy** [comment]
You mean an issue duplicated by another issue https://github.com/facebook/react-native/issues/29279 that is marked as fixed in 0.63.2 apparently, or via a patch-package patch you can integrate? That does not appear to be a show-stopper to me, I'd upgrade Xcode

Don't get me wrong, I don't like semver major breaks, I'm not arguing that. But I don't see an Xcode 12 blocker in that ref

**Comment by todorone** [comment]
> xcode 12 is not compatible with react native?

I did not say exactly this, probably RN is compatible with XCode 12, but not all dependencies are up to date. When i tried to migrate my production project month ago there were couple of annoying XCode-related issues with compilation to different targets(XC 12 is not backward compatible) and I almost sure not all of them are sorted out. So my point was that requirement to upgrade to XC 12 is breaking change for some not-hello-world projects.

Thanks once again for prompt reaction!

**Comment by mikehardy** [comment]
Interesting, for me was the opposite, I needed Xcode 12 *immediately* in order to continue submitting to App Store because we were touching APIs that had ios14-specific requirements. But that's software - everyone's situation is different. Good luck with your project!

**Comment by cannc4** [comment]
Hey @mikehardy I am facing the same issue here and unable to understand the solution by reading through this. Do we need to update to XCode 12.0 in order to get past the duplicate error?

**Comment by mikehardy** [comment]
If you develop for ios, use current xcode as a general rule. If for whatever reason you stay on an obsolete version you will need an obsolete version of this package as noted in the changelog

**Comment by cannc4** [comment]
... and who decides that the versions are now obsolete? even though it is heavily used in CI/CD platforms? 
I don't really see the value in that mindset either.

**Comment by mikehardy** [comment]
@cannc4 if you want to pedantic okay, but you must realize: people want features. features mean new symbols. Xcode bundles new symbols in new versions. So, to get new features, you need new Xcode. As soon as an Xcode major version comes out then, the old one doesn't have all the features. De facto it is obsolete.

Look, it's open source, you don't want to upgrade? don't! I'm not knocking on your door where you are physically and saying "hey dude, you *MUST* upgrade right now. Stay on the old version. Motivated to actually fix it vs meta discussions on mindset? You could make what appears (from your profile) to be your very first module by figuring out a way to handle this missing symbol on old Xcode versions. I certainly can't be bothered when it's the current version of Xcode is a free download.

**Comment by cannc4** [comment]
Oh wow. can't say that I feel any love with the way you phrase your sentences there. 
I also can not see the connection with me having any OS contributions (although I design open source music instruments) and the topic in this discussion. I suppose getting personal is always easier than trying to think about points made by the other sides.

**Comment by mikehardy** [comment]
I addressed your points.
I apologize for losing my temper though. I will admit it gets under my saddle when people treat this as the complaints department, and yes, I do give a lot more credence to those that contribute. Kudos on your contributions

**Comment by raldred** [comment]
Unfortunately we use a dependency which does not compile in release with xcode 12, so we're held back from updating at  present. I guess there are many different reason why it's not always possible to update immediately.

Sticking to 7.3.2 for now.
