### ISSUE TITLE
getBaseOs stopped working in 8.0.0 for Android

### ISSUE THREAD

**Issue by MateWW** [react-native-device-info/react-native-device-info#1158]
## Summary

| ----------- | --- |
| Version     | 8.0.0   |
| Affected OS |  Android   |
| OS Version  | Pixel 3 API 30 |

## Current behavior

Function `getBaseOs` stopped work. After update it returns empty string.

## Expected behavior

Should return correct value

**Comment by mikehardy** [comment]
How did it look when you reached into node_modules and put some console.log statements before/after native android calls, and inside the java method, System.err.println()'s? How does the example work?

**Comment by schie** [comment]
@MateWW,

 What was the previous version you were using?
