### ISSUE TITLE
Non-existent import in transpiled source

### ISSUE THREAD

**Issue by diego-antonelli** [react-native-device-info/react-native-device-info#1162]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.0.0 & <= 8   |
| Affected OS | All   |
| OS Version  | -   |

## Current behavior

When trying to use rollup, because of some wrong imports and exports the file lib/module/
internal/nativeInterface throws an error in the AsyncHookResult because this is a type and not a function or object.

`Non-existent export 'AsyncHookResult' is imported from ../../../node_modules/react-native-device-info/lib/module/internal/types.js5: import RNDeviceInfo from './internal/nativeInterface';`

## Expected behavior
The transpiled source should not contains imports and exports that results in errors.

Wrong line codes:
lib/module/index.js -> Lines 7 and 701

```
import { AsyncHookResult, DeviceType, LocationProviderInfo, PowerState } from './internal/types';
```
```
export { AsyncHookResult, DeviceType, LocationProviderInfo, PowerState };
```

**Comment by mikehardy** [comment]
Interesting... Could you propose a PR that corrects it for you?

**Comment by diego-antonelli** [comment]
@mikehardy this is the fix for the issue -> https://github.com/react-native-device-info/react-native-device-info/pull/1164
