### ISSUE TITLE
Support for Out-of-Tree Platforms

### ISSUE THREAD

**Issue by johnwcassidy** [react-native-device-info/react-native-device-info#1166]
## Description

When using `react-native-device-info` package with an Out-of-Tree platform, a native module is required named `RNDeviceInfo` as it is with iOS, Android, and Windows. Even if this module is present (which is required or it will throw an exception when creating the DeviceEmitter), it is never called as there is little desire (understandably) to add these out-of-tree platforms to the `supported-platforms` lists on each method definition.

If an Out-of-tree platform is using this package, it should be given the chance to support the various methods and call it's own defined `RNDeviceInfo` native module for the response.

## Use Case

A new out-of-tree platform (Foo) is added and wishes to return the deviceId. At present it will return `unknown`, but if it defines its own native module it can return the deviceId for the platform Foo.

**Comment by mikehardy** [comment]
If you post some code to do what you want, we can probably merge it. I don't spend a lot of time thinking of things in the abstract though, sorry. In general: sure, PRs happily accepted :-)
