### ISSUE TITLE
Different getUniqueId after version upgrade

### ISSUE THREAD

**Issue by InkOut** [react-native-device-info/react-native-device-info#1169]
## Summary
Different getUniqueId after version upgrade

| Version     | ?  3.1.4 -> 8.0.1  |
| Affected OS | ?  ios |

## Current behavior

1. Install react-native-device-info v3.1.4 
2. Call getUniqueId -> get old ID (id1)
3. Upgrade to 8.0.1
4. Call getUniqueId -> get new ID  (id2)
5. Downgrade to v3.1.4 
6. Call getUniqueId -> get old ID  (id1)
3. Upgrade to 8.0.1
4. Call getUniqueId -> get new ID  (id2)
5. Call syncUniqueId -> get new ID  (id2)
5. Downgrade to v3.1.4 
6. **Call getUniqueId -> get new ID  (id2)**

## Expected behavior

Always get the same id

**Comment by InkOut** [comment]
@Bardiamist @dmitry-bluescape maybe you know? Only 2 commits after 3.1.4
react-native-device-info/ios/RNDeviceInfo/DeviceUID.m

**Comment by Bardiamist** [comment]
Did you tried on device or on simulator? I faced with it recently and found out that that happening only on ios simulator.

**Comment by InkOut** [comment]
@Bardiamist on device

**Comment by Bardiamist** [comment]
@InkOut I don't know what was in `3.1.4`. I only added `syncUniqueId`. That should't any effect on `getUniqueId`.

Also maybe not helpful but I can say that I just tested update from `7.0.2` to `8.0.1` on iOS (simulator and device) and Android (emulator). And did not meet any problem with device id.

**Comment by beezyb2** [comment]
syncUniqueId

**Comment by enesbildiren95** [comment]
I get different UniqueId in different apps on the same phone. What would be the reason?

**Comment by mikehardy** [comment]
@enesbildiren95 - check the native APIs used for the getUniqueId implementation, read about how those APIs are implemented and the privacy concerns addressed by the implementation, report findings here.

**Comment by enesbildiren95** [comment]
@mikehardy Thank you. I found the answer I was looking for here. [https://developer.android.com/about/versions/oreo/android-8.0-changes#privacy-all](url) That is the expected behaviour on Oreo and above devices.

**Comment by lisichka999** [comment]
@InkOut does syncUniqueId fix your problem?

**Comment by rafaelmaeuer** [comment]
I do have a very similar problem: I recently updated all RN dependencies of my project including this lib from v5.6.1 to v8.1.2. 

The function `getUniqueId()` is used to sync user data (game highscores) with a server. This way I can restore the link between user and highscore although the app was deleted once and installed again later. I was wondering why this process stopped working until I had a closer look at the generated UserID. 

With v8.1.2 after every App deletion a new UserID is generated which breaks my sync-logic for user-highscores. I rolled back to v5.6.1 and it is still working as expected. I already tried implementing the `syncUniqueId()` function with v8.1.2., but without any success. Does anyone has knows how to solve this problem? 

Another interesting question I am asking myself: will this uniqueID be persistent with iOS 14.5 and the new privacy-feature?

**Comment by mikehardy** [comment]
maybe what we want is https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlock ?

**Comment by rafaelmaeuer** [comment]
That is the value which is used in the current version and doesn't work as expected. It seems that keystore access to the key `@"deviceUID"` is restricted with this setting. Therefore a new random key is generated, but I don't understand why access to this key is failing

**Comment by rafaelmaeuer** [comment]
No of cause not... I have no clue what causes this problem. I created a branch which reverts the change: https://github.com/rafaelmaeuer/react-native-device-info/tree/fix-getUniqueId-iOS

This is only a temporary fix until a solution is identified, but for now I don't have enough time and effort.
Feel free to use this branch, I will keep it in sync with this repo's master from time to time.

**Comment by mikehardy** [comment]
Easier: just patch it and use patch-package, that way you don't have to do branch maintenance https://github.com/ds300/patch-package

**Comment by InkOut** [comment]
@rafaelmaeuer I think it might be because iOS runs app in background (Push notifications, Preloadings(?)). Could you test this https://stackoverflow.com/questions/40614486/checking-for-ios-device-first-unlock-to-determine-if-items-stored-with-ksecattra solution and crash app if keychain is not available?

**Comment by InkOut** [comment]
the other idea, that we need something like a migration.
1. Get value with kSecAttrAccessibleAlways
2. Set value with kSecAttrAccessibleWhenUnlocked
3. Delete value with kSecAttrAccessibleAlways

**Comment by weiningtry7** [comment]
> the other idea, that we need something like a migration.
> 
> 1. Get value with kSecAttrAccessibleAlways
> 2. Set value with kSecAttrAccessibleWhenUnlocked
> 3. Delete value with kSecAttrAccessibleAlways

> 1. if (!_uid) _uid = [[self class] valueForAccessibleAwaysKeychainKey:UIDKey service:UIDKey];
    if (!_uid) _uid = [[self class] valueForKeychainKey:UIDKey service:UIDKey];
> 2.- (void)saveIfNeed {
  if (![DeviceUID valueForUserDefaultsKey:UIDKey]) {
    [DeviceUID setValue:_uid forUserDefaultsKey:UIDKey];
  }
  if ([DeviceUID valueForAccessibleAwaysKeychainKey:UIDKey service:UIDKey]) {
      [DeviceUID deleteValueForKeychainKey:UIDKey inService:UIDKey];
      [DeviceUID setValue:_uid forKeychainKey:UIDKey inService:UIDKey];
  }
  if (![DeviceUID valueForKeychainKey:UIDKey service:UIDKey]) {
    [DeviceUID setValue:_uid forKeychainKey:UIDKey inService:UIDKey];
  }
}

I used this method a moth ago, don't find problem so far

**Comment by harveyconnor** [comment]
Yep also getting this.
I use it for push notifications etc. will migrate to another solution until this lib is fixed.

**Comment by mikehardy** [comment]
@harveyconnor much more useful to post a PR here, and I can release it essentially immediately. Tangent solutions are a waste of developer effort IMHO

**Comment by mikehardy** [comment]
For everyone - happy to merge a solution here if anyone proposes one. I think there is something brewing here in the same area as well - #1226

**Comment by mikehardy** [comment]
(also note for easy of development: it's trivial to hack around in node_modules with https://github.com/ds300/patch-package supporting your work so it doesn't evaporate, then post a PR here when something is working)

**Comment by Bardiamist** [comment]
> I think we need to roll back to kSecAttrAccessibleAlways and work on solution that would actually work with kSecAttrAccessibleWhenUnlocked. No reason to use kSecAttrAccessibleWhenUnlocked today.

`kSecAttrAccessibleAlways` [is depricated](https://developer.apple.com/documentation/security/ksecattraccessiblealways)

**Comment by InkOut** [comment]
> kSecAttrAccessibleAlways is depricated

I know, but deprecated doesn't mean "not allowed", we just need to find a better solution until this method is removed.

"kSecAttrAccessibleAfterFirstUnlock"  is not working on iOS.

**Comment by mikehardy** [comment]
I'm not going to accept re-addition of a deprecated as a pull request though of course feel free to use patch-package locally - I say that to emphasize I'm not trying to be belligerent as patch-package works fantastically.

I'm watching this but it's not a use case I personally care about so I'll need some sort of consensus and a PR based on that in order to merge a real forward solution - but please no retrograde (deprecated) motion

**Comment by mikehardy** [comment]
@matrixyf 

From before:

>  I'm watching this but it's not a use case I personally care about so I'll need some sort of consensus and a PR based on that in order to merge a real forward solution - but please no retrograde (deprecated) motion

A PR would be merged if it had an explanation of the use case(s) that is/are failing (which you have done a bit in your commit) and links to apple's developer documentation supporting your assertions of the old code having problems in your use case and to the documents that show you your use case and all currently supported use cases will be properly handled with the code in your proposed pull request

**Comment by tkud04** [comment]
Hi guys, so I'm facing this issue as well. My use case:
We have a banking app with 2 versions, v1 and v2. v2 is about to be released but we noticed that the different versions of react-native-device info are giving 2 different device IDs. 

So when a user who has signed in previously with v1 is trying to sign in on v2, the app is going the 'change device?' flow because the device ID is different. What do you suggest we do here please?

v1
React-native-device-info version: ^8.4.4
Method: DeviceInfo.getUniqueId()
 
v2
React-native-device-info version: ^10.6.0
Method: DeviceInfo.getUniqueIdSync()

**Comment by LevanKvirkvelia** [comment]
@tkud04 i switched to https://github.com/oblador/react-native-keychain for storing a unique ID.

**Comment by guillaumekh** [comment]
@tkud04 we patch during npm postinstall

```patch
--- node_modules/react-native-device-info/ios/RNDeviceInfo/DeviceUID.m	2022-06-15 11:44:04.000000000 +0200
+++ DeviceUID.m	2022-06-15 11:53:42.000000000 +0200
@@ -91,7 +91,7 @@
 + (NSMutableDictionary *)keychainItemForKey:(NSString *)key service:(NSString *)service {
     NSMutableDictionary *keychainItem = [[NSMutableDictionary alloc] init];
     keychainItem[(__bridge id)kSecClass] = (__bridge id)kSecClassGenericPassword;
-    keychainItem[(__bridge id)kSecAttrAccessible] = (__bridge id)kSecAttrAccessibleAfterFirstUnlock;
+    keychainItem[(__bridge id)kSecAttrAccessible] = (__bridge id)kSecAttrAccessibleAlways;
     keychainItem[(__bridge id)kSecAttrAccount] = key;
     keychainItem[(__bridge id)kSecAttrService] = service;
     return keychainItem;
```

`patch -p0 < DeviceUID.patch`

TBH though it's lazy & dangerous because Apple has deprecated and will eventually retire support for `kSecAttrAccessibleAlways`.
