### ISSUE TITLE
@InkOut I don't know what was in `3.1.4`. I only added `syncUniqueId`. That should't any effect on `getUniqueId`.

### ISSUE THREAD

**Issue by beezyb2** [react-native-device-info/react-native-device-info#1170]
@InkOut I don't know what was in `3.1.4`. I only added `syncUniqueId`. That should't any effect on `getUniqueId`.

Also maybe not helpful but I can say that I just tested update from `7.0.2` to `8.0.1` on iOS (simulator and device) and Android (emulator). And did not meet any problem with device id.

__Originally posted by @Bardiamist in https://github.com/react-native-device-info/react-native-device-info/issues/1169#issuecomment-773876587__

**Comment by mikehardy** [comment]
This does not look like an issue, it contains no description of steps to reproduce, experienced behavior, difference from expected behavior.
