### ISSUE TITLE
get imei

### ISSUE THREAD

**Issue by sam9010** [react-native-device-info/react-native-device-info#1172]
hi i want to get imei and my version react-native-device-info package is 6.0.4

**Comment by gax97** [comment]
This is currently not possible since Apple doesn't allow you to programmatically get IMEI from the phone.

**Comment by sam9010** [comment]
i want just android

**Comment by mikehardy** [comment]
Have you read the security changes in Android :thinking:  ? @sam9010 please research the IMEI Android APIs, along with the release notes for android 9, 10, 11 etc (privacy sections) and report your findings

**Comment by sam9010** [comment]
I just want an ID that differentiates users
my app do not have login( i thinked imei is good choose)

**Comment by mikehardy** [comment]
@sam9010 then you should use async-storage and UUIDv4

**Comment by sam9010** [comment]
can i use AndroidId?

**Comment by mikehardy** [comment]
No one can say conclusively what you can use and cannot use. Every app has different needs, and Android APIs in this area change as Android moves on. To be clear: do your own research and come to your own conclusion, it's the only safe bet in this area.

My suggestion is likely to be sufficient based on your terse description of requirement but you must come up with your own decision for your own project.
