### ISSUE TITLE
sh: husky: command not found

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-native-device-info/react-native-device-info#1176]
I got postinstall issue with husky with the newest version. I guess it should be `npx husky install` ?

**Comment by mikehardy** [comment]
Oh no! @lorenc-tomasz can you detail your exact steps - like was this from a developer's perspective working on the module directly, or was this as a consumer (and I have unexpectedly blown up all our users :scream: )

I have a vague recollection that npx will go away so I think it should be `yarn husky install` or since npm is guaranteed to be there `npm husky install` (or however you call npm to run a project-internal command)

**Comment by lorenc-tomasz** [comment]
I did `npm i` ;) and got:

```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! react-native-device-info@8.0.3 postinstall: `husky install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-native-device-info@8.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by cristianoccazinsp** [comment]
Same, what's husky? Where did it get added? Looks like we are getting more and more "tracking" stuff from npm lately :D

**Comment by mikehardy** [comment]
I have tested a local change to react-native-device-info package.json that just alters that line to `npm husky install` and it appears to work perfectly

**Comment by mikehardy** [comment]
Scratch that, no way to run postinstall conditionally, and while I can get the postinstall to run, this would install it for everyone, which is silly. It's a great package and I recommend it but installing things for other people is rude and not okay at all.

v8.0.5 is out just now and should fix things? Hopefully one of you can confirm? Worked for me in my work project

**Comment by mikehardy** [comment]
@MoOx - I did not (yet) - we already use that hook but I wanted to read up on it more. Thanks for the positive confirmation that it works well for you. I didn't want to leave the busted version out there for one second longer than necessary though so queued the "real fix" behind the "get it working immediately" fix :-)

**Comment by lorenc-tomasz** [comment]
@mikehardy 8.0.5 works :) Thank you :) 

As @MoOx wrote, you should check `prepare` :)
