### ISSUE TITLE
isEmulator not detecting bluestacks instance

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-native-device-info/react-native-device-info#1177]
I gather from other issues posted that this is supposed to be fixed now(?), but the promise is still returning false on bluestacks instances.

version: 8.0.5

**Comment by mikehardy** [comment]
Hi there!

Things change over time, perhaps bluestacks has some new identifier.

Here's the detection, figure out what is actually being returned by bluestacks and propose a PR that accurately detects them with no false positives and I can merge + release

https://github.com/react-native-device-info/react-native-device-info/blob/c50b1b93621e6241331e5422c28ec774845a304a/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L211-L237

**Comment by JeremyBradshaw7** [comment]
I did look but didn't find any of the information returned by bluestacks that would definitely identify it as an emulator.

**Comment by mikehardy** [comment]
Then I'm afraid there is nothing we can do. Very strange they don't provide *anything*, but if there is no 100% way without false positive then I guess we have to move on. If anyone in the future can figure out foolproof bluestacks detection, I'll merge it sure

**Comment by phuongwd** [comment]
@roybselim thanks for temp fix,

"Package Names 2" is [Package Name Viewer 2.0](https://play.google.com/store/apps/details?id=com.csdroid.pkg&hl=en&gl=US) , right?

If so, I dont see the package `gg.now.accounts`, please see screenshot
<img width="1189" alt="Screen Shot 2022-08-08 at 15 00 00" src="https://user-images.githubusercontent.com/2460806/183369156-030551cc-db3c-43d4-af6a-14e04f152626.png">

**Comment by roybselim** [comment]
> @roybselim thanks for temp fix,
> 
> "Package Names 2" is [Package Name Viewer 2.0](https://play.google.com/store/apps/details?id=com.csdroid.pkg&hl=en&gl=US) , right?
> 
> If so, I dont see the package `gg.now.accounts`, please see screenshot <img alt="Screen Shot 2022-08-08 at 15 00 00" width="1189" src="https://user-images.githubusercontent.com/2460806/183369156-030551cc-db3c-43d4-af6a-14e04f152626.png">

Hi, I am not sure if package names 2 is the same as package name viewer 2.

**Comment by qayyummdnoor** [comment]
I did get bluestacks emulator props and it return the same as real device. Seems impossible to detect app running on bluestack. Still didn't found any workaround for this

bluestacks version 4.2

**Comment by JeremyBradshaw7** [comment]
mumuplayer seems to be the same, our preferred emulator over bluestacks now.
