### ISSUE TITLE
Unable to compile with Mac Catalyst  13

### ISSUE THREAD

**Issue by marcosrdz** [react-native-device-info/react-native-device-info#1178]
https://github.com/react-native-device-info/react-native-device-info/blob/c50b1b93621e6241331e5422c28ec774845a304a/ios/RNDeviceInfo/RNDeviceInfo.m#L116

This UIIdiom is only available in native macOS and Mac Catalyst 14. This breaks the ability to compile with Mac Catalyst 13.

**Comment by mikehardy** [comment]
PRs happily merged!

**Comment by mikehardy** [comment]
Hi there - after some investigation and testing on #1181 it appears that Xcode 12, which is the minimum for react-native these days (a reasonable stance, it's needed for new APIs) won't let you target catalyst 13 anymore, so requiring catalyst 14 seems reasonable
