### ISSUE TITLE
Unknown device model in arm64 iOS Simulator on M1 Mac

### ISSUE THREAD

**Issue by Arkkeeper** [react-native-device-info/react-native-device-info#1179]
RNDeviceInfo.m methods are using these checks to detect whether app is running in iOS Simulator:

`if ([deviceId isEqualToString:@"i386"] || [deviceId isEqualToString:@"x86_64"]`

It works for Intel Macs, but not for Apple Silicon Macs, where iOS Simulator runs on the same arm64 architecture as on real iOS devices.

## Summary

|             |     |
| ----------- | --- |
| Version     | 8.0.5   |
| Affected OS | iOS Simulator (M1 Mac)  |
| OS Version  | 14.4   |

## Current behavior

**DeviceInfo.getModel()** and other model-related methods return wrong values (unknown, null, false, etc).

## Expected behavior

As a workaround, if I use `#if TARGET_IPHONE_SIMULATOR` macro in **getDeviceId** and **isEmulator** methods in RNDeviceInfo.m, everything works as it should. So, it would be great to modify those simulator checks.

**Comment by mikehardy** [comment]
PRs happily accepted! You can modify those checks and post a PR and we can merge it
