### ISSUE TITLE
getUniqueId() return different UUID after application reinstall in IOS

### ISSUE THREAD

**Issue by lisichka999** [react-native-device-info/react-native-device-info#1183]
## Summary
IOS
RN 62
package version 3.0.0 (upgrade from 2)
## Current behavior

The application in IOS device receive different UUID each time when app reinstalled

## Expected behavior

The application should receive the same UUID each time

**Comment by mikehardy** [comment]
I don't believe this is possible sorry
Most of what the operating system vendors (android, iOS) have done in the last few years is make this impossible on purpose
Persistent tracking via unique IDs is not a thing they encourage and if you find a way to do it they will do their best to block you in the future.

My recommendation? Look at the *exact* APIs we use. If you can find a way we are not using them correctly, *then* we can reopen this

If we are using the available APIs correctly then, what we have is something that does not meet your expectations but it is not actually a bug

**Comment by Thientran2910** [comment]
@mikehardy 
I'm really test on iphone 8 Plus, Iphone 12 Pro max.
My app run on React native 0.63.3. Xcode 12.4, macOS Big Sur 11.2.3.
I'm using storage device info to support customer when need, I'm really when app reinstall function getUnique generate new id. Please check this issue.
Thank you very much.

**Comment by mikehardy** [comment]
@Thientran2910 you completely ignored my comment.

**Comment by lisichka999** [comment]
@mikehardy  Thanks for answering.
I found this [thread](https://stackoverflow.com/questions/40230246/device-uuid-not-unique-when-user-uninstall-and-re-install)
And notice that you also use identifierForVendor API.

**Comment by mikehardy** [comment]
> iOS: This is IDFV or a random string if IDFV is unavaliable. Once UID is generated it is stored in iOS Keychain and NSUserDefaults. So it would stay the same even if you delete the app or reset IDFV. You can carefully consider it a persistent, cross-install unique ID. It can be changed only in case someone manually override values in Keychain/NSUserDefaults or if Apple would change Keychain and NSUserDefaults implementations. Beware: The IDFV is calculated using your bundle identifier and thus will be different in app extensions.

Package version now is 8, you should retry with current versions and see if the keychain syncing code works for you

Logging issues against old versions is inefficient as frequently the issue is solved already (as I think this one might be?)
