### ISSUE TITLE
No way to get android versionCode

### ISSUE THREAD

**Issue by niwla23** [react-native-device-info/react-native-device-info#1188]
I was unable to find a way to get the versionCode for android. I mean the specified one in build.gradle, where you have this:

```
versionName=1.2.0
**versionCode=3**
```

**Comment by mikehardy** [comment]
may be possible to split getReadableVersion on `.` and take the last chunk https://github.com/react-native-device-info/react-native-device-info#getreadableversion

it's the information you are looking for based on the code - did you look? https://github.com/react-native-device-info/react-native-device-info/blob/7f435dceeb52b5adbac55af2d48f1a257fc1636e/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L180

**Comment by niwla23** [comment]
I just found out it is overwritten per abi, so I can use that value too.

**Comment by DhavalsShah** [comment]
`DeviceInfo.getBuildNumber() `will work to get version code.
https://github.com/react-native-device-info/react-native-device-info/blob/7f435dceeb52b5adbac55af2d48f1a257fc1636e/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L180
