### ISSUE TITLE
iOS CI silently passes compile failures / does not verify example app ran

### ISSUE THREAD

**Issue by mikehardy** [react-native-device-info/react-native-device-info#1191]
## Summary

CI environment is running iOS build but incorrectly reports success despite build failures

## Current behavior

Example:
https://github.com/mikehardy/rnfbdemo/commit/f84ad523b37f19db46ac0710396c4769ea024808

## Expected behavior

CI should have reported a failure

The underlying failure here needs a fix as well (it appears the iOS extension needs some compiler magic to compile correctly?) but I definitely want to see CI failing the iOS build correctly

**Comment by schie** [comment]
I'll look into this.

**Comment by mikehardy** [comment]
Not sure what changed but just did some CI work in #1638 and it was definitely failing the CI build until I put in a fix so that new Xcode could compile our stale example

Still doesn't verify the app ran, but not sure how to do that easily. Just seeing it built is good though
