### ISSUE TITLE
Unable to find React-Core specification

### ISSUE THREAD

**Issue by ApWin** [react-native-device-info/react-native-device-info#1192]
After installing react-native-device-info@7.4.0 to react-native@0.62.2. I runned cd ios&& pod install. After that following error occured  ```Unable to find a specification for `React-Core` depended upon by `RNDeviceInfo````

| Version     | 7.4.0  |
| React  | 16.11.0 |
| react-native | | 0.62.2 |
| OS Version  | MacOS Big Sure  |
<img width="934" alt="Screen Shot 2021-04-01 at 23 22 35" src="https://user-images.githubusercontent.com/38643533/113337419-2fdb7180-9341-11eb-9e71-5d2f96871aa7.png">

**Comment by mikehardy** [comment]
common problem, specs out of date probably. Definitely not a problem with this module

https://duckduckgo.com/?t=ffab&q=unable+to+find+a+specification+for+react-core
