### ISSUE TITLE
Question, is there any constant value for a device Id? IOS changes (getUniqueId)

### ISSUE THREAD

**Issue by yazmnh87** [react-native-device-info/react-native-device-info#1193]
I've looked through is there a method for IOS/android that provides a constant deviceID?  getUniqueId with IOS changes if you uninstall/reinstall the app.  I've look through other methods and can seem to find one that will work, any suggestions?

| Version     | 8.0.8  |
| Affected OS | ios/android   |

**Comment by mikehardy** [comment]
No. What you want violates privacy by enabling persistent tracking, and so is disallowed by the vendors on purpose.

**Comment by mikehardy** [comment]
Well, I guess for completeness I should say if you are an device manufacturer (you are not, I would bet) you can use some of the super privileged permissions and get some persistent and unique identifiers but at that point you also would know more than I do about such things and would not be asking me ;-)
