### ISSUE TITLE
getHost() does not actually return the hostname on Android

### ISSUE THREAD

**Issue by garrottkai** [react-native-device-info/react-native-device-info#1194]
## Summary

|             |     |
| ----------- | --- |
| Version     | latest   |
| Affected OS | Android   |
| OS Version  | all   |

## Current behavior

The [`getHost()`](https://github.com/react-native-device-info/react-native-device-info#gethost) and `getHostSync()` methods [return the value of `android.os.Build.HOST`](https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L740), which identifies the host machine on which the ROM was compiled, rather than the hostname of the Android device.

## Expected behavior

These methods should return the network-facing device hostname.

I can open a PR for this if needed. There is no public API in Android for retrieving the hostname, but it can be accessed with a shell command.

**Comment by mikehardy** [comment]
Interesting...I'd certainly be willing to look at a PR for getHostname(), I'm curious if shelling out is allowed under all circumstances / works on all android versions etc as this seems likely to be prone to runtime failure vs compile time failure as the command you need to run might vary over time, but...I dunno, could work?

Would be good to see some links (even if just stackoverflow) detailing why this method is the only available one and what others are doing in the area
