### ISSUE TITLE
node_modules/react-native-device-info/src/index.ts: Unexpected token (12:12)

### ISSUE THREAD

**Issue by cj768025549** [react-native-device-info/react-native-device-info#1212]
During npm start ... I get this error

error: bundling failed: SyntaxError: .../node_modules/react-native-device-info/src/index.ts: Unexpected token (12:12)
![image](https://user-images.githubusercontent.com/3918091/114139191-4edd9300-9941-11eb-901e-14cda70a1b39.png)

I have already updated it to the latest version (8.0.8), but it still has the error. And my typescript version is 3.9.7.

**Comment by mikehardy** [comment]
This *smells* like it was addressed in the v8 changelog area:

> Note, if you use typescript, this requires a minimum version of typescript 3.8 This change was inadvertently released without realizing it was a breaking change, apologies. It is close enough to the 8.0.0 release that it will stand here though, without bumping to 9.0.0

You assert that your typescript version is 3.9.7. I would guess that the typescript version in actual use is not >= 3.8 somehow based on the error message

**Comment by Sid-Shanker** [comment]
Got the same issue. Had to downgrade the version:
`"react-native-device-info": "8.0.0"`
It worked.

**Comment by mikehardy** [comment]
Better to upgrade typescript, but yes, 8.0.0 will work with stale typescript versions

**Comment by fredmanxu** [comment]
I have a same problem.
` "react-native": "^0.63.3"`
`"react-native-device-info": "^8.0.2",`
My typescript version is `4.2.4`,I try downgrade the version `"react-native-device-info": "^8.0.0",`. 
It worked.

**Comment by mikehardy** [comment]
@fredmanxu the only explanation that fits those facts is that you think you are using a compatible version of typescript but somehow, somewhere in your build chain you are not

**Comment by douglasjunior** [comment]
How to use without typescript?

**Comment by zoultrex** [comment]
Version 7.4.0 works for me on RN 0.61.5

**Comment by mikehardy** [comment]
@zoultrex 

> Should I keep trying to downgrade untill some version works?

I think you meant "Should I update all my packages so I'm running current stable versions?"

To which the answer is Yes! That's the best path, then everything will work and you can actually get support for any problems that come up

**Comment by zoultrex** [comment]
> @zoultrex
> 
> > Should I keep trying to downgrade untill some version works?
> 
> I think you meant "Should I update all my packages so I'm running current stable versions?"
> 
> To which the answer is Yes! That's the best path, then everything will work and you can actually get support for any problems that come up

Thats on my todo list, but I just don't have the time right now to upgrade React Native and everything else that comes after that change.

But I do totally agree, stay on the latest stable version is always the best approach
