### ISSUE TITLE
Feature suggestion: is app installed from store (App Store/Google Play)

### ISSUE THREAD

**Issue by dimaportenko** [react-native-device-info/react-native-device-info#1216]
I had a task to separate analytics in the app installed from the store (App Store/Google Play) and all other builds from Testflight, direct APKs, in development, etc. 

I've implemented it with native modules
iOS - [iOS stackoverflow answer](https://stackoverflow.com/questions/18282326/how-can-i-detect-if-the-currently-running-app-was-installed-from-the-app-store/18619270#18619270) and [App Center SDK solution](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenter/AppCenter/Internals/Util/MSACUtility%2BEnvironment.m)    
Android - [Android stackoverflow solution](https://stackoverflow.com/questions/37539949/detect-if-an-app-is-installed-from-play-store/37540163#37540163)

I would like to share my solution with the community and I think this library could be a good place to do it. 

Please let me know if this feature suits this library I'll do PR then.

**Comment by mikehardy** [comment]
It would definitely fit, we already have it for Android and Windows actually https://github.com/react-native-device-info/react-native-device-info#getinstallerpackagename

If any other platforms are missing or the current platforms may have better implementations please post a PR, we'll happily merge it
