### ISSUE TITLE
@react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.

### ISSUE THREAD

**Issue by nagesh-bv** [react-native-device-info/react-native-device-info#1218]
## Summary

|             |     |
| ----------- | --- |
| Version     | ?0.63.3  |
| Affected OS | iOS |
| OS Version  | iOS 14.4  |

## Current behavior

 @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
      • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
      • Rebuild and re-run the app.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
      If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info

      at Object.<anonymous> (node_modules/react-native-device-info/lib/commonjs/internal/nativeInterface.ts:20:11)
      at Object.<anonymous> (node_modules/react-native-device-info/lib/commonjs/index.ts:5:1)

**Comment by mikehardy** [comment]
You have not integrated the module correct. Common react-native + native module problem.

It's project specific, the module is fine.

Examine refresh-example.sh from this project and/or the example itself.
