### ISSUE TITLE
isTablet() returns wrong value for Android Phablets such as the HUAWEI MediaPad M5 Android 9

### ISSUE THREAD

**Issue by taongocsontam** [react-native-device-info/react-native-device-info#1219]
isTablet() returns wrong value for Android Phablets such as the HUAWEI MediaPad M5
Android 9

**Comment by schie** [comment]
@taongocsontam, what value are you getting / expecting? 

The term, `Phablet`, itself doesn't help since that kinda means something in-between the two. 

From the source code, we're using the [screen-size buckets defined by google](https://android-developers.googleblog.com/2011/07/new-tools-for-managing-screen-sizes.html) and some diagonal size logic:
```java
 if (diagonalSizeInches >= 3.0 && diagonalSizeInches <= 6.9) {
      // Devices in a sane range for phones are considered to be Handsets.
      return DeviceType.HANDSET;
    } else if (diagonalSizeInches > 6.9 && diagonalSizeInches <= 18.0) {
      // Devices larger than handset and in a sane range for tablets are tablets.
      return DeviceType.TABLET;
    } else {
      // Otherwise, we don't know what device type we're on/
      return DeviceType.UNKNOWN;
    }
```

**Comment by wakinochien** [comment]
I faced the same issue when the user change the display size from phone's setting 

If i changed the display size to larger/largest, 
it return false for isTablet() and return handset for getDeviceType()

![image](https://user-images.githubusercontent.com/4964965/128473465-17973252-1ed0-496c-a091-0ee2ef95a332.png)


device tested: huawei matepad T

**Comment by mikehardy** [comment]
Hi there! It's just a heuristic here, the idea is that it will tell you approximately if the phone has enough screen real estate to use a tablet-oriented (that is, more complicated) layout

It sounds like you need more direct control for your layout?

If so, you will probably want to get the Dimensions and operate on it directly?

https://reactnative.dev/docs/dimensions
