### ISSUE TITLE
Native module cannot be null ?

### ISSUE THREAD

**Issue by aytacmalkoc** [react-native-device-info/react-native-device-info#1222]
Hi, I got the error `native module cannot be null`. Could I be getting this error because I'm developing using Expo?

**Comment by mikehardy** [comment]
This error is because you are developing using Expo.
Expo managed workflow is completely incompatible with other native modules.
Bare workflow can work, ejected can work.

**Comment by namti** [comment]
> In iOS I am facing this issue and I am not using expo

Run `pod install` in the `/ios` directory then rebuild and re-run the APP.
