### ISSUE TITLE
Illegal invocation from getBattery call

### ISSUE THREAD

**Issue by Njaah-0** [react-native-device-info/react-native-device-info#1223]
Not 100% sure if this is actually an issue within this project, but though I would ask if someone happens to have some information on this.
## Summary
Affected platform: web
|             |     |
| ----------- | --- |
| Version     | 6.2.1   |
| Affected OS | all   |
| OS Version  |  No pattern  |

## Current behavior
Some users apparently receive `TypeError: Failed to execute 'getBattery' on 'Navigator': Illegal invocation.`
This is coming from `react-native-device-info/lib/module/web/index.js in init`. 
I did some research and error would indicate that the call is missing context (for navigator object), but based on code I have no idea how this could be. Perhaps the call should be prefixed with `window.`?
So far we have had 156 users getting this error, so it seems pretty common although it does not happen to me. 
<img width="1056" alt="Screenshot 2021-04-21 at 9 24 22" src="https://user-images.githubusercontent.com/14109820/115506715-dd2c1000-a283-11eb-93e1-ff372c75cdfd.png">

## Expected behavior
If getBattery call is found from navigator, call should not give error and no call should happen if method is not supported.

**Comment by mikehardy** [comment]
This could be in the library - I have not actually used it myself (the web port) as it was contributed by the community. As such I won't be able to help much (apologies!) but anything you find, and anything fixable would be interesting and if it needs fixing here I'd happily take a PR and kick out a release

**Comment by ZerdoX-x** [comment]
@Njaah-0 for me its yandex metrika: https://mc.yandex.ru/metrika/tag.js

**Comment by farukbigez** [comment]
@ZerdoX-x is this error blocking the access to the web page?

**Comment by ZerdoX-x** [comment]
> @ZerdoX-x is this error blocking the access to the web page?

Nope

**Comment by Njaah-0** [comment]
Yup, still happening.

**Comment by mikehardy** [comment]
Believe it or not I'm starting to get a lot more in to react-native-web, so there's a hope of this getting fixed soon :-)

@Njaah-0 what is your experience when you try the fix from #1333 ?

**Comment by Njaah-0** [comment]
@mikehardy I'm still unable to reproduce the issue within my local development environment, so I decided to add a patched version of the library to production. Let's see if the error reappears.

**Comment by Njaah-0** [comment]
It would seem that my patch based on https://github.com/react-native-device-info/react-native-device-info/pull/1333 didn't affect the error appearance rate, it's still happening.

**Comment by kperdomo1** [comment]
still relevant :) `react-native-device-info` v8.3.3

**Comment by sophie-li** [comment]
Still happening on react-native-device-info: ^10.4.0 🤔
