### ISSUE TITLE
getUniqueId() is different for release build (android)

### ISSUE THREAD

**Issue by Balthazar33** [react-native-device-info/react-native-device-info#1234]
## Summary
|                  |       |
| ----------- | --- |
| Version     | 8.1.0  |
| Affected OS | android   |
| OS Version  | 10   |

## Current behavior

The `getUniqueId()` API returns the one device id for debug build but when a release build is generated, it returns a different one.

## Expected behavior

The  `getUniqueId()` API should return the same device id even in release build

React Native version : **0.63.4**

**Comment by mikehardy** [comment]
if you uninstall and reinstall the app you get a new ID. It's not a hardware identifier it's an identifier of "this app installed on this device".
When you install the release build I'm guessing you uninstall the debug build
If I'm wrong and you can point to the area of code here where we are doing something wrong along with a reproduction based on the example, we may reopen
