### ISSUE TITLE
How to get all carriers of device with multiple sim

### ISSUE THREAD

**Issue by PurTahan** [react-native-device-info/react-native-device-info#1235]
I can get one Carrier with `DeviceInfo.getCarrier()`. But I need all Careers!

### How to get all carriers of device with multiple sim

**Comment by mikehardy** [comment]
Hi there!
You can get that by implementing a PR that uses the new APIs available on more recent Android operating systems like here 

- make sure the it is backwards-compatible by using Android version checks like this

https://github.com/react-native-device-info/react-native-device-info/blob/cab40497a09b5e7995709178315fba28287a598d/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L279

- call the API DeviceInfo.getCarriers() and document it to return an array of carriers
- have current DeviceInfo.getCarrier() just call in to getCarriers() but return `[0]` from it (or undefined)
- add it to the example app / tests (that's the best way to develop it anyway - get the example app running first, then use `yarn dev-sync` any time you make a change and re-run the app)

If you make the PR I'll happily collaborate with you to get it merged. Working on the code here is pretty easy in my opinion - so it should be achievable


current code is here

https://github.com/react-native-device-info/react-native-device-info/blob/cab40497a09b5e7995709178315fba28287a598d/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L339-L350


new APIs from Android are used like so https://stackoverflow.com/a/41984093/9910298

As this is not technically an issue with the module I'm going to close it however hopefully it's obvious by the effort I put into the research for you that I'll happily merge the feature if you implement it

Cheers!
