### ISSUE TITLE
Windows is reporting IsTablet incorrectly

### ISSUE THREAD

**Issue by namrog84** [react-native-device-info/react-native-device-info#1237]
Windows is reporting IsTablet incorrectly

## Summary

|             |     |
| ----------- | --- |
| Version     |  8.1.3 |
| Affected OS | Windows |
| OS Version  | Windows 10   |

It returns true when it should return false. And I'd imagine the opposote.

I will be doing a PR here soon to address this.

**Comment by mikehardy** [comment]
Thank you! Windows is not a use case for me and I'm the most active maintainer, so any help at all is appreciated!

**Comment by namrog84** [comment]
Hey no problem. I added the PR, with some potential food for thought and discussion regarding this.
Will continue further conversation over there on the PR itself.

**Comment by namrog84** [comment]
Sorry, definitely going to still finish this.  Just lots of other things have taken higher priority and haven't had a chance to circle back to this yet.

**Comment by mikehardy** [comment]
no worries, you are one of the more active PRs here actually, but I just implemented stale bot to purge out the rest of the cruft

**Comment by schie** [comment]
@mikehardy I'm stealing this stale bot GitHub action. That is all, carry on.
