### ISSUE TITLE
DeviceInfo.hasNotch() return false for device iPhone 12 Pro Max

### ISSUE THREAD

**Issue by i4apple** [react-native-device-info/react-native-device-info#1240]
Check:::: https://github.com/react-native-device-info/react-native-device-info/blob/65374808dc8aea1d6b989927a8f42c4732eaab60/deviceinfo.js

mentioned device name is not added in array inside Lib @ const devicesWithNotch = [], So, its return false, Please update.

**Comment by mikehardy** [comment]
Please post a PR and we can get a release out with the fix! Thanks
