### ISSUE TITLE
  TypeError: _reactNativeDeviceInfo.default.getVersion is not a function

### ISSUE THREAD

**Issue by MaganAnkur** [react-native-device-info/react-native-device-info#1250]
TypeError: _reactNativeDeviceInfo.default.getVersion is not a function

__mocks__

**Under react-native-device-info.js**
const mockedModule = jest.mock('react-native-device-info');

module.exports = mockedModule;

testfile.test.js
jest.mock('react-native-device-info', () => {
    return {
      getVersion: jest.fn()
    }
  })
![Screen Shot 2021-06-05 at 10 46 17 AM](https://user-images.githubusercontent.com/42070594/120895566-89834500-c5eb-11eb-8107-98ae37c5f53e.png)

**Comment by mikehardy** [comment]
If there is a problem with the mocks we distribute https://github.com/react-native-device-info/react-native-device-info/blob/master/jest/react-native-device-info-mock.js please post a minimal reproducible example (or better, a PR to fix it) and we can investigate it

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by MaganAnkur** [comment]
> If there is a problem with the mocks we distribute https://github.com/react-native-device-info/react-native-device-info/blob/master/jest/react-native-device-info-mock.js please post a minimal reproducible example (or better, a PR to fix it) and we can investigate it
> 
> https://stackoverflow.com/help/minimal-reproducible-example

@mikehardy  Thanks for swift response, it resolves the issue
