### ISSUE TITLE
getUniqueId gives same id on different devices

### ISSUE THREAD

**Issue by harsh-kukreja** [react-native-device-info/react-native-device-info#1262]
Hi there and thank you for reporting a bug! 🐛🐛🐛

## Summary
Hello, 
I am using getUniqueId as a usecase in my project to store the device id.
I got a report saying 2 of my customers have the same unique device ID on android
 can you please tell me another alternative for it? Or explain why this issue occur.
Both were using android phones i cannot get the details of which phone and Android version to reproduce.

**Comment by mikehardy** [comment]
Implemented like so, you're free to modify it to log more information or implement in some other way or provide more details
https://github.com/react-native-device-info/react-native-device-info/blob/0a5c21c9a544381577323e48e49cbbbe3bd8c946/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L776

With apologies, this isn't actionable on it's own though at all, so I'm going to close it

https://stackoverflow.com/help/minimal-reproducible-example
