### ISSUE TITLE
Jest Testing error

### ISSUE THREAD

**Issue by puneetkansal04** [react-native-device-info/react-native-device-info#1264]
_tests__/App-test.js
  ● Test suite failed to run

    TypeError: _reactNativeDeviceInfo.default.hasNotch is not a function

**Comment by mikehardy** [comment]
https://github.com/react-native-device-info/react-native-device-info/blob/master/jest.setup.ts

**Comment by puneetkansal04** [comment]
Hi @mikehardy did not get you. How can I resolve it. I replaced this file with new code. but not working.

**Comment by mikehardy** [comment]
You can clone the repo and see jest working. Something is wrong with your project and its configuration, not the module
