### ISSUE TITLE
Devices with notch - add new

### ISSUE THREAD

**Issue by yevhenlv** [react-native-device-info/react-native-device-info#1275]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.1.3   |
| Affected OS | android   |
| OS Version  | all   |

## Current behavior
Now DeviceInfo.hasNotch() return false

## Expected behavior

Please, add Xiaomi Redme Note 8 Pro to the devices with notch list.
Thank you)

**Comment by mikehardy** [comment]
The PR you need to post to implement the same is literally as fast as opening an issue :-). Open the code file here via github web UI, hit that edit button and propose the PR, I can integrate and release. Cheers
