### ISSUE TITLE
Getting warning with react native 0.65

### ISSUE THREAD

**Issue by shrenikTrukky** [react-native-device-info/react-native-device-info#1288]
I'm getting warning with react native new version 0.65
![Screenshot_1629435286](https://user-images.githubusercontent.com/15668512/130181259-8ada5601-2047-41e8-9cd4-cbe2ae345861.png)

**Comment by mikehardy** [comment]
Ah, thanks for posting this. I just investigated this pretty deeply for react-native-firebase https://github.com/invertase/react-native-firebase/issues/5614 / https://github.com/invertase/react-native-firebase/pull/5616 - should be easy to fix here.

Please note that as far as I can tell this has **no impact on your app**. Everything should be fine. So this is not urgent.

However! As a maintainer I really appreciate the notice and if you see it in any other modules I'm sure they'll appreciate it as well.

I'll investigate this here.

**Comment by mikehardy** [comment]
Called here:
https://github.com/react-native-device-info/react-native-device-info/blob/b57ddfb08dfb295abc8053c72306b713ba2ef21b/src/internal/asyncHookWrappers.ts#L29

According to the newly re-written react-native EventEmitter system, the native modules must implement addListener and removeListeners but they do not necessarily need to do anything. Simply implementing them is enough.
We do not have anything we need to do with them, so I can just add dummy implementations and that should be sufficient.

**Comment by mikehardy** [comment]
This is still present because it caused #1301 and was reverted in #1335
