### ISSUE TITLE
Is there a way to get the total RAM details of a device?

### ISSUE THREAD

**Issue by dion-george** [react-native-device-info/react-native-device-info#1294]
Doubt

Is there a method to get the RAM Storage of a device?
Currently, I can only see the option to get information related to disk storage. Curious to know if there's a way to get the RAM storage. 

Any updates on these [#178](https://github.com/react-native-device-info/react-native-device-info/issues/178), [#650](https://github.com/react-native-device-info/react-native-device-info/issues/650)

**Comment by schie** [comment]
Hi @dion-george ,

does `getTotalMemory` not return what you want?

**Comment by dion-george** [comment]
> Hi @dion-george ,
> 
> does `getTotalMemory` not return what you want?

Hey it does. my bad. Thanks a lot!
