### ISSUE TITLE
iOS device generates different unique id's from DeviceInfo.getUniqueId() for different apps on single device.

### ISSUE THREAD

**Issue by vaishnavtn** [react-native-device-info/react-native-device-info#1295]
iOS device generates different unique id's from DeviceInfo.getUniqueId() for different apps on single device. Where it's working fine for android and generates same unique id for multiple apps on same device.

## Summary

| OS Version  | 14 and above

## Current behavior

DeviceInfo.getUniqueId() - This method is generating different unique ID's for multiple apps on same device.

## Expected behavior

DeviceInfo.getUniqueId() - This method should generate same unique ID for multiple apps on same device.

**Comment by mikehardy** [comment]
The behavior you expect appears to be based on this statement:

> iOS: This is IDFV or a random string if IDFV is unavaliable

Are you sure IDFV is available? You will make progress on this issue by reaching into node_modules, directly manipulating the objective-c code to add logging statements (stackoverflow has examples if you're unfamiliar), then launching your app from Xcode on to a real device so you can see the console output. If you log all the arguments going in to the getUniqueId method, log results of any control flow branches, log arguments going into system APIs and the results from them, you'll have the problem isolated in a few minutes.

If there's something we're doing wrong please post a PR and we can merge and release it immediately

Cheers
