### ISSUE TITLE
A couple of questions about iOS uniqueIds

### ISSUE THREAD

**Issue by nicoburns** [react-native-device-info/react-native-device-info#1298]
Hi. Thanks again for this library. It's very useful having access to all of these values from one library. I have a couple of questions about the unique ids on iOS:

### Q1. When are IDFV's unavailable?

The README mentions that the `getUniqueId` falls back a random uuid on iOS when the IDFV is unavailable. But looking at the Apple docs I can't see any mention of it ever being unavailable. A best-effort persisted random uuid will probably work fine for my use case, but I was wondering when this occurs (IDFV unavailability).

### Q2. In what circumstances does one need to use the `syncUniqueId` function?

Naively reading the docs it looks like if I just want a unique(-ish) device id then I could call `getUniqueId` and it would "just work". However, in that case I can't see the purpose the of the `syncUniqueId` function at all. As it exists, I am assuming it is needed for something. So I wanted to check what it's used for in case it includes my use case without me realising.

Nico

**Comment by mikehardy** [comment]
Hi there - not really sure that was long before my time

just searching for IDFV in `git log` I get this 42fa516f1eadb734dfd1465e8b08580e6fad3e32 - maybe rooting around from there will help? It's from 2016!

Here's the syncUniqueId 34a1dd95e2bb87588402fbbb49d11585592e45b0 commit - might be useful?

**Comment by nicoburns** [comment]
Your comment inspired me to dive into the source code, where I found this:

```obj-c
+ (NSString *)appleIFV {
    if(NSClassFromString(@"UIDevice") && [UIDevice instancesRespondToSelector:@selector(identifierForVendor)]) {
        // only available in iOS >= 6.0
        return [[UIDevice currentDevice].identifierForVendor UUIDString];
    }
    return nil;
}
```
(https://github.com/react-native-device-info/react-native-device-info/blob/master/ios/RNDeviceInfo/DeviceUID.m#L161)

Looks like the case where it's not available is iOS version < 6. Which does actually line up with the Apple docs, I just didn't pay much attention because nobody is using iOS 6 these days.

**Comment by nicoburns** [comment]
Additionally, it looks like the `syncUniqueId` method is for putting either the IDFV or random UUID into the iOS keychain and NSUserDefaults. I think those storage methods are only used if `syncUniqueId` is called. A bit of googling suggests that the keychain used to survive uninstall/reinstall, which would have preserved the ID. However this no longer the case since iOS 10.3 unless a user has another app from the same developers installed. So I think this method is mostly useless at this point.

**Comment by mikehardy** [comment]
>  unless a user has another app from the same developers installed

I believe that *exact* case is why it exists though

**Comment by dusanristic** [comment]
Hey, I have one question regarding this.
@nicoburns said
>  bit of googling suggests that the keychain used to survive uninstall/reinstall, which would have preserved the ID

which is correct.
I have one question though. When I switch to a new phone and use the same Apple account, will the uniqueId stay the same or change? If the keychain (where the IDFV is stored) is somehow synced through the cloud on the new phone, I assume the IDFV for the specific app will stay the same. However, I am not certain whether syncing is done or not.
