### ISSUE TITLE
hasGms returns as false on Huawei devices which have GMS pre-installed

### ISSUE THREAD

**Issue by ws8149** [react-native-device-info/react-native-device-info#1300]
## Summary

|             |     |
| ----------- | --- |
| Device     | Huawei Mate 10 |
| Version     | 8.0.0   |
| Affected OS | Android   |
| OS Version  | 10 |

## Current behavior
hasGms returned as false

## Expected behavior
hasGms should return true for one of my user's Huawei device as it does have gms pre-installed.

## Additional notes
The user's device Play Store services version is 21.30.16

An investigation into this would be much appreciated!

**Comment by mikehardy** [comment]
Please dig into the code here:

https://github.com/react-native-device-info/react-native-device-info/blob/b7b3a668e2f7b62127a224015e58e77a023c1342/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L530-L541

Add some `System.err.println("something useful about which line exactly you are on, and the arguments to / return value from the API being exercised");` all over the place and re-test

If the test is failing for some reason there could be an incorrect assumption in the test but devices like yours (Huawei with google services these days? :thinking: ) so we need someone with the actual device to test on device and ideally repair the logic

**Comment by ws8149** [comment]
Hi, I currently do not have access to a Huawei phone with GMS pre-installed.

However, I do have a Huawei Nova 7 SE (Android 10). This device does not have GMS pre-installed. 

I have tried running the following code on Android Studio out of curiosity
`int avail_int = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(this);`

I have found that the value returned was, surprisingly, 9 aka SERVICE_INVALID. I would have expected it to be 1 aka SERVICE_MISSING. 

This leads me to suspect the issue might be on the isGooglePlayServicesAvailable() function itself.

I will update further on this issue if possible. I would like to try and get one of my users to run this function and see what gets returned. This may take a while though.

**Comment by mikehardy** [comment]
Anything you can do to get to the bottom of it is hugely appreciated! Never time pressure or any pressure, it's open source, so long as there is the mirror-image expectation that in the absence of you doing any work, nothing may happen :-) - in the general "you" sense, that is myself included. Cheers

**Comment by ws8149** [comment]
Here are my findings:

## Findings

- Ran the native `isGooglePlayServicesAvailable()` function on GMS pre-installed Huawei devices and it worked fine.
- Found that the problem can be reproduced on a Samsung S20. 
- react-native-device-info's hasGms() function works fine when the app runs from the command line eg: `react-native start`. However, when my app is built into an APK and installed from there. An error gets thrown.

## Error Details

- I found that the error thrown was
  `java.lang.NoSuchMethodException: com.google.android.gms.common.e.getInstance[]`
- However, this error does not get thrown when I run my app from the command line. 🤔

I have tried the following to resolve the issue but they did not work for me. Here's what I tried:
1. Performed "gradlew clean" command.
2. Deleted and reinstalled node_modules.
3. Updated react-native-device-info to the latest version.

**Comment by mikehardy** [comment]
Very interesting!!
Am I correct in assuming when you run from command line it is debug mode? Have you tried running it from command line in release mode?
Stated different: smells like a debug vs release build type issue
You can further test that hypotheses by setting proguard to true for debug mode as a temporary test: 

Put these two lines in the debug block and instead of referencing the "is proguard enabled" variable just put `true`
https://github.com/facebook/react-native/blob/4f0671b40953374d00ec5fe98d5442a13ffd5f41/template/android/app/build.gradle#L169-L170

And if that's the case then we may need a proguard rule that retains those classes, something like:

https://gist.github.com/jemshit/767ab25a9670eb0083bafa65f8d786bb#file-proguard-rules-pro-L216

But with the GooglePlayServicesAvailability symbol, not the Util symbol


we are including them via reflection and it may be that the R8 shrinker can't determine they need to be kept and so are discarded. I have a different project this might affect as well, I am very interested in any more experimental results here

**Comment by ws8149** [comment]
Thanks for the clue!

I have found that Proguard was causing this issue. 

Adding this into my Proguard configs solved the problem
`-keep class com.google.android.gms.common.** { *; }`

**Comment by mikehardy** [comment]
Excellent! We know the problem and have some direction on a solution now, thanks for testing that and confirming.
May I ask a favor? Can you post instructions on exactly what you did as a PR to the README for the documentation on that specific API? I want to leave this issue open as well, we need to figure something out to add proguard rules, it's actually a bit fiddly for react-native modules

Thanks!

**Comment by mikehardy** [comment]
> I want to leave this issue open as well, we need to figure something out to add proguard rules, it's actually a bit fiddly for react-native modules

**Comment by mikehardy** [comment]
Ideally a solution that did not result in all users having to include a proguard definition manually would be ideal.
I know it's possible to specify proguard rules for libraries via a build.gradle declaration in the library but I'm not sure if that is possible for gradle sub-projects or however react-native native modules are wired in to gradle for final app assembly
