### ISSUE TITLE
hasHms() doesn't work properly

### ISSUE THREAD

**Issue by yaroslavnikiforov** [react-native-device-info/react-native-device-info#1305]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.3.1  |
| Affected OS | Android  |
| OS Version  | 10   |

## Current behavior

I am testing `hasHms` method on HUAWEI MatePad T (AGS3-W09) and it returns false. But I have HMS Core and don't have Google mobile services. `hasGms` also returns false, as expected.

## Expected behavior

`hasHms()` should return true

**Comment by mikehardy** [comment]
I think this may be the same root cause as #1300 - please examine that one for the pointer to proguard rules and try it out. End result of that was a note in the documentation (#1302 ) with issue left open pending the addition of an actual proguard rules file we may direct people to include in their build.gradle

**Comment by yaroslavnikiforov** [comment]
I tried to enable proguard and added this rule: `-keep class com.google.android.gms.common.** {*;}` but `hasHms()` still returns false on Huawei device with HMS.

**Comment by mikehardy** [comment]
@yaroslavnikiforov I do not believe adding the **android GMS** classes will help you detect **huawei HMS**, no? What are the classes for HMS? 

Can you try with the HMS classes?

https://github.com/react-native-device-info/react-native-device-info/blob/b937e53bad1b5c358aaa9aee4d3e52dd33e11c01/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L548

**Comment by yaroslavnikiforov** [comment]
Alright, I added such rule in proguard-rules.pro: `-keep class com.huawei.hms.api.** {  *;  }` (also tried: `-keep class com.huawei.hms.api.HuaweiApiAvailability {  *;  }` and did changes to enable proguard:

<img width="669" alt="Screenshot 2021-09-22 at 12 36 49" src="https://user-images.githubusercontent.com/42115630/134320237-96c58343-6c13-45f6-b1f3-893d26fe1696.png">

But hasHms() doesn't work (returns false). Tested with release build.

**Comment by mikehardy** [comment]
Most unexpected. Perhaps the classes changed. I don't have a Huawei device, so apart from the general direction I've given with regard to how to tweak Proguard class retention (to make sure classes are still there in release even if only used via reflection) I won't be able to offer more.

If there's a PR needed to repair it, you'll have to post that, then we can release and merge. That it works in debug is very suspicious to me though - that makes me think there is still something going on with proguard and how it's configured in your project

**Comment by NoahSimajji** [comment]
I am facing the same issue. Any solution for it?
