### ISSUE TITLE
 isTablet() is false for Lenovo tablet  TB-8505X 

### ISSUE THREAD

**Issue by akunal1** [react-native-device-info/react-native-device-info#1308]
**Info:**
Device type : Tablet
OS : Android
model : Lenovo tablet  TB-8505X 

**Issue** 
`const isTablet = DeviceInfo.isTablet(); // returns false`

excepted : true

**Comment by mikehardy** [comment]
I believe the isTablet check is just using a heuristic based on screensize. Is this tablet so small that it appears like a phone? Have you inspected the code @akunal1 to see how this module operates and examined why it would return false?

**Comment by akunal1** [comment]
> I believe the isTablet check is just using a heuristic based on screensize. Is this tablet so small that it appears like a phone? Have you inspected the code @akunal1 to see how this module operates and examined why it would return false?

I have not checked the code yet but the tablet size is really confusing . size is little large from mobile and small from Tablet. 
I think screen size is confusing the library.

<html>
<body>


Size | 8.0 inches, 185.6 cm2 (~76.5% screen-to-body ratio)
-- | --
Resolution | 800 x 1280 pixels, 16:10 ratio (~189 ppi density)


</body>
</html>

**Comment by akunal1** [comment]
thanks, looks like I have to write a wrapper as per my requirements.
