### ISSUE TITLE
Get phone numbers with dual sim phones

### ISSUE THREAD

**Issue by aminebelmahi** [react-native-device-info/react-native-device-info#1315]
## Summary

|             |     |
| ----------- | --- |
| Version     |  8.3.3  |
| Affected OS |  Android  |
| OS Version  |  Android 9 / 10  |

## Current behavior

Currently getPhoneNumber() function only return the phone number in the first SIM, but not in the second one in the case of a Dual Sim Mobile, is there a workaround for this to work or the API only support one SIM?

## Expected behavior

Getting both SIM cards phone number in case of Dual Sim mobile

**Comment by mikehardy** [comment]
There is no current functionality like this, it has never been implemented as the module existed before Android itself had APIs to return multiple phone numbers. I know it has the APIs now though, if you proposed a PR that still worked with the current minSdkVersion (read as: had Android API checks before touching symbols that might not exist on prior versions) and returned phone numbers as an array, we could collaborate to get it merged

**Comment by ashutosh-badho** [comment]
Hi is this implemented? or any  work around? I am looking for solution.

**Comment by mikehardy** [comment]
@ashutosh-badho "I checked the code and I saw..." + "I read through this thread and concluded..."

When you do either you will have the answer. What is the answer you come to when you put in that effort?
