### ISSUE TITLE
Getting a different ID with getUniqueId()

### ISSUE THREAD

**Issue by Soltvalley-work** [react-native-device-info/react-native-device-info#1317]
This is not a bug, but was raised for confirmation like #1316.

In ver. 7.2.0 or later, when uninstalling and reinstalling, the IDs obtained by getUniqueId() were different.
In ver. 7.1.0 or earlier, when uninstalling and reinstalling, the IDs obtained by getUniqueId() are the same.

According to the readme, the behavior before ver. 7.1.0 should be the correct one. If the behavior in ver. 7.2.0 or later is correct, the readme description should be modified accordingly.

> iOS: This is IDFV or a random string if IDFV is unavaliable. Once UID is generated it is stored in iOS Keychain and NSUserDefaults. So it would stay the same even if you delete the app or reset IDFV. You can carefully consider it a persistent, cross-install unique ID. It can be changed only in case someone manually override values in Keychain/NSUserDefaults or if Apple would change Keychain and NSUserDefaults implementations. Beware: The IDFV is calculated using your bundle identifier and thus will be different in app extensions.

**Comment by mikehardy** [comment]
If there is a documentation change needed, I merge PRs quickly

You don't specify if you have allowed IDFV or not, so I'm not sure how that would affect any contemplated documentation change

Related, I'm curious how the syncUniqueId method affects this case across uninstalls, and that may affect any contemplated documentation change

I'm also curious if you've traced the iOS code to see whether it is trying to save in the keychain or not?

All that said - after reviewing the original item here #1119 it appears that perhaps the change was made in a way that is not developer friendly in practice.

Stated differently: now that the keychain is maybe not accessible, but apps may start (and try to store or access the id) prior to first unlock perhaps the iOS logic (and related documentation) should be changed to accommodate this. It could explicitly expose the issue to developers by returning undefined in that case, until it was defined, and I'm not sure if there is an unlock listener you can do on iOS but if there was, we could try to run when unlock happens so we can sync up the id with the stored preference

I'm open to reasonable PRs on all of this stuff, but it's not an important use case for me personally, so other than trying to be a good collaborator this must come from someone else doing the work

**Comment by marcorm** [comment]
> Should be true especially after the fix 11days ago. what is your experience testing the current version? No feedback so far

Hi @mikehardy , sorry for the late feedback. We had problems with previous issues. Now everything works as expected.
Thanks a lot for what you do in the community!
