### ISSUE TITLE
getSerial is not accessible even if permissions are available 

### ISSUE THREAD

**Issue by freeboub** [react-native-device-info/react-native-device-info#1320]
## Summary

| | |
| --  | -- |
| Version     | v8.3.3  |
| Affected OS | Android  |
| OS Version  | API > 26   |

## Current behavior

Access to serial number on android doesn't work even if android.permission.READ_PRIVILEGED_PHONE_STATE is granted.
(no error displayed)
getSerial return "unknown"

## Expected behavior

Serial number should be retrieved

## Link to documentation

https://developer.android.com/reference/android/os/Build#getSerial()
`
If the calling app has been granted the READ_PRIVILEGED_PHONE_STATE permission; this is a privileged permission that can only be granted to apps preloaded on the device.`
That means it can be tested only with an app preloaded in android system image

**Comment by freeboub** [comment]
I will open a pull request to fix the issue in few days!

**Comment by mikehardy** [comment]
Interesting - it looks like this needs an extra API branch for API 29, then inside that, 4 different tests - but...that is ugly.

Perhaps the whole API check and permission check may be removed, the docs can just point to the link you just linked (with a stern message saying: "You must read the documentation to understand the limited conditions when this will ever return anything but `unknown`" or similar)

And then just make the call with a catch for SecurityException and return "unknown" in the catch.

Seems clean and easy?

**Comment by mikehardy** [comment]
I just had something similar with #1343 and now that I re-read my comment here I really should have just removed all the API checks around my PR as well, and just done try { /* api call that can throw SecurityException */ } catch (SecurityException e) { return "unknown"; } for my PR as well. It's an easy PR I just don't have any way to test if it's working well since this is not a type of access any of my projects have. PRs welcome

**Comment by freeboub** [comment]
Few days were long :)

Thank you for the reminder !
I just remove all tests to keep only the last catch used, I think it is enough.
Thank you
