### ISSUE TITLE
Problem with getUniqueId() on iOS

### ISSUE THREAD

**Issue by xKRUTOIx** [react-native-device-info/react-native-device-info#1322]
## Summary

I have been using version `^4.0.1` for a few months and then decided to update it to the latest one(`^8.3.3`). I use function `getUniqueId` to uniquely identify users but `getUniqueId` from version `4.0.1` and `getUniqueId` from version `8.3.3` give me different ids and basically all my users will lost their accounts.

|             |     |
| ----------- | --- |
| Version     | 8.3.3   |
| Affected OS | iOS  |
| OS Version  | 14.5  |

## Current behavior

`getUniqueId` returns differnt id on the latest version compare to `4.0.1`

## Expected behavior

`getUniqueId` should returns the same uid for the same device in the latest version as well

__________________________________________

How can I achieve it?

**Comment by mikehardy** [comment]
Please search the issues list prior to logging duplicates #1317
