### ISSUE TITLE
Crashes on iOS with react-native 0.66

### ISSUE THREAD

**Issue by trcoffman** [react-native-device-info/react-native-device-info#1326]
## Summary

In the process of updating our app to RN 0.66, I started experiencing crashes in react-native-device-info.

|             |     |
| ----------- | --- |
| Version     | 8.4.0   |
| Affected OS | iOS   |
| OS Version  | 14.8   |

## Current behavior

A fatal error keeps the app from functioning
```
2021-10-11 09:17:10.354775-0700 Debug Property[10038:3409364] [javascript] Error: Exception in HostObject::get: for prop 'RNDeviceInfo': <unknown exception>, js engine: hermes
2021-10-11 09:17:10.362923-0700 Debug Property[10038:3409364] [javascript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

## Expected behavior

The app shouldn't crash.

**Comment by trcoffman** [comment]
I have discovered that the problem was that we were still using the legacy xcode buildsystem. After moving to the modern build system the app no longer crashes.

**Comment by Shevchenko-Oleksii** [comment]
In addition to that, i've discovered that having empty version string causes same crash as well. 
cc https://issueexplorer.com/issue/react-native-device-info/react-native-device-info/1239#1375724

**Comment by mikehardy** [comment]
@Shevchenko-Oleksii if you've got a stack trace of a crash and it's root cause, you could post a quick PR to more safely access whatever system information we're trying to fetch, posting the stack in the PR for review...
