### ISSUE TITLE
[Windows] isKeyboardConnected always returns true

### ISSUE THREAD

**Issue by creambyemute** [react-native-device-info/react-native-device-info#1327]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.4.0   |
| Affected OS | Windows  |
| OS Version  | Latest Win10   |

## Current behavior

When calling `isKeyboardConnected()` or `isKeyboardConnectedSync()` it always returns true.

* Tested on a desktop without keyboard
* Tested on surface pro 7 without hardware keyboard

## Expected behavior

Return true or false depending on whether a keyboard is connected or not?

It seems this behaviour is not a bug in this library itself. When doing trying the same in a console application it also always returns true. The Windows API KeyboardPresent does not seem to work at all?

@namrog84 Do you maybe have an idea?

**Comment by mikehardy** [comment]
If it's a useful signal (even if unreliable) I'm fine with it staying in, just with a note about it's limitations and an admonition to devs that if they use it to change their interface they should also provide the user a way to either temporarily or disable whatever the interface change was, in case it was an incorrect detection
