### ISSUE TITLE
[iOS + React Native Config] Exception in HostObject::get: for prop 'RNDeviceInfo'

### ISSUE THREAD

**Issue by gbettinazzi** [react-native-device-info/react-native-device-info#1334]
## Summary
```
"react-native-config": "1.4.4"
"react": "17.0.2"
"react-native": "0.66.0"
"react-native-device-info": "^8.4.3"
```

## Current behavior
Hi! I'm experiencing this issue using react-native-device-info in combination with react-native config.
`Exception in HostObject::get: for prop 'RNDeviceInfo'`.
I did some research and from this [previous issue](https://github.com/react-native-device-info/react-native-device-info/issues/1239) it might be caused by a mismatch between Info.plist variables and the project.pbxproj variables
With react-native-config I'm using the configuration variable $(IOS_VERSION) to be indicate the current application version, while in the project.pbxproj I had $(MARKETING_VERSION). 

## What I've tried so far
I've replaced the MARKETING_VERSION occurrences in project.pbxproj with IOS_VERSION and the app starts to compile again.
Unfortunately the app is no longer getting the correct version and build version from my .env variables. So this workaround is working but is not ideal in the long run.

I know it's not strictly an issue with your library (which I love) but rather a combination with react-native-config, it looks like RNDeviceInfo is trying to read some variables without finding them, can you please explain to me if my previous assumption is correct and what variables are required from RNDeviceInfo? 

## Expected behavior
The app should run in debug with no problems, getting the correct iOS version and build version from .env variables.

**Comment by schie** [comment]
Hi @gbettinazzi,

Do you have a simple example app that can reproduce the issue?

Unfortunately, while `react-native-config` seems cool, I've never personally used it, so a bootstrap would help. 

With that being said, if you've identified the issue, PRs are welcome!
