### ISSUE TITLE
获取设备唯一不变的id

### ISSUE THREAD

**Issue by sendsnow** [react-native-device-info/react-native-device-info#1342]
## Summary

|             |     |
| ----------- | --- |
| Version     | 2.2.2  |
| Affected OS | ?   |
| OS Version  | ?   |

## Current behavior

The device ID obtained by using deviceinfo.getdeviceid changes after the device is reset, app is uninstalled and reinstalled. It is not unique and fixed
## Expected behavior

Which method can you use to obtain the unique ID of the device that will not change, and as the unique identification between devices, can DeviceInfo. Getuniqueid() obtain the unique ID of the device that will not change

**Comment by mikehardy** [comment]
V2 is too old to pay any attention to.
Can you please run this through an English translator?
Please check the issue list for getMacAddress, this is likely a duplicate

**Comment by mikehardy** [comment]
Note ID vs Id
