### ISSUE TITLE
fix: useBatteryIsLow fires on initial render with current battery level

### ISSUE THREAD

**Issue by lisabaut** [react-native-device-info/react-native-device-info#1346]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.4.4   |
| Affected OS | iOS / Android   |
| OS Version  | ?   |

## Current behavior

When using the hook `useBatteryIsLow` it returns the current battery level on initial rendering- no matter if the battery level is currently low or not according to the defined percents (=> see [docs](https://github.com/react-native-device-info/react-native-device-info#usebatterylevelislow-or-rndeviceinfo_batterylevelislow)).

This is due to these lines here: https://github.com/react-native-device-info/react-native-device-info/blob/master/src/index.ts#L716-L719

**Please note:**
When running the `example` App on an emulator/simulator one can not detect this bug. 
You need to run the `example` App on a real device with an actual battery to see that `batteryIsLow` is rendered with the current battery level on initial rendering.

## Expected behavior

The hook `useBatteryIsLow` returns the battery level as a number in percent if the current battery level is currently low.
If the battery level is not low the hook returns `null`.

## Solution

I assume simply removing [the lines](https://github.com/react-native-device-info/react-native-device-info/blob/master/src/index.ts#L716-L719) would fix the issue. What do you think?

**Comment by mikehardy** [comment]
Interesting - I'll admit I'm not so great at hooks, and further I didn't write that one :-), if we remove the lines completely, won't that miss the case where it should fire when the battery actually is low, vs waiting for a battery level change event to trigger evaluation vs the low battery thresholds ?
