### ISSUE TITLE
Not working in release build (RNW 0.65)

### ISSUE THREAD

**Issue by Omar-Belghaouti** [react-native-device-info/react-native-device-info#1349]
## Summary

I can get the device info in debug mode, and it  works fine. But when I try to build the app in release mode nothing happen, I can't get any info. And this is only happening in Windows platform ( react-native-windows 0.65.7 ).

|             |     |
| ----------- | --- |
| Version    | 8.3.3   |
| Affected OS | Windows 11  |
| OS Version  |  21H2 |

## Current behavior

Cannot get the device info in release build.

## Expected behavior

Get the device info in release build.

**Comment by mikehardy** [comment]
I'm happy you resolved this! Please note react-native-windows does not have a huge user community yet so *any* thing you learned and can share on why this happened and what the cause was could be helpful to future react-native-windows folks, if you can drop a comment on what it was

Specifically as a maintainer here react-native-windows is new to me, so I'm open to learning anything, no matter how simple or hard. Cheers

**Comment by Omar-Belghaouti** [comment]
@mikehardy thanks for your comment, it was nothing big really. However I'd like to point to some point, the uid is not unique in each build and it always starts with `{` and ends with `}` only in Windows platform, so I took the liberty to use `.replaceAll("{", "")` and the problem was using it because it is an es7 method, so I used the `.replace("{", "")` method and it worked just fine, so after all this I would like to know why the uid is different in each build?

**Comment by mikehardy** [comment]
Not sure 😅 but willing to reopen fir triage in case anyone does know

**Comment by schie** [comment]
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpfr/ac10a1cc-128a-4942-a120-363f74e1953d

Here's some documentation on it.

**Comment by mikehardy** [comment]
bonus points for the link which in such a meta way contains a GUID (but not a curly-string GUID!)

**Comment by SruthyJohn** [comment]
Still searching for solution for this problem.

**Comment by mikehardy** [comment]
@SruthyJohn something is wrong then, I've run the windows version of the app pretty recently, it works fine
I suggest you make a clean reproduction (https://stackoverflow.com/help/minimal-reproducible-example) then open a new issue with all details necessary to reproduce + show what you've researched + describe the problem fully (https://stackoverflow.com/help/how-to-ask)
