### ISSUE TITLE
Airplane Mode listener

### ISSUE THREAD

**Issue by harsh-kukreja** [react-native-device-info/react-native-device-info#1352]
Hello, I am trying to add a listener in DeivceInfo Airplane Mode?
Is there any way where I can check if Airplane Mode is enabled or disabled continuously as an event?

**Comment by mikehardy** [comment]
airplane mode is more of a device switch than a network item, as it turns off all radios (bluetooth too). Not sure there is a listener, but there is airplane mode *detection* in the device-info package I maintain https://github.com/react-native-device-info/react-native-device-info/#isairplanemode

You could PR there to add listeners for it native, and wrap it in a hook, I'd merge that. There is prior art you may use as a pattern for the other listener/hook additions.

Adding it here would be an overlap of module API surface area I think, so if you would like to do that, please focus effort in the repo linked above, I'll close this as out of scope here
