### ISSUE TITLE
iPhone 13 not detected

### ISSUE THREAD

**Issue by xlcrr** [react-native-device-info/react-native-device-info#1353]
Upgraded to latest version currently `^8.4.3` to detect the iPhone 13 series

When I log `DeviceInfo.getModel()` I get `iPhone` using any iPhone 13 in the simulator. All older models are working as expected.

I am using swift v4 and ran pod clean/install, npm install.

Its working fine for another developer on our team.

Can anyone suggest why its not working for me?

**Comment by mikehardy** [comment]
If it's working for another developer, then it's not a bug here. My best suggestion is `npx react-native-clean-project` - it's quite thorough. If you can reproduce with your other teammate and assert that it is still not working then we may reopen but I see 13 in the simulator as well, so I do not reproduce either

**Comment by xlcrr** [comment]
Didn't know about that command, thanks for the help and fast reply! Will post the fix when I find it
