### ISSUE TITLE
DeviceId returns the board instead of the device Id

### ISSUE THREAD

**Issue by Nesh108** [react-native-device-info/react-native-device-info#1355]
Hello,

I am a bit confused at why this line: https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L193

doesn't use `Build.DEVICE` instead.

On my side, changing that returns the expected values for android (the ones from this list: https://storage.googleapis.com/play_public/supported_devices.html )

**Comment by mikehardy** [comment]
https://github.com/react-native-device-info/react-native-device-info/blob/1a10a875c840bbe1ea0cb00fed592974d32d5f32/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L733-L736

Different API has the Build.DEVICE key - been that way forever, so not likely to change now, but the info you want is available
