### ISSUE TITLE
Is react-native-device-info available in expo?

### ISSUE THREAD

**Issue by urinipni** [react-native-device-info/react-native-device-info#1357]
<img width="458" alt="ScreenShot 2021-12-28 오후 5 25 54" src="https://user-images.githubusercontent.com/60772837/147545680-054313d3-0202-4eef-a1d9-3f261efc0d79.png">

I had to use `getFontScale()` method in expo.

So I installed the package with `npm i react-native-device-info`, and wrote a simple code.

```
DeviceInfo.getFontScale().then((fontScale) => {
  console.log(fontScale)
});
```

And I received an error.

I'm suspecting that `react-native-device-info` doesn't work in expo. Does anyone know this package is available in expo? And if so, how to fix this error?

**Comment by mikehardy** [comment]
if in expo ecosystem, use their device info module. You are correct this one will not work
