### ISSUE TITLE
DeviceInfo.getSystemName() returns `ipados` instead of `ios`

### ISSUE THREAD

**Issue by lukebars** [react-native-device-info/react-native-device-info#1358]
## Summary

|             |     |
| ----------- | --- |
| Version     |  8.4.5  |
| Affected OS | iOS 15.2 (iPadOS 15.2)  |
| OS Version  |  iOS 15.2 (iPadOS 15.2)  |

## Current behavior

Looks like since some changes in Apple's ecosystem, currently iPads with latest OS do return `ipados` instead of `ios` when getting system name with `DeviceInfo.getSystemName()`. 

This might not be a bug from library side, but I'm raising this issue for consideration and for all the folks that are using this library that could run into issues because of this.

## Expected behavior

At least back in the day `DeviceInfo.getSystemName()` was returning `ios` on iPads.

**Comment by mikehardy** [comment]
Interesting - not sure what we can do about that
I guess the appropriate response is an update to the readme here if you hit the edit button and add ipados as a possible return: https://github.com/react-native-device-info/react-native-device-info#getsystemname - would be great to know when that started happening (that is, with which version of ipados, and/or if it relied on you compiling specifically for ipados or ?? )

**Comment by lukebars** [comment]
Ah yes, sure. I'll do a round of research tomorrow on which iPadOS release this behavior appeared and will submit a PR.

**Comment by lukebars** [comment]
This behavior was introduced in iPadOS 15.0.

I've raised a PR that addresses that in the readme.

Closing this as everything is sorted out.
