### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument when testing with Jest

### ISSUE THREAD

**Issue by guiccbr** [react-native-device-info/react-native-device-info#1360]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.4.8   |
| Affected OS | N/A Jest   |
| OS Version  | N/A   |

## Current behavior

I just upgraded from react-native 0.66.1 to react-native 0.66.4 and when I tried to run my test suite with jest, many of the tests are failing with:

```
 ● Test suite failed to run

    Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

      at invariant (../../../node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (../../../node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:44:30)
      at Object.<anonymous> (../../../node_modules/react-native-device-info/lib/commonjs/internal/asyncHookWrappers.ts:29:34)
      at Object.<anonymous> (../../../node_modules/react-native-device-info/lib/commonjs/index.ts:3:1)
```

## Expected behavior

I'd expect the tests to work as they were working before.

Trying to find a solution/workaround in many other places but nothing that I've tried has fixed it.

I have the following lines on my test.setup.js (that was working fine before the upgrade):

```
import mockRNDeviceInfo from 'react-native-device-info/jest/react-native-device-info-mock';
jest.mock('react-native-device-info', () => mockRNDeviceInfo);
```

**Comment by mikehardy** [comment]
Looks common
https://search.brave.com/search?q=Invariant+Violation%3A+new+NativeEventEmitter()+requires+a+non-null+argument+when+testing+with+Jest&source=desktop

What have you tried?

Anything like https://github.com/react-native-device-info/react-native-device-info/blob/808c1b5f8021905e93cb03e011a17ffe475c134a/jest.setup.ts#L146-L149

**Comment by guiccbr** [comment]
Hi, Mike. Thank you. I did try that, but it had no effect.

After some more investigation I noticed that my `test.setup.js` was importing a module that depended on react-native-device-info, but the import was *before* the jest.mock lines. By making sure that the mock was in place before that import, things started to work again.

Thank you!

**Comment by mikehardy** [comment]
Excellent! glad to hear you got it working. Jest mocking is subtle stuff for sure

**Comment by ramirobg94** [comment]
Hi, sorry for open again this thread but...  after open many github issues links and try many things the problem persist on our side. 

```
src/state/form/sagas/_tests/clusterPlotTree.test.js
  ● Test suite failed to run

    Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

      at invariant (node_modules/invariant/invariant.js:40:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:44:16)
      at Object.<anonymous> (node_modules/react-native-device-info/lib/commonjs/internal/asyncHookWrappers.ts:29:34)
      at Object.<anonymous> (node_modules/react-native-device-info/lib/commonjs/index.ts:3:1)
```

and

jest.setup.js

```
import mockRNDeviceInfo from 'react-native-device-info/jest/react-native-device-info-mock';

jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter');

jest.mock('react-native-device-info', () => mockRNDeviceInfo);
````

Any idea about what is the reason?

Thanks

**Comment by Adnan-Bacic** [comment]
> Hi, sorry for open again this thread but... after open many github issues links and try many things the problem persist on our side.
> 
> ```
> src/state/form/sagas/_tests/clusterPlotTree.test.js
>   ● Test suite failed to run
> 
>     Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
> 
>       at invariant (node_modules/invariant/invariant.js:40:15)
>       at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:44:16)
>       at Object.<anonymous> (node_modules/react-native-device-info/lib/commonjs/internal/asyncHookWrappers.ts:29:34)
>       at Object.<anonymous> (node_modules/react-native-device-info/lib/commonjs/index.ts:3:1)
> ```
> 
> and
> 
> jest.setup.js
> 
> ```
> import mockRNDeviceInfo from 'react-native-device-info/jest/react-native-device-info-mock';
> 
> jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter');
> 
> jest.mock('react-native-device-info', () => mockRNDeviceInfo);
> ```
> 
> Any idea about what is the reason?
> 
> Thanks
> 
> Im trying to use a function into a saga (Redux-sagas)

you have to run jest.mock() on the react-native emitter, as shown here: https://github.com/ocetnik/react-native-background-timer/issues/367#issuecomment-953662440
`jest.mock('react-native/Libraries/EventEmitter/NativeEventEmitter');`
