### ISSUE TITLE
How to get the Processor name in an android phone?(QUESTION)

### ISSUE THREAD

**Issue by ThiruRJST** [react-native-device-info/react-native-device-info#1367]
This is actually a question. Is there any method to get the processor name of a phone.
The output must be like: Snapdragon 888, Mediatek Helio like this.

**Comment by mikehardy** [comment]
@ThiruRJST I don't know. Not in the current version of the module here at least. What did you find when you investigated the available APIs from the Android developer site? Please do the research and post a PR if it is possible and you want the feature
