### ISSUE TITLE
Add Huawei P40 Lite to devicesWithNotch?

### ISSUE THREAD

**Issue by rafaelmaeuer** [react-native-device-info/react-native-device-info#1376]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.4.8   |
| Affected OS | Android   |
| OS Version  | SDK31   |

## Current behavior

`Huawei P40 Lite` currently is not listed in `devicesWithNotch` but has a cutout on the front display:

![proxy-image-1](https://user-images.githubusercontent.com/6418459/152201595-750a9fba-aec2-4e4d-94a4-859b7b9ce355.jpg)

## Expected behavior

`Huawei P40 Lite` should be added in `devicesWithNotch` like `P20 Lite` and `P30 Lite` already are.

**Comment by mikehardy** [comment]
Hi there! Post a PR that  you confirm works for you locally and we can merge it and release
