### ISSUE TITLE
Camera view angle type

### ISSUE THREAD

**Issue by charity-detalytics** [react-native-device-info/react-native-device-info#1382]
How to know which camera view type does device have?
For example: wide angle camera, ultra-wide angle camera, ...

**Comment by mikehardy** [comment]
Hi there! No idea - the module does not currently provide that info.
You are in luck though, there is a wonderful library that already implements exposure of the info I believe you are looking for, and is a natural home for extra information if there should be more: https://mrousavy.com/react-native-vision-camera/docs/api/interfaces/CameraDevice
