### ISSUE TITLE
getIpAddress() shouldn't be deprecated

### ISSUE THREAD

**Issue by thnszgns** [react-native-device-info/react-native-device-info#1387]
## Description

getIpAddress() is working without any issues in react-native-windows while solutions you suggest like react-native-netinfo/netinfo or react-native-network-info don't work for windows Platform

**Comment by mikehardy** [comment]
@thnszgns I maintain both this repo and react-native-netinfo/netinfo

What exactly is the problem with the windows port of netinfo? Last I checked, it works.

https://github.com/react-native-netinfo/react-native-netinfo/tree/master/windows

**Comment by thnszgns** [comment]
I can't get IP information from NetInfo

NetInfo.fetch().then(state => {
      console.log("IP", state.ipAddress); //undefined
      console.log("Is connected?", state.isConnected); //works
    });

**Comment by mikehardy** [comment]
netinfo will have a release in a moment with ipAddress, please test and report issues on related PR
