### ISSUE TITLE
Can't get mac address on ios

### ISSUE THREAD

**Issue by hungth84** [react-native-device-info/react-native-device-info#1391]
I want to ask why using **DeviceInfo.getMacAddress()** on ios always results in: 02:00:00:00..... I want to get the Mac Address of IOS, how can I do that?

`DeviceInfo.getMacAddress().then((mac)=>{ alert(mac)})`

**Comment by mikehardy** [comment]
Please read documentation before posting issues, this is addressed https://github.com/react-native-device-info/react-native-device-info#getmacaddress
