### ISSUE TITLE
Check Device Volume

### ISSUE THREAD

**Issue by theneekz** [react-native-device-info/react-native-device-info#1393]
## Description

This is a robust package that is already extremely versatile. I wonder if others would also like for it to include the following functionality to prevent adding yet another package to handle the phones volume settings.

Ideally:
- get volume
- add/remove volume listener
- check if phone is in silent mode

Nice to have:
- set phone to silent mode
- set volume

One package that already claims to support this is [react-native-system-setting](https://github.com/c19354837/react-native-system-setting) 

## Use Case

If an app has features with sounds but the users volume is off, you could then warn them that they might not hear the app's features.

**Comment by mikehardy** [comment]
That package you linked looks like it is doing a good job of it, I wouldn't want to include the functionality here unless there was some coordination with the maintainer there to actually move it here and help support. Adding new code is not easy, supporting it forever is hard. it needs maintainer-power, not code, in other words. And it looks like it has maintainer-power already, over there

If you can coordinate a merge of features, I'm open to that but I don't have time to pursue it at the moment personally

**Comment by liho00** [comment]
+1 for this feature, with check device's silent or mute state of the setting.

**Comment by mikehardy** [comment]
It seems like you haven't addressed my comment. A reopen doesn't seem to make sense. But I never close comments unless people are behaving badly, so they are open for collaboration, sure.

**Comment by JoniVR** [comment]
@mikehardy I see your argument for the other package already doing this, and that's a fair point. It might hurt the smaller library and it does do the job currently.

On the other hand, I'd love to not have to use a different dependency for everything, I think we can both agree that react native apps typically already have way too many dependencies. 

Imagine if I had to pull in a package for every single system sensor or setting that this package provided 😅 

Whatever you do decide is your decision obviously as maintainer, I just wanted to offer a different perspective.

**Comment by mikehardy** [comment]
I hear you but that still doesn't move it forward, I don't actually have to do anything, it's up to a motivated person to coordinate a merge if they want, through diplomacy with the other package and a commitment for maintenance

Open source isn't free code, it's a free puppy 😅, this needs effort, not words in comment boxes. This isn't a use case of mine so I have no personal interest and won't invest in it.  I'm not obstructive or anything though, I would be happy to collaborate and we always need more maintainers, happy to share out authority in the repo

**Comment by JoniVR** [comment]
Thanks for the update.

> Open source isn't free code, it's a free puppy 😅, this needs effort, not words in comment boxes. This isn't a use case of mine so I have no personal interest and won't invest in it. I'm not obstructive or anything though, I would be happy to collaborate and we always need more maintainers, happy to share out authority in the repo

I want to add that I was in no way implying that you'd have to be the one to implement or maintain this by yourself. I understand open source (and the work that comes with it) very well. My personal need for this feature is not high enough, but a maintainer can decide if a feature will be added when people submit a PR or not, this was my point I was trying to make, to at least consider it if someone was willing to put up the work for it (and effectively maintain it).
