### ISSUE TITLE
exported key value in Android Manifest file

### ISSUE THREAD

**Issue by gkasireddy202** [react-native-device-info/react-native-device-info#1396]
Can i set exported value from true to false in Android manifest file?
Is there any chance to crash the app or app is not running when i set exported value from true to false.

**Comment by mikehardy** [comment]
Hi there - please point me to the location in this module where we are setting exported:true - I don't see one.
If we have one that you can point to, we can examine and discuss

https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/AndroidManifest.xml

**Comment by gkasireddy202** [comment]
Can I set exported is false in the below folder path.?
node_modules>react-native-device-info>android>src>main>AndroidManifest.xml.

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.learnium.RNDeviceInfo">

  <application>
    <receiver android:name="com.learnium.RNDeviceInfo.RNDeviceReceiver"
        android:enabled="true"
        android:exported="false"
        tools:ignore="ExportedReceiver"
       
        >
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
      </intent-filter>
    </receiver>
  </application>

</manifest>

**Comment by mikehardy** [comment]
@gkasireddy202 you need to just update your version. That feature literally no longer exists. You can see that in my link.

**Comment by gkasireddy202** [comment]
Thanks @mikehardy.
