### ISSUE TITLE
DeviceInfo.getPhoneNumber()  returning unknown 

### ISSUE THREAD

**Issue by sudippalash** [react-native-device-info/react-native-device-info#1404]
While I am trying to get phoneNumber I am getting "unknown" response.

OS: Android 11
API: 30

React Native : 0.67
React Native Device Info : 8.5.1

**Comment by mikehardy** [comment]
https://github.com/react-native-device-info/react-native-device-info#android-permissions-2

We can reopen if you triple check you have all the right permissions (check the PR that added that change to the README, for instance - find it via git blame on the file). I'm guessing it's just privacy constrained

**Comment by sudippalash** [comment]
I added permissions based on the readme reference link "https://developer.android.com/about/versions/11/privacy/permissions#phone-numbers"

but I got a response "unknown".

My Permission in Manifest file:
<manifest>
    
    <uses-permission android:name="android.permission.READ_PHONE_STATE"
                     android:maxSdkVersion="29" />
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
</manifest>

**Comment by TarikHuber** [comment]
@sudippalash could you solve this?
