### ISSUE TITLE
How to get the UDID

### ISSUE THREAD

**Issue by HuXin957** [react-native-device-info/react-native-device-info#1405]
## Summary

|             |     |
| ----------- | --- |
| Version     | 8.7.0   |
| OS Version  | 15.3  |

**Comment by luoxuhai** [comment]
@HuXin957 
Try this: [getUniqueId](https://github.com/react-native-device-info/react-native-device-info#getuniqueid)

**Comment by HuXin957** [comment]
Is not this，You can see it here "Xcode>Window>Devices and Simulators" , it's Identifier

**Comment by HuXin957** [comment]
First of all , so sorry ,but That's not what I meant. I looked at all the apis, and i am sure there's no answer I'm looking fro

**Comment by HuXin957** [comment]
First of all , so sorry ,but That's not what I meant. I looked at all the apis, and i am sure there's no answer I'm looking fro

**Comment by HuXin957** [comment]
First of all , so sorry ,but That's not what I meant. I looked at all the apis, and i am sure there's no answer I'm looking for
