### ISSUE TITLE
Different ID from getUniqueId() on iOS after OS update

### ISSUE THREAD

**Issue by KevinDeShawn** [react-native-device-info/react-native-device-info#1407]
<div id=":fn" class="Ar Au Ao" style="display: block;"><div id=":fj" class="Am Al editable LW-avf tS-tW tS-tY" hidefocus="true" aria-label="Message Body" g_editable="true" role="textbox" aria-multiline="true" style="direction: ltr; min-height: 376px;" tabindex="1" spellcheck="false" contenteditable="true"><h2 dir="auto">Summary</h2>
<p>I've been using the version 7.4.0 of this awesome library for a while now. <br></p><p>I use the function <code>getUniqueId</code> to uniquely identify devices.</p><p>Recently I have updated my device(an Iphone) to the OS version 15.3.1 and noticed that <code>getUniqueId</code> returns a <code>different id after the OS update.<br></code></p>
<p><code>Previous OS version of my device is 15.0.2</code></p>

  |  
-- | --
Version | 7.4.0
Affected OS | iOS
OS Version | 15.3.1(current)

<h2 dir="auto">Current behavior</h2>

<p dir="auto">
<code>getUniqueId</code> returns a different id for the same device&nbsp; after the OS update.<br></p>

<h2 dir="auto">Expected behavior</h2>

<p dir="auto"><code>getUniqueId</code> should return the same id for the same device after the OS update as well.</p>
<hr>
</div></div>

**Comment by jporrinobrosoft** [comment]
@KevinDeShawn were you able to solve this issue? I'm having the same problem

**Comment by jiangyu816** [comment]
+1

**Comment by bradzickafoose** [comment]
After updating 
react-native-device-info from 8.7.1 to 10.0.0 in my app, I noticed that `getUniqueId()` was returning `{"_h":0,"_i":0,"_j":null,"_k":null}` instead of the device id (which is what it previously did in 8.7.1). 

The way I fixed the issue was to use `getUniqueIdSync()` instead.

**Comment by mikehardy** [comment]
@bradzickafoose that is a different issue - you were seeing the classic "toString value of a Promise" because the breaking change in v10 was *exactly* that change as mentioned in the CHANGELOG and release notes, that getDeviceId is now async and returning a Promise. The original issue here is about different IDs, not different method signature.

**Comment by bradzickafoose** [comment]
Roger that. Apologies for the confusion.

**Comment by ycdaskin** [comment]
same here. any suggestions?

**Comment by seamive** [comment]
Any promise example to fetch everything in a constant?

We're using 

```
const carrierName = DeviceInfo.getCarrier().then((carrier) => {
  return carrier;
});
const  device: {
    api_level: DeviceInfo.getApiLevel(),
    brand: DeviceInfo.getBrand(),
    carrier: carrierName,
}
```

but getting `{"_h": 0, "_i": 1, "_j": 30, "_k": null}`

Thanks!

**Comment by mikehardy** [comment]
That's the classic presentation of an unresolved promise when sent into console.log

Not sure why it isn't resolved, but it appears to be unresolved somehow, whatever it is. Your code is very selective in this case. You may consult the example app here to see appropriate usage of every API

**Comment by seamive** [comment]
Can you please provide a link to the same on how to resolve the UNRESOLVED PROMISE?

Also, is migrating from 8.4.9 to 10.0.2 a major change? If yes, can you please share break change CHANGES.log?

Thanks!

**Comment by mikehardy** [comment]
> Can you please provide a link to the same on how to resolve the UNRESOLVED PROMISE?

No, with apologies, this is javascript knowledge not specific to this repository, so you'll have to search on your own on the broader internet

> Also, is migrating from 8.4.9 to 10.0.2 a major change? If yes, can you please share break change CHANGES.log?

This is...really confusing. Did you look? https://github.com/react-native-device-info/react-native-device-info/blob/master/CHANGELOG.md

**Comment by josh-gc** [comment]
For those stumbling on this, here is how I fixed it:
``` tsx
// Forgot await
const uniqueId = getUniqueId();
console.log(TAG, 'getUniqueId:', uniqueId);

// With Await
const uniqueIdAwait = await getUniqueId();
console.log(TAG, 'getUniqueIdAwait:', uniqueIdAwait);
```
Returns:
UserProfileContext.tsx -> getUniqueId: {"_h": 0, "_i": 0, "_j": null, "_k": null}
UserProfileContext.tsx -> getUniqueIdAwait: HDMUEH62-JSU4-ARYS-HJUG-62489CDAA782
```
