### ISSUE TITLE
getVersion result contains a build number

### ISSUE THREAD

**Issue by mtnt** [react-native-device-info/react-native-device-info#1411]
## Summary

|             |     |
| ----------- | --- |
| Version     | v8.4.3   |
| Affected OS | iOS/Android   |
| OS Version  | ?   |

## Current behavior

It seems sometimes, `getVersion` returns a build number additionally to a version (e.g. 1.9.0+27 or 1.9.0 (27)). I did not catch it by hand, but I found sentry releases with that names while an error report is configured as `release: DeviceInfo.getVersion()`.

I can not present some exact data, but I can list data from sentry:
- Android 6.0.1 Nexus 5X
- Android 12 M2101K7AG
- Android 11 SM-A505FN
- iOS 15.2 iPhone XR
- iOS 15.2.1 iPhone 11
- iOS 15.3.1 iPhone 11
- iOS 15.4.1 iPhone 11
- iOS 14.3 iPhone X
- iOS 15.2 iPhone X
- iOS 15.3.1 iPhone 12

each of devices is not emulator

## Expected behavior

A version from `DeviceInfo.getVersion()` does not contain a build number.

**Comment by mtnt** [comment]
Oh, I understand... but you can at least add a point about it in doc - I`m sure not all developers know about they can put into version field whatever they want. I mean, we a using RN for the purpose we don`t want to deal with ios/android subtleties (IMHO =)).

For my project, I just add an utility to get a semver-like string: `DeviceInfo.getVersion().match(/.*([0-9]+\.[0-9]+\.[0-9]+).*/)[1]`

**Comment by mikehardy** [comment]
@mtnt - sure! You can hit the edit button on any page in the doc to make a PR, I merge all reasonable PRs, and for small ones typically very quickly

**Comment by mtnt** [comment]
@mikehardy deal
