### ISSUE TITLE
isHeadphoneConnected: Bluetooth headset is not recognized in Android

### ISSUE THREAD

**Issue by TheShadowPlayer** [react-native-device-info/react-native-device-info#1415]
## Summary

|             |     |
| ----------- | --- |
| Version     |   8.7.1   |
| Affected OS |   android   |
| OS Version  |  12   |

## Current behavior

When I try to connect a Bluetooth headset, it is not recognized on Android. It works with wired headsets.
With the hook useIsHeadphonesConnected I only get the following back: { "loading": false, "result": false }

## Expected behavior

When connecting with a headset it should look like this: { "loading": false, "result": true }

## Probable error source

The isBluetoothA2dpOn function is used, but has been deprecated since API 26. Maybe you should change it to: https://stackoverflow.com/a/45629557

**Comment by mikehardy** [comment]
> The isBluetoothA2dpOn function is used, but has been deprecated since API 26. Maybe you should change it to: https://stackoverflow.com/a/45629557

"you" :thinking: ? PRs happily accepted! :+1: 

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

**Comment by TheShadowPlayer** [comment]
yes i know the principe of open source, but unfortunately i don't have the know how and time to fix this by myself.

**Comment by mikehardy** [comment]
No problem, I do understand that - unfortunately that means it'll sit until an interested party rolls up sleeves and tackles it. I will say, just as a possible motivator, I knew nothing of android mobile development (first) or react-native module development (second) until I just said "Oh what the heck, let's open up the docs and just play around and see if I can hack something up". It's possible to build the know-how by simply trying in other words - the code in react-native modules is typically very basic (thankfully!)

**Comment by schie** [comment]
I'll take a crack at this.

**Comment by Daveeeeeeeeee** [comment]
up for this
