### ISSUE TITLE
DeviceInfo.isHeadphonesConnectedSync() alway return false for iOS - iPhone 7

### ISSUE THREAD

**Issue by Joshig99** [react-native-device-info/react-native-device-info#1438]
Hi, i ran the example project and DeviceInfo.isHeadphonesConnectedSync()  and useIsHeadphonesConnected()  always return false for iphone 7 but its working fine with android, please help me how to fix that

IOS: 15.4.1
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 25.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 2022.06.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found

"react-native-device-info": "^10.0.1"

**Comment by mikehardy** [comment]
Hi there - with apologies, this is not a use case of mine and I do not have any extra volunteer time to help. I'm not aware of anyone else that works in this repo either, which means you will likely have to dig in yourself with the API calls in the objective-c to check API call parameters, return values etc
