### ISSUE TITLE
add getFirstInstallTime() for iOS

### ISSUE THREAD

**Issue by voxspox** [react-native-device-info/react-native-device-info#1440]
## Description

I want to know when the app was installed. I think `getFirstInstallTime()` will do that, but it is only available for Android.

Maybe this [article](https://medium.com/quick-code/how-to-get-app-install-date-in-react-native-ba4519150478) is helpful.

## Use Case

Add/complement iOS part for `getFirstInstallTime()`

**Comment by mikehardy** [comment]
All reasonable PRs are merged but you'll have to implement this yourself and propose it if this is an important use case for you

**Comment by mikehardy** [comment]
For what it's worth, I would love this. Relevant code

```objective-c
RCT_EXPORT_METHOD(exampleMethod)
{
NSURL* urlToDocumentsFolder = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject];
__autoreleasing NSError *error;
NSDate *installDate = [[[NSFileManager defaultManager] attributesOfItemAtPath:urlToDocumentsFolder.path error:&error] objectForKey:NSFileCreationDate];
NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
[dateFormatter setDateFormat:@"dd/mm/yyyy hh:mm:ss"];
NSString *stringDate = [dateFormatter stringFromDate:installDate];
[self emitMessageToRN:@"EXAMPLE_EVENT" :@{ @"date":stringDate }];
}
```

in particular this fetches it - the rest seems to be boilerplate to get it up to the javascript layer and may not apply here

```
NSURL* urlToDocumentsFolder = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] lastObject];
__autoreleasing NSError *error;
NSDate *installDate = [[[NSFileManager defaultManager] attributesOfItemAtPath:urlToDocumentsFolder.path error:&error] objectForKey:NSFileCreationDate];
```

**Comment by mikehardy** [comment]
That article was very helpful @voxspox - and I needed this for my work app, so I just implemented it. Will close when #1464 merges
