### ISSUE TITLE
The current version can't get Android Mac. It returns an empty string and has permissions set.

### ISSUE THREAD

**Issue by Barryhuan** [react-native-device-info/react-native-device-info#1443]
import React, { useState, useEffect, useCallback } from 'react';
import { View, Text, TextInput, Button } from 'react-native';
import DeviceInfo from 'react-native-device-info';
const App = () => {
  DeviceInfo.getMacAddress().then(res => {
    console.log(res) // ''
  });
  return (
    <View></View>
  )
}

export default App;

![Snipaste_2022-08-02_14-27-53](https://user-images.githubusercontent.com/46715367/182306749-5abb670c-12e2-4fd6-8f7c-bb2384ef5a4f.png)

**Comment by mikehardy** [comment]
I'm sorry, I can't really read images while using the mobile app and I'm traveling now. Strongly prefer posting relevant information as text when interacting with repos here on github.

Also, you've not included any information about versions etc https://stackoverflow.com/help/how-to-ask - what version of the module what version of android what minSdkVersion etc. 

You haven't mentioned what you have tried or which previous issues (there are a few) you have consulted - could you link in the issues you have seen here that are duplicate and attest you've handled all that?

**Comment by old** [comment]
> I'm sorry, I can't really read images while using the mobile app and I'm traveling now. Strongly prefer posting relevant information as text when interacting with repos here on github.
> 
> Also, you've not included any information about versions etc https://stackoverflow.com/help/how-to-ask - what version of the module what version of android what minSdkVersion etc.
> 
> You haven't mentioned what you have tried or which previous issues (there are a few) you have consulted - could you link in the issues you have seen here that are duplicate and attest you've handled all that?

I am having the same issue when upgrading to react-native v0.68.2, getMacAddress is returning a empty string now

**Comment by old** [comment]
> import React, { useState, useEffect, useCallback } from 'react'; import { View, Text, TextInput, Button } from 'react-native'; import DeviceInfo from 'react-native-device-info'; const App = () => { DeviceInfo.getMacAddress().then(res => { console.log(res) // '' }); return ( ) }
> 
> export default App;
> 
> ![Snipaste_2022-08-02_14-27-53](https://user-images.githubusercontent.com/46715367/182306749-5abb670c-12e2-4fd6-8f7c-bb2384ef5a4f.png)

Were you able to fix this by any chance?

**Comment by Barryhuan** [comment]
> 

Sorry to disturb your trip. This is the first time I asked a question. It's not detailed enough. The react native version I used at that time was 0.69.3. This version can't get the getmacaddress of react native device info. Later, I changed the react native version to 0.63.3 and it can be obtained normally. Because I'm a novice, please forgive me
