### ISSUE TITLE
"uniqueId" not compliant with Huawei App market Policies ,how to modify version of 2.2.2

### ISSUE THREAD

**Issue by caifu23** [react-native-device-info/react-native-device-info#1446]
## Summary

|             |     |
| ----------- | --- |
| Version     | 2.2.2   |
window 

## Current behavior
"Android_ID" not compliant with Huawei App market Policies,
but now is use version of 2.2.2, because react-native version is 0.59，and other plugins is too old ，couldn‘t to upgrade this package to version of 10.0.0.
i want to know how to use it, base on version 2.2.2

**Comment by fengqingyun2008** [comment]
"Android_ID" not compliant with Huawei App market Policies,
+1

**Comment by stawecki** [comment]
The simplest solution is:

Before building the APK, in your project directory, edit the file
```
node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
```
 and remove the line:
```
constants.put("uniqueId", Settings.Secure.getString(this.reactContext.getContentResolver(), Settings.Secure.ANDROID_ID));
```
I assume you're not actually using uniqueId. This will remove its value from constants, so it will be empty when calling getUniqueId()

More details in #1427

You can also use a shell script, I used to run it on each release before the package was patched e.g.:
```
grep -v '"uniqueId"' node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java > RNDeviceModule.java_
rm node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
mv RNDeviceModule.java_ node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
```

**Comment by mikehardy** [comment]
Much better to use patch-package, in my opinion. Make the edit once in node_modules/etc etc  then use patch-package to generate a stable diff against that version and apply it on all installs

https://github.com/ds300/patch-package
