### ISSUE TITLE
[Feature Request]: is24HourFormat function

### ISSUE THREAD

**Issue by robrechtme** [react-native-device-info/react-native-device-info#1447]
## Description

Hi! It would be nice if this lib offers a `is24HourFormat` function: 

It could be based on https://github.com/steffenagger/react-native-device-time-format (which is not really maintained anymore)

## Use Case

Formatting of times used to be done based on the user's locale. This is in fact incorrect, since both iOS and Android have a separate setting for the clock format.

**Comment by mikehardy** [comment]
Hi there! What you want is this: https://github.com/zoontek/react-native-localize

It's maintained quite well, I use it

**Comment by robrechtme** [comment]
Thanks for the response! `react-native-localize` was already included in our project, I just wasn't aware of the method. Sorry for wasting your time 🤦
