### ISSUE TITLE
Improper Export of your Android Broadcast Receiver

### ISSUE THREAD

**Issue by tusharsarkar** [react-native-device-info/react-native-device-info#1449]
## Summary

Have issues with android Broadcast Receiver

## Current behavior

Improper Export of your Android Broadcast Receiver

## Expected behavior

We should have proper export of Android Broadcast Receiver in code base.

## Code
```
<receiver android:enabled="true" android:exported="true" android:name="com.learnium.RNDeviceInfo.RNDeviceReceiver"> <intent-filter>
<action android:name="com.android.vending.INSTALL_REFERRER"/> </intent-filter>
</receiver>
```

**Comment by mikehardy** [comment]
> We should have proper export of Android Broadcast Receiver in code base.

We should!

When you post a PR for the same I can probably get it merged and released

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b
