### ISSUE TITLE
Unable to detect noxplayer emulator

### ISSUE THREAD

**Issue by KKChong** [react-native-device-info/react-native-device-info#1450]
I've tried to run the app on the Nox emulator. It seems like the SDK is not able to detect the nox emulator. Below is the system information of the emulator:

Nox version: 7.0.3.3033-9.0900220715
Android version: Android 9(64 bit)
System version: Windows10-64bit-4cpu
Computer model: MSI-MS-7850
CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
Total memory: 15.9 GB
Available memory: 10.0 GB
CPU VT: Enabled
Rendering mode: OpenGL+
OpenGL version: 4.3.0 - Build 20.19.15.4624
OpenGL rendering: Intel(R) HD Graphics 4600
Discrete graphics: Enabled
Graphics card1: Intel(R) HD Graphics 4600
Firewall: Enabled(Recommend to disable)
Installation path: D:\Program Files\Nox\bin
Log Path: C:\Users\KK\AppData\Local\Nox
Emulator disk space: total 128G, available 116G

```
public boolean isEmulatorSync() {
    return Build.FINGERPRINT.startsWith("generic")
            || Build.FINGERPRINT.startsWith("unknown")
            || Build.MODEL.contains("google_sdk")
            || Build.MODEL.toLowerCase(Locale.ROOT).contains("droid4x")
            || Build.MODEL.contains("Emulator")
            || Build.MODEL.contains("Android SDK built for x86")
            || Build.MANUFACTURER.contains("Genymotion")
            || Build.HARDWARE.contains("goldfish")
            || Build.HARDWARE.contains("ranchu")
            || Build.HARDWARE.contains("vbox86")
            || Build.PRODUCT.contains("sdk")
            || Build.PRODUCT.contains("google_sdk")
            || Build.PRODUCT.contains("sdk_google")
            || Build.PRODUCT.contains("sdk_x86")
            || Build.PRODUCT.contains("vbox86p")
            || Build.PRODUCT.contains("emulator")
            || Build.PRODUCT.contains("simulator")
            || Build.BOARD.toLowerCase(Locale.ROOT).contains("nox")
            || Build.BOOTLOADER.toLowerCase(Locale.ROOT).contains("nox")
            || Build.HARDWARE.toLowerCase(Locale.ROOT).contains("nox")
            || Build.PRODUCT.toLowerCase(Locale.ROOT).contains("nox")
            || Build.SERIAL.toLowerCase(Locale.ROOT).contains("nox")
            || (Build.BRAND.startsWith("generic") && Build.DEVICE.startsWith("generic"));
 }
```

the method above, is no longer valid anymore because noxplayer already replace the "nox" keyword with real valid keyword.

**Comment by mikehardy** [comment]
Hi there! If you propose a PR that solves your issue, we'll be happy to merge it
