### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Talanoff** [react-native-device-info/react-native-device-info#1451]
Google requires at least SDK 31 to publish an app to the Play Market. But when I specify target & compile SDK versions to 31 build fails.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
    }

**Comment by jsite-pl** [comment]
SDK31 needs JDK11, So change your JDK in android studio or update JDK on your computer and update JAVA_HOME env path.

There was few issues about that:
#1350 #1406 #1348 #1362

**Comment by mikehardy** [comment]
Thanks for the help @jsite-pl, much appreciated - @Talanoff those were the right answers above, hopefully you're unstuck. Cheers
