### ISSUE TITLE
DeviceInfo.getPhoneNumber shows unknown when clear data from Application and in release APK

### ISSUE THREAD

**Issue by SanjanaTailor** [react-native-device-info/react-native-device-info#1454]
Hello, 

 var phoneno: any = [];
    DeviceInfo.getPhoneNumber().then((phoneNumber) => {
      console.log('phoneNumber------->>>>', phoneNumber);
    });
    
From the settings , in Apps section open application and clear data re-run the application 
phoneNumber shows unknown also this issue happening in release APK.

Permissions are added in Manifest file.
 <uses-permission android:name="android.permission.READ_PHONE_STATE" />
 <uses-permission android:name="android.permission.READ_SMS" />

Please suggest solution. Thank you

**Comment by gdpr1504** [comment]
Any solution to this?

**Comment by mikehardy** [comment]
@gdpr1504 I don't see any in the comments? What did you find when you investigated and tried to fix it?

https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b

**Comment by gdpr1504** [comment]
For me it was working. The problem actually was with the sim which you are using. Few sim are not published with number. So they return unknown. Try with other sim. It might result the number.
Code:
In Android XML File:(Added this line)
<uses-permission android:name="android.permission.READ_SMS"/>

Npm Package:
import DeviceInfo from 'react-native-device-info';

Linked the react native project using:
react-native link react-native-device-info

Used Below Code to access the number: - This works only if you allow the permissions.

 if (
      hasReadSMSPermission === PermissionsAndroid.RESULTS.GRANTED
    ) {
      const phoneNumber = await DeviceInfo.getPhoneNumber();
      console.log(phoneNumber); //Returns the number
    }else{
      console.log("Permission Denied")
    }

Also check the sim settings in phone if the number displaying in sim settings or not.

**Comment by SanjanaTailor** [comment]
@gdpr1504 : In Android XML file which line added ? Is related to permissions SMS

**Comment by manoharkharvi43** [comment]
Still the same issue, not resolved.
