### ISSUE TITLE
Can I get some sample output from react-native-device-info?

### ISSUE THREAD

**Issue by Saif-MindCoopers** [react-native-device-info/react-native-device-info#1456]
Is that possible to get all the data as a log ? Instead of calling every API one by one ? 

Here is example for log.
`{getDeviceName:  Name of My Phone,
getUniqueID:    f12edc3b4af56e78,
getManufacturer:    samsung,
getModel:   SM-G950U,
getSystemName:  Android,
getSystemVersion:   8.0.0,
getBrand:   samsung,
getAPILevel:    26,
getUserAgent:   Mozilla/5.0 (Linux; Android 8.0.0; SM-G950U Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36,
isTablet:   false,
getApplicationName: My Awesome App,
getBundleId:    com.app.awesome,
getBuildNumber: 1,
getVersion: 0.0.0,
getReadableVersion: 0.0.0.1}`

**Comment by mikehardy** [comment]
No, there is no API that does that. All the APIs we have are documented. In my app I call them all to populate an object
