### ISSUE TITLE
Main module is declared as  `deviceInfoModule` instead of `DeviceInfo`

### ISSUE THREAD

**Issue by lukasgjetting** [react-native-device-info/react-native-device-info#1461]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

In the documentation, the main module is imported as `DeviceInfo`.

However, in the code the exported variable is named `deviceInfoModule`. This means the generated TypeScript declaration file (`/lib/typescript/index.d.ts`) defines it as:

```ts
declare const deviceInfoModule: DeviceInfoModule;
export default deviceInfoModule;
```

The auto import feature VS Code will thus treat (and import) the module as if it is named `deviceInfoModule`:

![image](https://user-images.githubusercontent.com/17611888/190218492-673581fc-2cba-4225-810b-231e53611dce.png)
![image](https://user-images.githubusercontent.com/17611888/190218602-ddcdbd1f-ffae-4611-9d8a-34c806cdffe1.png)

IMO, it would be better to match the documentation and declare it as:

```ts
declare const DeviceInfo: DeviceInfoModule;
export default DeviceInfo;
```

Very minor, but it makes the experience a bit nicer. I'd be happy to provide a PR - for now I'm just fixing it locally with `patch-package`.

**Comment by mikehardy** [comment]
Interesting - your idea does seem to improve developer experience, seems reasonable. Would it be a breaking change? I don't think it would but if it's a breaking change it either a) may not be worth *that* much or b) we'll have to bump the major version if we think it's worth that much.

If people import * from the module, they would be receiving our deviceInfoModule name and thus we would break them if I understand correctly? Is that how it works in practice?

**Comment by schie** [comment]
@mikehardy, I don't view a changing of the default variable name as breaking as it's up to what ever the developer wants to name it. Like you mentioned, I view this a developer experience improvement.

For example, I use `device` or a 'spread' for imports like so,

```ts
import device from 'react-native-device-info';
import { isTablet } from 'react-native-device-info';
```

If we want to do it, I can make the quick change 'patch'

**Comment by mikehardy** [comment]
Sure give it a go
