### ISSUE TITLE
NativeModule.RNDeviceInfo is null error - Android 11 Device 

### ISSUE THREAD

**Issue by luisrmmalaga** [react-native-device-info/react-native-device-info#1465]
React Native Version ->  0.64.3
| Affected OS | Android |
| OS Version  | 11 |

## Current behavior

![image](https://user-images.githubusercontent.com/48436088/191857221-9cf72051-cb40-420a-8455-237c4f33b43c.png)

![image](https://user-images.githubusercontent.com/48436088/191857361-8db10392-ca8f-44dd-9901-346c61d37072.png)

![image](https://user-images.githubusercontent.com/48436088/191857380-8ee32b53-2075-466a-af21-315698c47b73.png)

I'm trying to get Android id from the device but the app show me that error always.

I have read the rest of issues/posts and i don't know how to solve it.

I'm using Expo framework.

**Comment by OkancanCosar** [comment]
Before closing this error, I wish you had written how you solved it. So that we could take advantage of it.

**Comment by mikehardy** [comment]
@OkancanCosar the error message itself contains the root cause. If you are an Expo user this module is likely not built in to your native code so it is null, leading back to that same root cause. No native module in your app? javascript fails to load it. Troubleshoot accordingly
