### ISSUE TITLE
Android installation issue : Could not find com.google.android.gms:play-services-iid:18.0.0.

### ISSUE THREAD

**Issue by worktechnotoil** [react-native-device-info/react-native-device-info#1466]
android installation issue  "react-native": "0.69.1",

![Screenshot 2022-09-23 at 12 15 16 PM](https://user-images.githubusercontent.com/84009897/191906057-0317b1a7-24fd-47cb-9333-a6ec1400fa5b.png)

**Comment by mikehardy** [comment]
Network or gradle config issue could not contact repository that contains the dependency everyone else seems to have no trouble contacting
Not a bug in the module
