### ISSUE TITLE
Get device time format

### ISSUE THREAD

**Issue by 98gzi** [react-native-device-info/react-native-device-info#1467]
This is a feature request, wasn't sure where to post it.

The following package is no longer supported: https://github.com/steffenagger/react-native-device-time-format

I think it would be great, if this was implemented part of this package!

**Comment by mikehardy** [comment]
Hi there! We will not add any formating stuff, what you want is react-native-localize, this module and that module worked together to re-home all locale/internationalization type APIs over there where they may have a focused, well-maintained home.

https://github.com/zoontek/react-native-localize#uses24hourclock etc

Should do what you need

**Comment by 98gzi** [comment]
Thanks Mike 👍
