### ISSUE TITLE
iPhone 14 is reported as model "iPhone" - not "iPhone 14" so hasNotch does not work

### ISSUE THREAD

**Issue by MalinnaLeach** [react-native-device-info/react-native-device-info#1468]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.2.0  |
| Affected OS | 16  |
| OS Version  | 16  |

## Current behavior

```
export function hasNotch() {
  if (notch === undefined) {
    let _brand = getBrand();
    let _model = getModel();
    console.log('RNDeviceInfo.model: ', RNDeviceInfo.model);
    notch =
      devicesWithNotch.findIndex(
        (item) =>
          item.brand.toLowerCase() === _brand.toLowerCase() &&
          item.model.toLowerCase() === _model.toLowerCase()
      ) !== -1;
  }
  console.log('notch: ', notch);
  return notch;
}
```

- RNDeviceInfo.model is just coming through as `iPhone` not `iPhone 14` for an iPhone 14
- This means that hasNotch is always returning false, when it should be true

## Expected behavior

- hasNotch should return true for iPhone 14

**Comment by serhiiharbo** [comment]
@MalinnaLeach 
Use `model: DeviceInfo.getModel()` instead.
In v10.2.0 that method will try to pick up deviceName by deviceId (deviceCode)
https://github.com/react-native-device-info/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L304

**Comment by MalinnaLeach** [comment]
Ah - apologies - I've got this working now..
