### ISSUE TITLE
Realtime memory usage not updating 

### ISSUE THREAD

**Issue by UdithaChathuranga** [react-native-device-info/react-native-device-info#1469]
"react-native": "^0.68.2",
"react-native-device-info": "^10.0.2",

Hi,
When use in the DeviceInfo.getUsedMemory() in android and iOS shows different value when comparing to the android studio and Xcode profile
In android memory usage realtime not updating. (Sometime the memory spike doesn't show)

In iOS memory usage values are incorrect when compering to the Xcode profile.

Do you know what is the reasons for this for those 2 issues?

Thanks.

**Comment by mikehardy** [comment]
Hi there! No I don't, sorry. The code is available though and uses very simple APIs, it's possible to investigate and share your findings here. If something needs correction, I'll happily merge + release any reasonable PR

**Comment by UdithaChathuranga** [comment]
![memoryDeviceiNFO](https://user-images.githubusercontent.com/114398166/192694904-1f21a962-c63c-41ea-bd65-5ced2ef81118.jpg)

```

  DeviceInfo.getUsedMemory().then((usedMemory) => {
      const RamUsageMegabites= usedMemory *  0.00000095367432 
      console.log("usedMemory",RamUsageMegabites)
  });
```

Here is the example of memory output of the library and the Xcode profile. 
Can you explain why is that different?

**Comment by mikehardy** [comment]
No, I can't - but you've got the source code and documentation for the various APIs we use all available, and can investigate. If something needs correction, I'll happily merge + release any reasonable PR
