### ISSUE TITLE
New fabric architecture

### ISSUE THREAD

**Issue by hansdesmedt** [react-native-device-info/react-native-device-info#1470]
Hello. Are there any plans to update this library to support TurboModules?

We will add the lib to the list 

https://github.com/reactwg/react-native-new-architecture/discussions/6

**Comment by hansdesmedt** [comment]
started working on Fabric migration

https://github.com/hansdesmedt/react-native-device-info/commits/master

**Comment by mikehardy** [comment]
Looks really promising, fantastic @hansdesmedt

**Comment by schie** [comment]
@hansdesmedt Do you have a link to any guides  to implement these changes to support and documentation on the new architecture?

**Comment by hansdesmedt** [comment]
yeah in this case you need the feat/back-turbomodule-070 branch from 

https://github.com/react-native-community/RNNewArchitectureLibraries

because this is a turbo module for RN 0.70+ and not a component.

Here some docs

https://reactnative.dev/docs/new-architecture-intro

**Comment by schie** [comment]
@hansdesmedt,

a few days ago, I had to go through this on a private (work) project.

After banging my head against the wall for the better part of a work day, we ended with the solution of just making a new boiler plate project via [create-react-native-library](https://github.com/callstack/react-native-builder-bob/tree/main/packages/create-react-native-library), then copying over all the relevant code.

**Comment by BraveEvidence** [comment]
This might help to get you started https://www.youtube.com/watch?v=q3-Mrwd1Vm0

**Comment by bhaskarathma** [comment]
Can we please reopen this issue? We still need new architecture support for this library

**Comment by itsramiel** [comment]
@mikehardy 

I have experience migrating ios/android to new arch but I dont know about windows. Can it be partially migrated if I worked on it or a pr has to include all platforms?

**Comment by mikehardy** [comment]
Hey that sounds great, incremental is probably the only way it will happen so that seems fine to me

I have no experience yet with migrating modules to new architecture so I won't be able to offer much review or help but I can merge things

**Comment by itsramiel** [comment]
If anyone is interested in testing new arch for ios please check [this pr](https://github.com/react-native-device-info/react-native-device-info/pull/1598)
