### ISSUE TITLE
DeviceInfo.getDeviceNameSync() return 'iPhone' on iOS 16

### ISSUE THREAD

**Issue by authordev99** [react-native-device-info/react-native-device-info#1472]
Affected on v9.0.2 Device info, before upgraded to iOS 16.
getDeviceNameSync returned value as expected.

## Current behavior

iOS 16 returned 'iPhone' as device name

## Expected behavior

should be return device name as user input on phone settings

**Comment by mikehardy** [comment]
Step 1) upgrade to current version of package to see if whatever issue you are seeing is still there

In no cases open an issue on old versions, it is not an efficient use of time

Step 2) then open an issue if it still reproduces taking care to include exactly how you trigger the behavior that seems erroneous (https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by syntheticencounters** [comment]
#1501 Check my comment in this issue. Apple has a new entitlement that is required before accessing this information on iOS 16.
