### ISSUE TITLE
Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver

### ISSUE THREAD

**Issue by mansilaad** [react-native-device-info/react-native-device-info#1474]
App is crashing Abruptly.

| Version -10.2.1 
| Affected OS - Android
| OS Version - 10, 11 
| react-native-version - 0.64.2

Error( tracked on bugsnag)  - Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" 

StackTrace - 

java.lang.RuntimeException · Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/lib/arm64, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]RawActivityThread.java:4082 android.app.ActivityThread.handleReceiverActivityThread.java:272 android.app.ActivityThread.access$1700ActivityThread.java:2066 android.app.ActivityThread$H.handleMessageHandler.java:107 android.os.Handler.dispatchMessageLooper.java:237 android.os.Looper.loopActivityThread.java:8016 android.app.ActivityThread.mainMethod.java:-2 java.lang.reflect.Method.invokeRuntimeInit.java:496 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runZygoteInit.java:1076 com.android.internal.os.ZygoteInit.mainCaused By: java.lang.ClassNotFoundException · Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/lib/arm64, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]BaseDexClassLoader.java:196 dalvik.system.BaseDexClassLoader.findClassClassLoader.java:379 java.lang.ClassLoader.loadClassClassLoader.java:312 java.lang.ClassLoader.loadClassAppComponentFactory.java:110 android.app.AppComponentFactory.instantiateReceiverCoreComponentFactory.java:60 androidx.core.app.CoreComponentFactory.instantiateReceiverActivityThread.java:4075 android.app.ActivityThread.handleReceiverActivityThread.java:272 android.app.ActivityThread.access$1700ActivityThread.java:2066 android.app.ActivityThread$H.handleMessageHandler.java:107 android.os.Handler.dispatchMessageLooper.java:237 android.os.Looper.loopActivityThread.java:8016 android.app.ActivityThread.mainMethod.java:-2 java.lang.reflect.Method.invokeRuntimeInit.java:496 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runZygoteInit.java:1076 com.android.internal.os.ZygoteInit.main

**Comment by mikehardy** [comment]
1- This stack trace is formatted in such a way it is almost unreadable, you have not put in the effort with formatting to help people help you. Triple-backticks are your friend in markdown when posting large amounts of text

2- This module is in use by thousands and thousands of people and has been forever and you're the only report of this, so it is pretty suspect. I use it and do not reproduce this, and it has not come up before that I remember 

3- I assume this is release mode. I assume you have proguard on, but those are assumptions. You might post (in triple backtick enclosures!) your android/build.gradle / android/app/build.gradle files to see how proguard is used (https://stackoverflow.com/help/how-to-ask)

4- better than all that given that no one else is reproducing this, you might try to reproduce it cleanly in a fresh repo (https://stackoverflow.com/help/minimal-reproducible-example). `npx react-native init RNDITest && cd RNDITest && yarn add react-native-device-info && npx react-native run-android --variant release` to see how it goes.

**Comment by mansilaad** [comment]
Please accept apologies for the inconvenience.

Please find the Error details below - 

**1. App is crashing on random actions, there is no particular action for reproducing this error.**

   Affected Models - 
   
   POCO X3 Pro (M2102J20SI)
   OnePlus9R (LE2101)
   Nothing phone (1) (A063)
   Redmi 9 Power (M2010J19SI)
   
   Error ( tracked on bugs tracking tool )  - 
   
   a.  `java.lang.RuntimeExceptionMainActivity
        Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: 
        Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/~~vc-e- 
        ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/base.apk"],nativeLibraryDirectories=. 
        [/data/app/~~vc-e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/lib/arm64, /data/app/~~vc- 
        e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/base.apk!/lib/arm64-v8a, /system/li`

   b. `java.lang.RuntimeExceptionBaseDexClassLoader.java:218
         Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: 
         Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file 
         "/data/app/~~lxLvFt6SHGOdTongZQnkUg==/com.travelxp-vbsOoAPSjpoNQpHYi9rrGg==/base.apk", zip file 
          "/data/app/~~lxLvFt6SHGOdTongZQnkUg==/com.travelxp- 
          vbsOoAPSjpoNQpHYi9rrGg==/split_config.arm64_v8a.apk", zip file 
        "/data/app/~~lxLvFt6SHGOdTongZQnkUg==/com.travelxp-vbsOoAPSjpoNQpHYi9rrGg==/split_config.bn.apk", z`

2 . **Formatted stacktrace**  - 

`java.lang.RuntimeException · Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/~~vc-e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/base.apk"],nativeLibraryDirectories=[/data/app/~~vc-e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/lib/arm64, /data/app/~~vc-e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]RawActivityThread.java:4116 android.app.ActivityThread.handleReceiverActivityThread.java:257 android.app.ActivityThread.access$1600ActivityThread.java:1993 android.app.ActivityThread$H.handleMessageHandler.java:106 android.os.Handler.dispatchMessageLooper.java:236 android.os.Looper.loopActivityThread.java:8056 android.app.ActivityThread.mainMethod.java:-2 java.lang.reflect.Method.invokeRuntimeInit.java:656 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runZygoteInit.java:967 com.android.internal.os.ZygoteInit.mainCaused By: java.lang.ClassNotFoundException · Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/~~vc-e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/base.apk"],nativeLibraryDirectories=[/data/app/~~vc-e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/lib/arm64, /data/app/~~vc-e-ow-o1mJKkCXjkgKkA==/com.travelxp-CjW6hhCYBD_XOiGjVCor3w==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]BaseDexClassLoader.java:207 dalvik.system.BaseDexClassLoader.findClassClassLoader.java:379 java.lang.ClassLoader.loadClassClassLoader.java:312 java.lang.ClassLoader.loadClassAppComponentFactory.java:110 android.app.AppComponentFactory.instantiateReceiverCoreComponentFactory.java:60 androidx.core.app.CoreComponentFactory.instantiateReceiverActivityThread.java:4109 android.app.ActivityThread.handleReceiverActivityThread.java:257 android.app.ActivityThread.access$1600ActivityThread.java:1993 android.app.ActivityThread$H.handleMessageHandler.java:106 android.os.Handler.dispatchMessageLooper.java:236 android.os.Looper.loopActivityThread.java:8056 android.app.ActivityThread.mainMethod.java:-2 java.lang.reflect.Method.invokeRuntimeInit.java:656 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runZygoteInit.java:967 com.android.internal.os.ZygoteInit.main`

3. This error is occurring in release as well as development mode.

   Proguard is used as below- 
   
   **file - android/app/build.gradle**
   
   `....
    def enableProguardInReleaseBuilds = false
    ....
    ....
     buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
             // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
   `
   
   **file  -  android/app/proguard-rules.pro**
   
   `# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:
-dontwarn io.branch.**
-keep class in.juspay.** {*;}`


Could you please help me here? 
What could be the reason behind this?
What should I do to solve it?

**Comment by mikehardy** [comment]
No idea sorry, never seen this before. I recommend you create a blank react-native app with `npx react-native init TestApp`, then add react-native-device-info to it, then do whatever you do to reproduce this in development. If you cannot reproduce it in development, then there is something wrong with your project - what? I do not know, sorry.

I do not reproduce this and no one else has logged anything like this that I know of

**Comment by ravi123saxena** [comment]
> App is crashing Abruptly.
> 
> | Version -10.2.1 | Affected OS - Android | OS Version - 10, 11 | react-native-version - 0.64.2
> 
> Error( tracked on bugsnag) - Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver"
> 
> StackTrace -
> 
> java.lang.RuntimeException · Unable to instantiate receiver com.learnium.RNDeviceInfo.RNDeviceReceiver: java.lang.ClassNotFoundException: Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/lib/arm64, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]RawActivityThread.java:4082 android.app.ActivityThread.handleReceiverActivityThread.java:272 android.app.ActivityThread.access$1700ActivityThread.java:2066 android.app.ActivityThread$H.handleMessageHandler.java:107 android.os.Handler.dispatchMessageLooper.java:237 android.os.Looper.loopActivityThread.java:8016 android.app.ActivityThread.mainMethod.java:-2 java.lang.reflect.Method.invokeRuntimeInit.java:496 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runZygoteInit.java:1076 com.android.internal.os.ZygoteInit.mainCaused By: java.lang.ClassNotFoundException · Didn't find class "com.learnium.RNDeviceInfo.RNDeviceReceiver" on path: DexPathList[[zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk", zip file "/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/lib/arm64, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/base.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.travelxp-MVk6LmfWKHQ5edvnCO_dTA==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]BaseDexClassLoader.java:196 dalvik.system.BaseDexClassLoader.findClassClassLoader.java:379 java.lang.ClassLoader.loadClassClassLoader.java:312 java.lang.ClassLoader.loadClassAppComponentFactory.java:110 android.app.AppComponentFactory.instantiateReceiverCoreComponentFactory.java:60 androidx.core.app.CoreComponentFactory.instantiateReceiverActivityThread.java:4075 android.app.ActivityThread.handleReceiverActivityThread.java:272 android.app.ActivityThread.access$1700ActivityThread.java:2066 android.app.ActivityThread$H.handleMessageHandler.java:107 android.os.Handler.dispatchMessageLooper.java:237 android.os.Looper.loopActivityThread.java:8016 android.app.ActivityThread.mainMethod.java:-2 java.lang.reflect.Method.invokeRuntimeInit.java:496 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.runZygoteInit.java:1076 com.android.internal.os.ZygoteInit.main

Did it fix ? What is the solution. Please help here..
