### ISSUE TITLE
getDeviceId returns wrong id

### ISSUE THREAD

**Issue by SeongwoonHong** [react-native-device-info/react-native-device-info#1479]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.0.2 |
| Affected OS | iOS  |
| OS Version  |  iOS16.0  |

## Current behavior

I'm getting `iPhone14,5` on my iPhone 13 device from `getDeviceId()`

## Expected behavior

I should be getting `iPhone13` since my phone is iPhone 13

**Comment by mikehardy** [comment]
I don't have these devices to test on, if this is a bug you'll need to provide a PR yourself based on work you do on your device. I can merge and release

**Comment by SeongwoonHong** [comment]
@mikehardy thank you. do you happen to know what the digit that comes after the comma mean ?

**Comment by mikehardy** [comment]
@SeongwoonHong I performed a basic web search for you and found information https://www.theiphonewiki.com/wiki/Models#iPhone

**Comment by opayen** [comment]
This is not a bug, it's just how Apple names their products (see the [GSMArena product page for iPhone 13](https://www.gsmarena.com/apple_iphone_13-11103.php), in the Misc section they indicate that the model name is `iphone14,5`).

What you're after is probably `DeviceInfo.getModel()`

**Comment by SeongwoonHong** [comment]
Thank you everyone i'll close it
