### ISSUE TITLE
Android App Set Id

### ISSUE THREAD

**Issue by OpenTasteSG** [react-native-device-info/react-native-device-info#1480]
## Description

Is the Android App Set Id currently implemented?

https://developer.android.com/training/articles/app-set-id
## Use Case

Like to track different developer own apps installed on the same device

**Comment by mikehardy** [comment]
What did you see when you checked the module? All the code is available to you

**Comment by mikehardy** [comment]
I don't want to see any more dependencies used as backing for implementation of getUniqueId if possible, I just replaced the IID one in https://github.com/react-native-device-info/react-native-device-info/pull/1475 and I don't want to go back

I'm not against seeing an implementation of app set id but is should be named for exactly what it is, and optional + non-breaking

**Comment by markwilcox** [comment]
Makes sense, thanks for the speedy response. It doesn't exactly feel like the privacy-respecting identifier landscape is stable right now. Not 100% sure we need persistent for one vendor across apps for this use case. If we decide we do, I'll be back with a PR. Otherwise a UUID will do.

**Comment by mikehardy** [comment]
> It doesn't exactly feel like the privacy-respecting identifier landscape is stable right now

Been this way for the 3+ years I've been watching it. I expect it will never stabilize because there are financial incentives to track and privacy incentives to not track, leading to sufficient funding on both sides for an infinite arms race.
