### ISSUE TITLE
:react-native-device-info:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by RatikantAppstango** [react-native-device-info/react-native-device-info#1481]
Hello ,
I am facing issue with Execution failed for task :react-native-device-info:compileDebugJavaWithJavac in my working project.
I have tried using JDK version 11, Default android studio JDK 11 but also getting this same issue.

Is there any solution please provide me

Thankyou

**Comment by mikehardy** [comment]
https://github.com/facebook/react-native/issues/35210

**Comment by RatikantAppstango** [comment]
The version update is still not working 
I was using react native version 0.66.4 and updated it to 66.5 and 67.5 but still the same error.

**Comment by AlkanV** [comment]
hello, i have same error using 0.67.5. any updates on this?

**Comment by mikehardy** [comment]
There will be no further updates on this. The module has no compilation error. The link above to the generic issue for react-native compilation errors is canonical
