### ISSUE TITLE
Device OPPO A3s change name device, getDeviceName not working 

### ISSUE THREAD

**Issue by ngoctran5596** [react-native-device-info/react-native-device-info#1482]
## Summary

|             |     |
| ----------- | --- |
|Package  |Version
|react-native-device-info     |   10.2.1  |
|react-native   |  0.68.0  |

## Current behavior
I changed the device name on OPPO A3s, OPPO A9 android but getDeviceName is not working with my new name. It takes the old name of the device.

thanks

**Comment by mikehardy** [comment]
Hi there! You may need to restart your device prior to it taking effect.
Either way - if this is important to you, you will need to invest the time to look into node_modules and add logging code to the relevant javascript and Java code areas for this API to see what the calls + return values on the API look like, and see why your device is not behaving as expected.

I can merge+release any reasonable PR you come up with based on your findings.

**Comment by ngoctran5596** [comment]
@mikehardy i have tried many ways, reset my phone after change name but still not working. Almost tried many types of OPPO and it doesn't work. help me please.

**Comment by mikehardy** [comment]
I don't have the time to solve your problem sorry. My previous comment stands. The code is available here for the module, it's all open source. Use that to troubleshoot your problem
