### ISSUE TITLE
Device Processor and Memory Usage

### ISSUE THREAD

**Issue by AndersonLeandrog** [react-native-device-info/react-native-device-info#1483]

**Comment by mikehardy** [comment]
All reasonable PRs happily excepted - I just did a quick scan on the internet and did not see any obvious hits for this sort of thing in other modules

**Comment by AndersonLeandrog** [comment]
> All reasonable PRs happily excepted - I just did a quick scan on the internet and did not see any obvious hits for this sort of thing in other modules

ok thanks anyway, I'm looking for an API that performs this function as I'm developing an application whose purpose is to display detailed information about the system.
