### ISSUE TITLE
Support for Display Zoom

### ISSUE THREAD

**Issue by jkester1986** [react-native-device-info/react-native-device-info#1485]
## Description

Would like to see a way to determine if the device's display is set to Zoom vs Standard

## Use Case

When users zoom in on our app, the styling gets messed up. Having a way to determine if the device is zoomed or not would be incredibly helpful

**Comment by mikehardy** [comment]
Hi there - do you mean something like this? https://www.reddit.com/r/androiddev/comments/80y795/how_to_programmatically_check_if_user_has/

That is, things affected by accessibility zoom?

If so maybe https://developer.android.com/reference/android/util/DisplayMetrics#DENSITY_DEVICE_STABLE versus https://developer.android.com/reference/android/util/DisplayMetrics#densityDpi  (or the other density methods) ?

I wonder if PixelRatio is useful for this at all? https://reactnative.dev/docs/pixelratio

If PixelRatio is not useful and you must have DisplayMetrics information, we could merge a PR that exposed the DisplayMetrics from Android

**Comment by jkester1986** [comment]
@mikehardy we need it for the Display Zoom. I can see use in knowing the accessibility zoom as well, though it isn't my current focus.

https://user-images.githubusercontent.com/1626364/205133124-f4110fe3-4294-4d6e-9507-eefb578eb55a.mov

Our app is currently just iOS so the DisplayMetrics wouldn't work for us.

It doesn't look like pixelratio will work either - both standard and zoomed give the same value. I did look into [Dimensions](https://reactnative.dev/docs/dimensions) for react native, but it doesn't give any information regarding zoom either. I could compare the height against the standard height of the device, but to do that I'd need to know all the standard heights of all the iPhones (and eventually Android), and need to constantly update my list of standard heights as new devices come out.

The options used to be Standard and Zoomed (and still are in my simulator), but appear to have changed to Larger Text and Default in the latest iOS update my phone got.

**Comment by mikehardy** [comment]
Looks like you could attempt a PR based on this? https://stackoverflow.com/questions/25952243/how-can-i-detect-whether-a-user-has-an-iphone-6-plus-in-standard-or-zoomed-mode

I'm just searching for strings you are mentioning by the way - and we merge all reasonable PRs - happy to do so in this case, just propose something that works for what you need

**Comment by jkester1986** [comment]
I don't work in native code at all, I honestly wouldn't even know where to begin with this

**Comment by mikehardy** [comment]
I had never touched iOS platform *at all* until I began on a react-native project. We all start somewhere. The objective-c code in this module is some of the most trivial objective-c code there is so it's actually a pretty easy start. Not saying that to be condescending in any way, it's actually a lifesaver for me, I'm terrible at objective-c (and/or swift) but and the simplicity of this code is the only reason I can work on it. Start by reaching right into node_modules and tweaking the code directly. Use https://github.com/ds300/patch-package to save your work. When you get something working post a PR

**Comment by jkester1986** [comment]
great, thanks for the pointers. I will try to find some time to dig into this

**Comment by jkester1986** [comment]
We've opened a PR here: https://github.com/react-native-device-info/react-native-device-info/pull/1495

**Comment by jkester1986** [comment]
hi there @mikehardy , just following up since we hadn't gotten a response on the PR mentioned above
