### ISSUE TITLE
Example app throws errors on JS side. Some function "are not a function"

### ISSUE THREAD

**Issue by shadowsheep1** [react-native-device-info/react-native-device-info#1489]
## Summary

Example app throws errors on JS side.

```
~/Documents/react/react-native-device-info/example (master ✘)✹✭ ᐅ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 80.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.asdf/installs/nodejs/14.17.4/bin/node
    Yarn: 1.22.19 - ~/npm-global/lib/node_modules/yarn/bin/yarn
    npm: 6.14.14 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/shadowsheep/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Current behavior

Cloning the repo (master branch) and running `yarn example:ios` I get `getUniqueIdSync is not a function` error.

<img src="https://user-images.githubusercontent.com/16268789/206858004-ba7d2897-ecc6-4a8f-98d8-6cb7df2bf693.png" width="200" />

This is not only relevant to this function but for all of the ones below:

- `getUniqueIdSync()`
- `DeviceInfo.getBrightnessSync()`
- `DeviceInfo.hasDynamicIsland()` 
- `useBrightness()`

## Expected behavior

Cloning the repo (master branch) and running `yarn example:ios` I should expect to run the example app without any errors.

<img src="https://user-images.githubusercontent.com/16268789/206858319-a26e7677-4285-4b93-abc8-0abd102fc1b2.png" width="200" />

**Comment by mikehardy** [comment]
I did not see any error messages using these run scripts from package.json at top level:

```json
    "example:install": "yarn && cd example && yarn && cd .. && yarn dev-sync",
    "example:install:pods": "cd example/ios && pod install",
    "example:ios": "cd example && yarn ios --simulator 'iPhone 14'",
```

**Comment by shadowsheep1** [comment]
@mikehardy thanks! You're right. I was missing `yarn dev-sync` 

It was my fault not to run all top level scripts for _example_ inside `package.json` , but running all usual yarn commands by hands.
