### ISSUE TITLE
getting `JavaScript execution returned a result of an unsupported type` error

### ISSUE THREAD

**Issue by OrLevy23** [react-native-device-info/react-native-device-info#1493]
## Summary
It appears that only for ios sporadically when we call getUserAgent we get an error `JavaScript execution returned a result of an unsupported type`  for ios only (we had about 30 errors in the last 90 days)
I know that this is relatively old version in compare to what you currently have but when looking at the implementation it appears that this function was not changed
|             |     |
| ----------- | --- |
| Version     | 8.4.8   |
| Affected OS | iOS   |
| OS Version  | 13.3.1 - 16.1   |

**Comment by marcobeltempo** [comment]
I've also been experiencing this error on `10.3.0`.

If [window.navigator.userAgent](https://github.com/react-native-device-info/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L802C26-L802C26) is returning `nil`, we may consider adding a `result != nil` check before resolving the value.
