### ISSUE TITLE
hi ,i am getting 'unknown' for getPhoneNumber(),please give any suggestions /resolutions if any

### ISSUE THREAD

**Issue by geeta87** [react-native-device-info/react-native-device-info#1494]
## Summary

|             |     |
| ----------- | --- |
| Version     | ?   |
| Affected OS | ?   |
| OS Version  | ?   |

**Comment by kesha-antonov** [comment]
Hi
Which platform?

**Comment by geeta87** [comment]
Android

**Comment by kesha-antonov** [comment]
Did you use permission?

https://developer.android.com/about/versions/11/privacy/permissions
