### ISSUE TITLE
Unablle to get Device Info in release mode android

### ISSUE THREAD

**Issue by rahuldev761** [react-native-device-info/react-native-device-info#1497]
Hi, first of all, thanks for creating a such wonderful library. It's awesome. and very easy to use.

I have added this to my one of projects and it's working fine in debug mode. but I am facing one issue when I am creating a release build. I am not getting any info on the device using this. This means it's not working in release mode.

Please help me with this.

**code snip:**
```

import DeviceInfo from 'react-native-device-info';

  const deInfo = {
      brand: DeviceInfo.getBrand(),
      sysVersion: DeviceInfo.getSystemVersion(),
      modal: DeviceInfo.getModel(),
      version: DeviceInfo.getVersion(),
    };
    console.log({deInfo});

```

**details:**
 "react": "17.0.2",
 "react-native": "0.68.2",
 "react-native-device-info": "^8.4.1",

Thanks

## Summary

|             |     |
| ----------- | --- |
| Version     | 8.4.1  |
| Affected OS | android   |
| OS Version  |  android 9,10,11,12,13   |

**Comment by mogulist** [comment]
Same happens to me, too.

**Comment by varemel** [comment]
I have same problem with async method.
Sync method for android solved this bug. For iOS you still need to use async method, because sync is not supported by iOS.
```
export const getUserAgent = () =>
  getSupportedPlatformInfoAsync({
    memoKey: 'userAgent',
    defaultValue: 'unknown',
--->    supportedPlatforms: ['android', 'ios', 'web'],
    getter: () => RNDeviceInfo.getUserAgent(),
  });

export const getUserAgentSync = () =>
  getSupportedPlatformInfoSync({
    memoKey: 'userAgent',
    defaultValue: 'unknown',
--->    supportedPlatforms: ['android', 'web'],
    getter: () => RNDeviceInfo.getUserAgentSync(),
  });
```

final workaround for me is
```
// use sync for android
  let userAgent = Platform.select({
    android: DeviceInfo.getUserAgentSync(), // sync not supported by iOS - supportedPlatforms: ['android', 'web']
    default: await DeviceInfo.getUserAgent(),
  })
```

**Comment by chinnick967** [comment]
We are experiencing this same issue, would appreciate a solution

**Comment by mikehardy** [comment]
There's no code fairy in this repo, sorry - I am able to do releases if someone discovers root cause and posts a PR that appears sensible.

I'd start by seeing if you can reproduce it with the example.

I can tell you that I do not have this problem in my app in release mode at least, so I don't reproduce it.
