### ISSUE TITLE
Even if the name is modified, the result is [iPhone]

### ISSUE THREAD

**Issue by dingsq820** [react-native-device-info/react-native-device-info#1501]
[iPhone13 iOS16.2] For this model of mobile phone, the result obtained by using the getDeviceName method is always [iPhone]. Even if the name is modified, the result is [iPhone]

**Comment by syntheticencounters** [comment]
iOS 16 has a new entitlement that is required before a non-generic device name can be returned. You can apply for this entitlement with Apple using the following link. https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name?language=objc

**Comment by dingsq820** [comment]
Thank you.This is very useful to me.

**Comment by iotashan** [comment]
Yep, the proper solution to this will be noting in the documentation that it's no longer supported with iOS 16 unless this entitlement is granted by Apple... which is difficult to get.

**Comment by syntheticencounters** [comment]
I think the difficulty depends on the use-case. Our particular case was right inline with what Apple allows. The form you have to fill out is short and simple.

**Comment by iotashan** [comment]
I'm going to bet that the vast majority of people using it were doing it for tracking purposes, like I was. We're not being nefarious, we are using it in enterprise apps on iPhones/iPads that we own, manage under MDM, etc. It just helps us track where our own devices are and which of our contractors is using them.

**Comment by syntheticencounters** [comment]
Yeah you may be right. We use the feature in a number of apps to let users manage the devices that have access to their account. I guess you could consider that tracking depending on how you look at it.
