### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by imckain** [react-native-device-info/react-native-device-info#1507]
## Summary
I have tried just about everything and still getting the error:
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
See screenshot below.

|             |     |
| ----------- | --- |
| Version     |  10.4.0   |
| Affected OS | iOS   |
| OS Version  | 15.4  |

## Current behavior

![Screenshot 2023-02-21 at 1 10 35 PM](https://user-images.githubusercontent.com/70352563/220425632-666072c2-d899-4c9c-8e4c-2765444b59ec.png)

Bare workflow React Native
Using Storybook
Cleared all pods, node_modules, and lock files.
Watchman ran, DerivedData cleared. 

I'm trying to use `DeviceInfo.getFontScale()` and get that error. I cannot seem to figure out what's going on.

Here's the simple task I have:

```
const [deviceInfo, setDeviceInfo] = useState<number>();

useEffect(() => {
  try {
    DeviceInfo.getFontScale().then((fontScale) => {
      setDeviceInfo(fontScale);
    });
  } catch (e) {
    // eslint-disable-next-line no-console
    console.log(e);
  }
}, []);

// eslint-disable-next-line no-console
console.log(deviceInfo);
```

As soon as I comment out the method usage, index loads like normal. 

## Expected behavior

Being able to use the methods in this package without errors

**Comment by huyvuskedulo** [comment]
Had the same issue. But it's from the isTablet() method

**Comment by imckain** [comment]
> Had the same issue. But it's from the isTablet() method

Are you using Storybook as well? I'm curious.

**Comment by imckain** [comment]
@guilhermerera that is very odd indeed. Glad to know that you are ***not*** using Storybook. I can at least rule that out. Hopefully, we can get some resolution on this issue by a contributor, as I have not been successful in finding a fix.

**Comment by mikehardy** [comment]
As far as I can tell I'm the only person reliably contributing here and I don't reproduce this myself right now

So if you need a fix you'll have to continue investigating + post a PR as without a reproduction + personal need on my part I don't see any activity happening otherwise

**Comment by imckain** [comment]
@mikehardy Thanks for the reply. I hear you, I will continue to investigate and post my findings here. This is a great package, so it would be nice to get it working in our enterprise solution. If you have any advice on possible origins of an error like this I would appreciate the insight.

**Comment by arifulbgt4** [comment]
I am facing the same issue. Has someone found the solution to this ?

**Comment by kvnlnt** [comment]
I solved this by adding `pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'` to my `Podfile` after seeing that `NativeEventEmitter` is being called correctly in the lib. `RNDeviceInfo` is `null` unless I mapped it.

**Comment by josurene** [comment]
I solved this just running `npx pod-install`

**Comment by RemyNtshaykolo** [comment]
> I solved this just running `npx pod-install`


I needed to delete the app and reinstall it using `react-native run-ios`

**Comment by JestemTrzcinska** [comment]
Terminate metro, close the simulator, pod install and run the app again (npm run ios).
Worked for me

**Comment by mikehardy** [comment]
In my experience @alipatel16 this is what happens when the native module is not installed correctly. And that can frequently happen with folks using Expo (for example) if they don't do `yarn expo prebuild --clean` or similar before `yarn expo ios` (or however they start their native app).

It will not happen in a correctly configured + built/installed app

**Comment by WeiMeng101** [comment]
> > I solved this just running `npx pod-install`
> 
> I needed to delete the app and reinstall it using `react-native run-ios`

thanks

**Comment by LXCGH** [comment]
cd /xxx/ios
rm -rf Pods
rm -rf build
pod install
