### ISSUE TITLE
Deprecated README example update

### ISSUE THREAD

**Issue by Victorywastaken** [react-native-device-info/react-native-device-info#1508]
According to the [README Warning section](https://github.com/react-native-device-info/react-native-device-info#troubleshooting):

The code to suppress the warning is [deprecated](https://reactnative.dev/docs/debugging#logbox) as of React Native 0.63:

![image](https://user-images.githubusercontent.com/35668883/222761851-d048268e-6357-4012-8bbf-cd98560b9553.png)

Proposed change: 

```javascript
import { LogBox } from 'react-native';
LogBox.ignoreLogs(['Battery state']);
```

I can create a PR for this if this issue is approved

**Comment by mikehardy** [comment]
Sure, post a PR
