### ISSUE TITLE
Are there any cases where getAndroidId() fails to fetch Android_ID?

### ISSUE THREAD

**Issue by Yandamuri** [react-native-device-info/react-native-device-info#1513]
I am posting this question here since there is no separate section for posting questions.

I am using `getAndroidId()`  as device unique identifier and it is working as expected . May I know `getAndroidId()` ever fails to fetch `Android_ID` or fetch `null` value?

If so, Any fallback options available?

Thank you.

Note: Kindly guide me if posting questions here is not appropriate.

**Comment by mikehardy** [comment]
https://github.com/react-native-device-info/react-native-device-info#getandroidid

> Gets the ANDROID_ID. See [API documentation](https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID) for appropriate use.

https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID

The documentation seems pretty clear. I'm not aware of any cases that are contrary to the documentation, you'll have to read it and deduce yourself
