### ISSUE TITLE
`lowPowerMode` from `getPowerState()` always return false [Xiaomi only]

### ISSUE THREAD

**Issue by rachitdua** [react-native-device-info/react-native-device-info#1514]
When using `getPowerState()` method, the value of `lowPowerMode` is always returned as false. On digging deeper, it happens because Xiaomi uses a system setting `POWER_SAVE_MODE_OPEN` for power saving mode, not the powerManager.

## Summary

|             |     |
| ----------- | --- |
| Version     | <= 10.4.0 |
| Affected OS | Android   |
| OS Version  | All |

## Current behavior

The `lowPowerMode` in `getPowerState()` always returns false for Xiaomi devices.

## Expected behavior

It should return the value of the low power mode as it is changed.

**Comment by mikehardy** [comment]
PRs happily accepted, otherwise this will likely sit.

**Comment by ZeroLTV** [comment]
i am also getting this error

**Comment by mikehardy** [comment]
Fantastic if you reproduce the error @ZeroLTV ! That's most of the way to fixing it.


PRs happily accepted, otherwise this will likely sit.
