### ISSUE TITLE
Invalid ID in getUniqueId in iOS devices after migration

### ISSUE THREAD

**Issue by moshekrush** [react-native-device-info/react-native-device-info#1526]
## Generating the UID for iOS devices does not work properly. When a user migrate between devices the device UID remains the same, though it's a new device. 

|             |     |
| ----------- | --- |
| Version     | 10.5.1  |
| Affected OS | iOS |
| OS Version  | 6+ |

## Current behavior

When calling the `getUniqueId` method the UID calculation in iOS devices looks for the UIDKey in the keychain and uses it if exists. However, when storing the UIDKey, it is saved with the `kSecAttrAccessibleAfterFirstUnlock` attribute instead of the `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`.
When using [kSecAttrAccessibleAfterFirstUnlock](https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlock?language=objc) the value will be present after migration, hence making it not uniqued per device. 
If it would be saved using [kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly](https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlockthisdeviceonly?language=objc) then it would not be passed upon migration. In Apple's words:
_Thus, after restoring from a backup of a different device, these items will not be present._

## Expected behavior

Upon migration, the `getUniqueId` method should generate a new ID(according to your code the IDFV) and not keep the one from the old device. 

## Suggested fix
Change the `CFStringRef` to `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` instead of `kSecAttrAccessibleAfterFirstUnlock`

**Comment by mikehardy** [comment]
It appears this case was considered and may be the reason for `syncUniqueId`? https://github.com/react-native-device-info/react-native-device-info#syncuniqueid

Your argument appears correct though, android does not have the possibility of being the same across multiple devices so this represents a platform-difference.

It would be a breaking change, but likely a welcome one. I'm happy to issue breaking changes so long as they have good release notes (which I can ensure)

If you raise a PR for this I can get it merged + released

**Comment by carlbleick** [comment]
@moshekrush I'm having the same issue, did you resolve it by using `syncUniqueId`? Or did you patch the lib and use `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` (as you recommended initially)?

**Comment by carlbleick** [comment]
@moshekrush Thanks for replying! How did you handle existing devices? Did you have to reset the devices in some way or did the affected devices managed it automatically?

**Comment by moshekrush** [comment]
IIRC it doesn't happen automatically

**Comment by carlbleick** [comment]
@moshekrush Oh okay, how did you solve it for already affected devices then? Or did you notice the bug before encountering it in prod?
