### ISSUE TITLE
Support for useBatteryLevel & useBatteryLevelIsLow is missing in windows

### ISSUE THREAD

**Issue by sohail-p** [react-native-device-info/react-native-device-info#1528]
## Summary
Support for Hook useBatteryLevel & useBatteryLevelIsLow is not available on windows platform

|             |     |
| ----------- | --- |
| Version     | 10.4.0 |
| Affected OS | Windows |
| OS Version  |11|

## Current behavior

Support for Hook **useBatteryLevel**, **useBatteryLevelIsLow**, event **RNDeviceInfo_batteryLevelDidChange** & **useBatteryLevel & useBatteryLevelIsLow** is not available on windows platform, Have checked the code and found that this event is not subscribed in windows

## Expected behavior

We should be get event **RNDeviceInfo_batteryLevelDidChange** & **useBatteryLevel & useBatteryLevelIsLow** on windows platform too

**Comment by rahulsbaviskar** [comment]
Finally someone added these for windows, have been waiting for these since long... @mikehardy when can this be release?
