### ISSUE TITLE
getManufacturerSync method throws Invariant Violation error when debugging

### ISSUE THREAD

**Issue by BrentWardOx** [react-native-device-info/react-native-device-info#1531]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.5.1   |
| Affected OS | Android   |
| OS Version  | 11   |

## Current behavior

In my React Native app, I have the following code:

```
import DeviceInfo from 'react-native-device-info';

const manufacturer = DeviceInfo.getManufacturerSync();
```

I am able to call this code just fine! It works great under normal conditions.

However, this code throws an error whenever I start debugging via the `React Native DevMenu (Bridge)`.

![image](https://user-images.githubusercontent.com/90654819/231215996-5a2219ba-ff3c-472c-a692-0769b4048c0c.png)

This method throws the following two errors:

`Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.`
`Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication).`

Screenshot of errors:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/90654819/231216636-c0bacc01-c193-48b2-8f4f-9b8cf6a4cc64.png">

I verified that the line `const manufacturer = DeviceInfo.getManufacturerSync();` is what throws these errors. Once these errors are thrown, the app is rendered unable to continue.

## Expected behavior

The `DeviceInfo.getManufacturerSync` method should not throw errors when debugging in React Native.

**Comment by johhansantana** [comment]
happens to me with the `getUniqueIdSync` function. only when using debug mode

**Comment by mikehardy** [comment]
@johhansantana ...and that's because sync functions are not allowed in the react-native bridge / debugger. So, don't do that is all that can be said - it is not technically possible to do it as the debugger is async

**Comment by johhansantana** [comment]
@mikehardy yeah, figured it out from other issues. Luckily we use reactotron most of the time for debugging. 👍
