### ISSUE TITLE
getUniqueId always returns unknown

### ISSUE THREAD

**Issue by JoergTiedemann** [react-native-device-info/react-native-device-info#1532]
In my react app I've added react-native and also react-native-device-info
But I can't build I got a message that react-native is required and no module found
than I added react-native-web and I can build, but if I call DeviceInfo.getUniqueId on in a windows edge browser I always get unknown as the device Id.
What is going wrong or in other words what could the reason ?

**Comment by sohail-p** [comment]
Hi @JoergTiedemann if you look at the [API Table](https://github.com/react-native-device-info/react-native-device-info#api), you would see that getUniqueId() is not supported in Web, hence you might be getting it as unknown
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Sohail/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Sohail/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Method | Return Type | iOS | Android | Windows | Web
-- | -- | -- | -- | -- | --
getUniqueId() | Promise<string> | ✅ | ✅ | ✅ | ❌
  |   |   |   |   |  



</body>

</html>

**Comment by JoergTiedemann** [comment]
oh sorry 
I didn't see the column Web just ios Android Windows
but this means it will not work in a react web app under ios safari ?
Is there any other way to get a unique device id in a react web site ?
