### ISSUE TITLE
Missing API specifications for getUniqueIdSync

### ISSUE THREAD

**Issue by SamMcDuffie** [react-native-device-info/react-native-device-info#1538]
## Description
The [API](https://github.com/react-native-device-info/react-native-device-info#api) section of the `README.md` does not include details about `getUniqueIdSync` which I feel would be beneficial.

**Comment by julian-dotcom** [comment]
This should be added to the README in my opinion.

**Comment by johhansantana** [comment]
anyone knows the differences between `getUniqueIdSync` and `getUniqueId` apart from it being synchronous ?

**Comment by mikehardy** [comment]
No, the sync and async methods are always connected and equivalent except the sync/async difference. They delegate to each other even, such that the implementation is usually singular
