### ISSUE TITLE
Free Space is varied by around 300MB

### ISSUE THREAD

**Issue by amruth-k** [react-native-device-info/react-native-device-info#1559]
Incorrect Storage shown from the [react-native-device-info](https://github.com/react-native-device-info/react-native-device-info) from both iOS and Android.
The difference is around 300-350 MB.

## Summary

|             |     |
| ----------- | --- |
| Version     | 10.3.0   |
| Affected OS | Android/iOS   |
| OS Version  | 11   |

## Current behavior

Free space shown in in-built file manager: 41.17GB

Free space shown from [react-native-device-info](https://github.com/react-native-device-info/react-native-device-info) : 41.4 GB

## Expected behavior

Ideally, they both should be same.

Please let me know if this is a limitation or any solution for this.

**Comment by thatgriffith** [comment]
This issue seems to be related (with a solution for iOS)
https://github.com/react-native-device-info/react-native-device-info/issues/1148#issuecomment-764748934

**Comment by amruth-k99** [comment]
@thatgriffith I observed this issue in Android mostly
