### ISSUE TITLE
isTablet() identifies opened fold phones as tablets

### ISSUE THREAD

**Issue by VoidBGS** [react-native-device-info/react-native-device-info#1560]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.8.0 |
| Affected OS | HarmonyOS |
| OS Version  | 3 |

## Current behavior
When starting my application with an unfolded Huawei fold phone, the library identifies it as a tablet. This causes issues with the logic of my application and makes it harder for me to determine if a device is a tablet or a fold phone. I have two different designs for tablets and phones. When I fold the phone, the isTablet() function still returns falsely that the phone is a tablet.

## Expected behavior
`isTablet()` function should not recognize fold phones as tablets, or if it does, it should be dynamic and it should recognize when the fold phone is no longer folded.

**Comment by mikehardy** [comment]
It appears isTablet is currently a constant in the android code:

https://github.com/react-native-device-info/react-native-device-info/blob/d73b01af2640417fe35c5afa4913ce46237f6cdf/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L202C1-L202C1

This would be a breaking change but may be a necessary one.

You would want to remove isTablet from constants, and instead have calls to it on android resolve dynamically each time

It may be possible to do a non-breaking thing where you add an isFoldable to the constants (detecting it however you need to based on Android internals - there must be something on stackoverflow...) and then implement the currently windows-only method isTabletMode for android as well, such that it is false if display metrics indicate it's currently folded and in phone mode or unfolded and in tablet mode

Reasonable PRs accepted

**Comment by thomasdierickx** [comment]
Has there been a fix for this issue?
