### ISSUE TITLE
getCarrier Not Working on iOS

### ISSUE THREAD

**Issue by baranngungor** [react-native-device-info/react-native-device-info#1561]
## Summary

GetCarrier deprecated on iOS 16.4 and newer. Now i'm getting "--" when run getCarrier.

|             |     |
| ----------- | --- |
| Version     | 10.8.0 |
| Affected OS | iOS |
| OS Version  | 16.5.1 |

## Current behavior

Package Getting "--" on iOS

## Expected behavior

It should get the carrier name

**Comment by mikehardy** [comment]
If you post a PR that solves the issue we can merge it

**Comment by baranngungor** [comment]
@mikehardy I was using your package for SIM Card Signal. API you using in package is deprecated on iOS.

**Comment by mikehardy** [comment]
If you post a PR that solves the issue, we can merge it

**Comment by baranngungor** [comment]
No, API deprecated as I said and the API has no alternative for get Carrier name. If there was an alternative, I would do it, you can be sure :)

**Comment by Noah-Access** [comment]
I am facing this issue as well. Any workaround for this?
