### ISSUE TITLE
isEmulator() is not detecting the MEMU emulator

### ISSUE THREAD

**Issue by GaneshGK34** [react-native-device-info/react-native-device-info#1562]
DeviceInfo?.isEmulator() working fine android studio emulator, But in memu emulator It is not working.

**Comment by EzzineSmichi** [comment]
also for me i detect this problem, there is any solution ?

**Comment by mikehardy** [comment]
Please feel free to extend the isEmulator method in a PR with whatever is necessary to detect your emulator
