### ISSUE TITLE
Question about Behaviour of getUniqueId() on Android

### ISSUE THREAD

**Issue by SeanCandon** [react-native-device-info/react-native-device-info#1567]
## Summary

|             |     |
| ----------- | --- |
| Version     | 5.4.3 |
| Affected OS | Android |
| OS Version  | ?   |

## Current behavior

 
Hi there. Not really a bug but more of a question about what we're occasionally seeing from `getUniqueId()`. This could well be that we're on an old version and updating will sort it. 

Our use case is we're trying to do some fraud detection for registrations on our app. One of the pieces of data we're using is a unique identifier for the device. For the most part, these IDs are coming in fine using `getUniqueId()` (e.g `FCDBD8EF-62FC-4ECB-B2F5-92C9E79AC7F9` for iOS and `dd96dec43fb81c97` for android), but occasionally for Android registrations we're only getting back a more general id related to the manufacturer. Examples include `exynos7870`, `s5e9925` and `a14xm`. We're wondering what could potentially cause this to happen?

**Comment by mikehardy** [comment]
That is quite odd, I wouldn't expect that. Here's the code, it just reaches in and grabs something compiled by the manufacturer, so perhaps they are making it impossible to grab this non-resettable user identifier for privacy reasons:

https://github.com/react-native-device-info/react-native-device-info/blob/d73b01af2640417fe35c5afa4913ce46237f6cdf/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L810

You can see it's not fancy, just a one-liner.

You might try using async-storage and a locally generated random ID, in android terms that's https://developer.android.com/training/articles/user-data-ids#instance-ids-guids - but you can do similar in react-native via javascript with a "check for existing GUID / generate one and store it if it doesn't exist / verify GUID"

Or you can use `@react-native-firebase/installations` as they indicate

No comment on whether any of these strategies will work at all or work well for your use case, just thinking at the code level about how it could happen, how you could possible work around
