### ISSUE TITLE
hasDynamicIsland not returning true for iphone 15 devices

### ISSUE THREAD

**Issue by jfurdock** [react-native-device-info/react-native-device-info#1578]
## Summary
Update HasDynamicIsland device array to include latest devices

|             |     |
| ----------- | --- |
| Version     | ?   |
| Affected OS | ?   |
| OS Version  | ?   |

## Current behavior

const HAS_DYNAMIC_ISLAND = DeviceInfo.hasDynamicIsland();

HAS_DYNAMIC_ISLAND is returned false on Iphone 15 Pro Max device

## Expected behavior

const HAS_DYNAMIC_ISLAND = DeviceInfo.hasDynamicIsland();

HAS_DYNAMIC_ISLAND should return true on Iphone 15 Pro Max device

**Comment by mikehardy** [comment]
@mertcankose "same issue" is not a valid comment in an open source context. A PR is the path forward

**Comment by mertcankose** [comment]
> @mertcankose "same issue" is not a valid comment in an open source context. A PR is the path forward

sorry i forgot to upgrade the package. it's solved
