### ISSUE TITLE
isDisplayZoomed always returns true

### ISSUE THREAD

**Issue by idlework** [react-native-device-info/react-native-device-info#1581]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.4.0 - 10.11.0 |
| Affected OS | iOS |
| OS Version  |16.6|

## Current behavior

Logging the result value from the function `isDisplayZoomed` on an iOS device always results in the value `true`.
Logging the result value on a simulator always results in false. This is because there is no display zoom support on the simulator.

I believe the value should change if you adjust the `Display Zoom` found in the settings `Display & Brightness` -> `Display Zoom` and switch between `Default` and `Larger Text`

## Expected behavior

`Display Zoom` with value `Default`:
Result value from `isDisplayZoomed` on an iOS device should be `false`.

`Display Zoom` with value `Larger Text`:
Result value from `isDisplayZoomed` on an iOS device should be `true`

## Needed for
This feature is useful to detect if the user is zooming their screen. If the function works correctly, we can optimize the UI for the user.

**Comment by Kowaio** [comment]
Hi guys,
Got the same issue on simulator with latest version.
It works great on iPhone 15 Pro Max, isDisplayZoomed() currently returns the good value.
Although, on iPhone 13 mini, isDisplayZoomed() always returns true.
Is there a fix somewhere about this?
Thanks!

**Comment by mikehardy** [comment]
Sounds like you've got the hardware available that would allow for inspection and a PR - we could merge a fix easily

**Comment by Kowaio** [comment]
My bad, its on simulator, i dont have these devices but its doing that only with this one iPhone 13 mini 17.2
