### ISSUE TITLE
 Error: react-native-device-info: NativeModule.RNDeviceInfo is null

### ISSUE THREAD

**Issue by durejagaurav** [react-native-device-info/react-native-device-info#1583]
Error: react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  
  Did all things. But still facing the same issue.

I am using:

    "react-native": "0.72.6",
    "react-native-device-info": "^10.11.0",

Getting error on ios build

**Comment by mikehardy** [comment]
Do not log duplicate issues please #1558
This is a local problem in your integration and not a problem with this repository - it is not actionable here, it will not result in any change in the code here, and is thus closed.
