### ISSUE TITLE
upgrading to googlePlayServicesVersion 21.0.1 

### ISSUE THREAD

**Issue by trne** [react-native-device-info/react-native-device-info#1584]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-device-info@10.11.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-device-info/android/build.gradle b/node_modules/react-native-device-info/android/build.gradle
index feb9f0d..56ba0ff 100644
--- a/node_modules/react-native-device-info/android/build.gradle
+++ b/node_modules/react-native-device-info/android/build.gradle
@@ -65,7 +65,7 @@ dependencies {
   } else if(firebaseIidVersion){
       implementation "com.google.firebase:firebase-iid:${firebaseIidVersion}"
   }else{
-      def iidVersion = safeExtGet('googlePlayServicesIidVersion', safeExtGet('googlePlayServicesVersion', '17.0.0'))
+      def iidVersion = safeExtGet('googlePlayServicesIidVersion', safeExtGet('googlePlayServicesVersion', '21.0.1'))
       implementation "com.google.android.gms:play-services-iid:$iidVersion"
   }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mikehardy** [comment]
The problem with this is that IID hasn't been released since 17.0.0, so this could lead to an invalid iid dependency
https://mvnrepository.com/artifact/com.google.android.gms/play-services-iid
So this is invalid
