### ISSUE TITLE
':react-native-device-info:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by PravinNashte** [react-native-device-info/react-native-device-info#1593]
## Summary

|             |     |
| ----------- | --- |
| Version       | [10.12.0] [10.11.0] 
| Affected OS   | Android 
| OS Version     | sdk 33

## Current behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-device-info:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/pravinnashte/Library/Android/sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /Users/pravinnashte/Library/Java/JavaVirtualMachines/openjdk-21.0.1/Contents/Home/bin/jlink with arguments {--module-path /Users/pravinnashte/.gradle/caches/transforms-3/47e305173a08682f911db0c5055580c3/transformed/output/temp/jmod --add-modules java.base --output /Users/pravinnashte/.gradle/caches/transforms-3/47e305173a08682f911db0c5055580c3/transformed/output/jdkImage --disable-plugin system-modules}

## Expected behavior

it works on iOS but not working on android while running on metro

**Comment by mikehardy** [comment]
If you read the error carefully you'll notice this module has nothing to do with your problem, so your issue is misplaced here.

What you really want is to not use JDK21. You will have to use JDK17 until android gradle plugin 8.2.1 is released, see: https://issuetracker.google.com/issues/294137077
