### ISSUE TITLE
ID of the CellTower in use

### ISSUE THREAD

**Issue by Krelyshy** [react-native-device-info/react-native-device-info#1594]
## Description

I would love to have a method that would get the ID of currently used mobile network celltower.

Should be related to https://developer.android.com/reference/android/telephony/TelephonyManager#getAllCellInfo()

## Use Case

Displaying information/interacting with users depending on their location, which in some cases can be obtained immediately by using a known cell ID.

**Comment by Krelyshy** [comment]
Or maybe https://github.com/mroczis/netmonster-core could be used?

**Comment by mikehardy** [comment]
I'd prefer not to have a new dependency if possible
We are over minSdkVersion 17 so the API you cite is available

If you implemented that and returned a reasonable JSON tree of info representing all the stuff that came back that seems reasonable. Might be more reasonable in react-native-netinfo (where you'll meet me again, I'm the main maintainer over there as well at the moment...)

**Comment by Krelyshy** [comment]
Indeed it makes more sense to implement it in netinfo. See you there!
