### ISSUE TITLE
Apple privacy manifest file 

### ISSUE THREAD

**Issue by AntonyARHS** [react-native-device-info/react-native-device-info#1596]
Hi,

I would like to ask a question regarding the new permission file from Apple: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

As we don't know what APIs are used internally in your library, could you confirm whether or not you will be managing the new permission file required by Apple? If you have to handle it, do you have an ETA?

Thank you very much,

**Comment by mikehardy** [comment]
I don't provide ETAs, no one in open source should
You do know what APIs are used internally because it's open source, you may inspect the repository

**Comment by AntonyARHS** [comment]
Hello, 

Sorry, I didn't think to adapt my message. It was a copy and paste of a request made to another non-open source SDK. 

So I understand that there are no open points on this subject yet, thank you. I'll have a look later on!

**Comment by AntonyARHS** [comment]
Hello,

Sorry, I didn't think to adapt my message. It was a copy and paste of a request made to another non-open source SDK.

So I understand that there are no open points on this subject yet, thank you. I'll have a look later on!

**Comment by LydGol90** [comment]
In case it helps anyone I have been reviewing this for the apis we use in our app and only found two that use "required reason apis" from Apple

getFreeDiskStorage --> NSFileSystemSize
getUniqueIdSync --> NSUserDefaults

**Comment by mikehardy** [comment]
@LydGol90 note that you can always use patch-package to simply purge those from the module and not have them show up or need handling...

**Comment by taylorkline** [comment]
Related: #1624
