### ISSUE TITLE
when use getMacAddress get a null value

### ISSUE THREAD

**Issue by DowCore** [react-native-device-info/react-native-device-info#1597]
when use getMacAddress get null

## Summary

|             |     |
| ----------- | --- |
| Version     | 10.12  |
| Affected OS |  android |
| OS Version  | android 11 or up   |

**Comment by mikehardy** [comment]
likely missing permissions stated in the documentation https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#getmacaddress

Definitely missing information required for anyone to help https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example
