### ISSUE TITLE
Docs are not correct regaring getUniqueId

### ISSUE THREAD

**Issue by EJohnF** [react-native-device-info/react-native-device-info#1606]
It's regarding this functions https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#getuniqueid

>  Once UID is generated it is stored in iOS Keychain and NSUserDefaults. So it would stay the same even if you delete the app or reset IDFV. You can carefully consider it a persistent, cross-install unique ID. It can be changed only in case someone manually override values in Keychain/NSUserDefaults or if Apple would change Keychain and NSUserDefaults implementations. Beware: The IDFV is calculated using your bundle identifier and thus will be different in app extensions.

But this is not true. App re-install changes this value. And it's also written in the apple docs. 

> The value in this property remains the same while the app (or another app from the same vendor) is installed on the iOS device. The value changes when the user deletes all of that vendor’s apps from the device and subsequently reinstalls one or more of them. The value can also change when installing test builds using Xcode or when installing an app on a device using ad-hoc distribution. Therefore, if your app stores the value of this property anywhere, you should gracefully handle situations where the identifier changes.

So, I think docs needs to be updated to not confuse people.

**Comment by mikehardy** [comment]
PRs happily accepted 🙏
