### ISSUE TITLE
Android app crashing on start-up due to NullPointerException at com.android.installreferrer.api.onServiceConnected

### ISSUE THREAD

**Issue by jwhenshaw** [react-native-device-info/react-native-device-info#1607]
## Summary

Experiencing app crashes only with APKs from downloaded and installed from Google Play Store on physical devices only.

Apologies in advance as this initial bug report is going to be a bit bare bones in the hopes of being pointed in the right direction to help provide what's needed to fix.

|             |     |
| ----------- | --- |
| Version     | ^10.12.0   |
| Affected OS | android   |
| OS Version  | 11   |

## Current behavior

On start-up of the app it crashes with the following error

```
java.lang.NullPointerException
	at com.android.installreferrer.api.b$b.onServiceConnected(SourceFile:24)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2207)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2240)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

## Expected behavior

Crash free

## Additional information

I've confirmed that removing this package from my application prevents the crash from happening.

I am also not attempting to use any install referrer utils here.

`react-native version 0.73.3`

### Pro-guard - not related

Pro-guard is enabled in my application however, disabling this does not fix the issue nor is it fixed by following the pro-guards steps within the README.

### Build Gradle/dependency

I've also explicitly attempted to explicitly include the dependency for `com.android.installreferrer:installreferrer` (versions ^1.1.1 and ^2.2) to no avail.

-----

Thanks in advance, I am going to continue trying to nail down the exact root cause but in the meantime appreciate any help.

**Comment by jwhenshaw** [comment]
From poking around in the code it may be (really not sure...) that the [React Context provided](https://github.com/react-native-device-info/react-native-device-info/blob/116291a7362fe262a58230f5760eb2853e34e541/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L92) is null 
```
this.installReferrerClient = new RNInstallReferrerClient(reactContext.getBaseContext());
```

and then when the [listener is registered](https://github.com/react-native-device-info/react-native-device-info/blob/116291a7362fe262a58230f5760eb2853e34e541/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java#L58) and called we get the null pointer exception
```
  // Create the InstallReferrerStateListener instance using a Proxy.
  installReferrerStateListener = Proxy.newProxyInstance(
      InstallReferrerStateListenerClazz.getClassLoader(),
      new Class[]{InstallReferrerStateListenerClazz},
      new InstallReferrerStateListenerProxy());

  // Call startConnection on the client instance.
  Method startConnectionMethod = InstallReferrerClientClazz.getMethod("startConnection", InstallReferrerStateListenerClazz);
  startConnectionMethod.invoke(mReferrerClient, installReferrerStateListener);
```

Why the react context would be null I'm not sure - perhaps I'm following the wrong trail of breadcrumbs here

**Comment by mikehardy** [comment]
Having a null ReactContext is actually a really frustrating but common crash root cause in react-native. It has to do with the asynchronous nature of the native/JS bridge, and that the main react-native "Activity" can go away any time while the "Application" is still there (with your code, that still thinks it has a valid Activity with a valid ReactContext).

The native modules run in the Application context if I understand correctly, not the Activity context, so your code can still execute later but the Activity (with it's context) are gone and poof you get an NPE and a crash

Any use of ReactContext should have a null-safety guard around it

If you null-checked the ReactContext and just put a Log warning in there in case it's null then continued along as best you can in that case and posted that as a PR, that may be as good as it gets for a solution

**Comment by jwhenshaw** [comment]
Thanks, makes sense.

I am going to try get a PR up asap - having no luck being able to link the package in order to test locally as of yet however.
