### ISSUE TITLE
[Feature] Request device date and time automatically is enabled or disabled

### ISSUE THREAD

**Issue by chanphiromsok** [react-native-device-info/react-native-device-info#1609]
- get device date and time automatically enabled or disabled from setting

**Comment by mikehardy** [comment]
@chanphiromsok please search

https://github.com/react-native-device-info/react-native-device-info/issues?q=is%3Aissue+automatic+date+time

Not going to happen

https://github.com/react-native-device-info/react-native-device-info/issues/423#issuecomment-526336895

Use react-native-localize
Please search before opening issues, thank you

**Comment by chanphiromsok** [comment]
> @chanphiromsok please search
> 
> https://github.com/react-native-device-info/react-native-device-info/issues?q=is%3Aissue+automatic+date+time
> 
> Not going to happen
> 
> [#423 (comment)](https://github.com/react-native-device-info/react-native-device-info/issues/423#issuecomment-526336895)
> 
> Use react-native-localize Please search before opening issues, thank you

thank for information
