### ISSUE TITLE
Problem with submitting application to Google Play because of the usage of getLine1Number inside the library

### ISSUE THREAD

**Issue by alexkutsko** [react-native-device-info/react-native-device-info#1612]
## Summary
The issue lies in the utilization of TelephonyManager.getLine1Number() within the library's code ([accessible via this link](https://github.com/react-native-device-info/react-native-device-info/blob/e46a5d4dba4e7d1f5e1da8b17c82829600f84d77/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L919)).

The problem stems from receiving notifications from Google for several applications we are developing, prompting the implementation of Prominent Disclosure. This requirement arises due to the inclusion of this function within the codebase. We speculate that Google flags this through static code analysis. The issue surfaced during Google Play's application verification process, where Google's automated systems detected the function's presence. Despite not actively collecting phone numbers, the function's existence necessitates a Prominent Disclosure and a revision of our data collection policies. Attempting to address this, we forked the code and successfully published a version devoid of this function.

Consequently, we propose offering a version of the library without this function. Notably, the getLine1Number function is deprecated, and alternative methods for retrieving phone numbers from SIM cards are recommended. However, access to phone number retrieval typically requires specific "carrier" permissions or designation as the default "SMS application." Thus, we believe retaining this function may hinder the seamless publication of many applications with react-native-device-info library inside on Google Play.

| | |
|-----|---|
| Version | All versions |
| Affected OS | Android |

**Comment by mikehardy** [comment]
Indeed, as the platforms become more privacy-oriented there aren't that many good ways to handle this. The ideal way is to perhaps split the project in to sub-modules but that's a difficult user experience and a difficult maintainer experience.

However, for the telelphony APIs specifically, we're in luck as there appears to be a library that looks currently maintained and handles things better then we do already: https://github.com/odemolliens/react-native-sim-cards-manager

If you proposed a PR that removes the all telephony features that are present in react-native-sim-cards-manager we can issue a breaking change release that no longer has them here
