### ISSUE TITLE
v10.13.0 import of `UIUserInterfaceIdiomVision` breaks Expo builds

### ISSUE THREAD

**Issue by BrianLi101** [react-native-device-info/react-native-device-info#1616]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.13.0   |
| Affected OS | Expo Builds on iOS   |
| OS Version  | iOS 13.4 |

## Current behavior

For Expo builds, the importing of `UIUserInterfaceIdiomVision` in version `10.13.0` breaks Expo builds with the following error:
```
❌  (../node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:137:14)

  135 |         case UIUserInterfaceIdiomTV: return DeviceTypeTv;
  136 |         case UIUserInterfaceIdiomMac: return DeviceTypeDesktop;
> 137 |         case UIUserInterfaceIdiomVision: return DeviceTypeHeadset;
      |              ^ use of undeclared identifier 'UIUserInterfaceIdiomVision'; did you mean 'UIUserInterfaceIdiomPhone'?
  138 |         default: return DeviceTypeUnknown;
  139 |     }
  140 | }

❌  (../node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:137:14)

  135 |         case UIUserInterfaceIdiomTV: return DeviceTypeTv;
  136 |         case UIUserInterfaceIdiomMac: return DeviceTypeDesktop;
> 137 |         case UIUserInterfaceIdiomVision: return DeviceTypeHeadset;
      |              ^ duplicate case value 'UIUserInterfaceIdiomPhone'
  138 |         default: return DeviceTypeUnknown;
  139 |     }
  140 | }
```

## Solution
We are deprecating to version `10.12.1` for now

**Comment by theJustinCase** [comment]
Ran into the same issue, reverting to `10.12.1` did the trick for now.  Using Expo@49.

**Comment by johnf** [comment]
This breaks Xcode builds too

**Comment by VadymBezsmertnyi** [comment]
I also encountered an issue today:
Build failed: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

Log:
`Mon, 26 Feb 2024 08:09:24 GMT
› Compiling react-native-device-info Pods/RNDeviceInfo » RNDeviceInfo.m
Mon, 26 Feb 2024 08:09:24 GMT
❌  (node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:137:14)
  135 |         case UIUserInterfaceIdiomTV: return DeviceTypeTv;
  136 |         case UIUserInterfaceIdiomMac: return DeviceTypeDesktop;
> 137 |         case UIUserInterfaceIdiomVision: return DeviceTypeHeadset;
      |              ^ use of undeclared identifier 'UIUserInterfaceIdiomVision'; did you mean 'UIUserInterfaceIdiomPhone'?
  138 |         default: return DeviceTypeUnknown;
  139 |     }
  140 | }

Mon, 26 Feb 2024 08:09:24 GMT
❌  (node_modules/react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:137:14)
  135 |         case UIUserInterfaceIdiomTV: return DeviceTypeTv;
  136 |         case UIUserInterfaceIdiomMac: return DeviceTypeDesktop;
> 137 |         case UIUserInterfaceIdiomVision: return DeviceTypeHeadset;
      |              ^ duplicate case value 'UIUserInterfaceIdiomPhone'
  138 |         default: return DeviceTypeUnknown;
  139 |     }
  140 | }`
  
 @theJustinCase Downgrading react-native-device-info to version 10.12.1 also did not yield any results.

**Comment by VadymBezsmertnyi** [comment]
@theJustinCase
Sorry. Downgrading the version of "react-native-device-info" to "10.12.1" helped me.
The first time I didn't delete node_modules.

**Comment by mikehardy** [comment]
Perfect timing - github workflows don't seem to be triggering right now so I can't run the release. There was a similar outage last Wednesday though status currently isn't showing a problem. I'll keep trying to release it and leave this open until it works https://www.githubstatus.com/history

**Comment by mikehardy** [comment]
github appears to be working well again, again closing, I think it's fixed, can reopen if wrong...
