### ISSUE TITLE
Error starting expo

### ISSUE THREAD

**Issue by lcdevelopersmx2024** [react-native-device-info/react-native-device-info#1618]
ERROR  Error: react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
  • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
  • Rebuild and re-run the app.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
  If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-device-info/react-native-device-info, js engine: hermes

This just importing 
import DeviceInfo from 'react-native-device-info';

"@react-native-community/netinfo": "^11.3.1",
"expo": "^50.0.7",
"react": "18.2.0",

**Comment by mikehardy** [comment]
> NativeModule.RNDeviceInfo is null.

This means "I installed your module and I have it's javascript running in the bundle, but I haven't correctly build and installed the native code"

You need to correctly build and install the native part of the module, however you do that in Expo terms.

Not a bug in this library, bug in project setup / install / execution.
