### ISSUE TITLE
RNDeviceInfo is null on Android and react-native

### ISSUE THREAD

**Issue by Kohlroulade** [react-native-device-info/react-native-device-info#1625]
## Summary

|             |     |
| ----------- | --- |
| Version     | 10.13.1   |
| Affected OS | Android   |
| OS Version  | 10   |

## Current behavior

Running expo using `npx expo start`. Start app on my smartphone. Get following error:

> ERROR  Error: react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
>   • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
>   • Rebuild and re-run the app.
>   • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
>   If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-device-info/react-native-device-info, js engine: hermes
>  ERROR  Invariant Violation: "main" has not been registered. This can happen if:
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

## Expected behavior

App should start on smartphone

I am using react-native 0.73.4

**Comment by GemsGame** [comment]
the same issue

**Comment by rahulinaction** [comment]
Facinig the same issue

**Comment by rahulinaction** [comment]
As added in the Readme there is possibly manual linking done in your project. Try to get rid of the includes and try installing module followed by pod install. That did the trick for me

**Comment by Kohlroulade** [comment]
> As added in the Readme there is possibly manual linking done in your project. Try to get rid of the includes and try installing module followed by pod install. That did the trick for me

Eeeeehm, I didn't implement any linking, and from the README I guess this is done automatically as of react-native >0.59. Apart from this I don't use CocoaPods nor have I any pod-file.

**Comment by rethink-alexandrejunior** [comment]
the same issue, somebody ? 

<img width="1249" alt="Captura de Tela 2024-03-28 às 18 39 39" src="https://github.com/react-native-device-info/react-native-device-info/assets/102677257/16b87528-8c9b-4ea9-9e9b-1201ae4a0b7f">

**Comment by Larry-Schultz** [comment]
Also experiencing this issue.

I'm using React version `0.73.6` and I'm not using CocoaPods.  What am I supposed to do to resolve this issue?

**Comment by pnthach95** [comment]
react-native: 0.73.7
react-native-device-info: 10.13.2

Reproducer: https://github.com/pnthach95/applicationIdError

https://github.com/react-native-community/cli/assets/31266357/81d10c18-c5ac-407b-af80-18268c3412da

**Comment by mikehardy** [comment]
@rethink-alexandrejunior 

> the same issue, somebody ?

"the same issue" - you all realize you have like 3 issues all mixed on this one thread?  It shows an inattention to detail when the issues are clearly different - reading was not performed 👀 

> <img alt="Captura de Tela 2024-03-28 às 18 39 39" width="1249" src="https://private-user-images.githubusercontent.com/102677257/317890140-16b87528-8c9b-4ea9-9e9b-1201ae4a0b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDI5NjUsIm5iZiI6MTcxNTgwMjY2NSwicGF0aCI6Ii8xMDI2NzcyNTcvMzE3ODkwMTQwLTE2Yjg3NTI4LThjOWItNGVhOS05ZTliLTEyMDFhZTRhMGI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxOTUxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzhmZWE4NjliZjUyYTc2MzRlMzdiNTliOTczOTg2MGQxNjdkYWY1NDM3NjcxZDZkZWNhNjE0MzFmODdiYjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bFJq-_p7bibRmETISxS2UjmZNYhZpmmaCQB8A3PyEgA">

@rethink-alexandrejunior that looks like unit tests, and you are likely missing a mock implementation - I believe one is shipped with this package for this package


Separately:

- Expo issue - I don't use expo, expo people will have to figure that out

And finally:

- @pnthach95 it works in CI, it works in my apps, you have some project-specific problem. What it is, I am not sure, but it will not result in a change here. I realize you made a reproduction repo and I do appreciate that - I gave it a brief glance - and I see your video, but something doesn't seem right as I have no problem with this module in my projects 🤔

**Comment by harshal311989** [comment]
Any update on above, it is still facing in my project Android 

"react-native": "0.71.1",
"react-native-device-info": "^11.1.0",

Android 14.0 OS it is not working in debug mode, Release mode it is working. 

I feel like it is new version react native and device info not compatible with Android 14.0 Debug mode. In debug mode it is not working but in release mode it is working kindly fix this issue asap if possible

**Comment by pedroduca** [comment]
@Kohlroulade 

The solution that worked for me was to manually link it, as it apparently wasn't linked during installation, even when using the linking command.

First, I checked the android/settings.gradle file in my application, just to be sure if there was an import for react-native-device-info, and to my surprise, there was nothing.

1. Add to `android/settings.gradle`
```groovy
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
```

```groovy
include 'presentation',
...
'react-native-device-info'
```

2. Add to `build.gradle`
    
```groovy
    dependencies {
    implementation project(':react-native-device-info')
    }
```

3. [[MainApplication.java](http://mainapplication.java/)](http://MainApplication.java) or in my case android/presentation/src/main/java/br/com/myapplication/myaplication/ui/react/MyApplicationReactNativeHost.kt
    
I found it by searching for getPackages()

    
    ```kotlin
    @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                new MainReactPackage(),
                new RNDeviceInfo() // Add this line
            );
        }
    ```
    
4. Clean the cache and rebuild the project

```bash
yarn start --reset-cache

react-native run-android
```

@rethink-alexandrejunior 
In your setup.jest.js add this 
```jsx
jest.mock('react-native-device-info', () => ({
  getModel: jest.fn(),
}))
```

**Comment by ggenova79** [comment]
I had the same issue.  Be sure to open the iOS project in Xcode then close it and try to run the app again.

**Comment by lyh543** [comment]
consider using [expo-device](https://docs.expo.dev/versions/latest/sdk/device/#installation) as alternative.

**Comment by Saakve** [comment]
I encountered the same issue with the following environment:

- OS: Windows 11
- Node: 22.18.0
- Java: OpenJDK 17.0.16 (LTS, 2025-07-15)

Dependencies:
```json
{
  "react": "19.0.0",
  "react-native": "0.78.0",
  "react-native-device-info": "^15.0.2",
  ...
}
```

To resolve the issue, I cleaned my repository using: `git clean -fxd`

After that, I manually deleted some remaining folders via File Explorer that git clean could not remove.

This approach resolved the issue in my environment, and may help others facing the same problem.

**Comment by DastanIqbal** [comment]
These flags helped to rid of this error
```
ReactNativeFeatureFlagsDefaults() {
      override fun useNativeViewConfigsInBridgelessMode() = true
      override fun useFabricInterop() = true
      override fun useTurboModuleInterop() = true
}
```
