### ISSUE TITLE
Need to have googlePlayServicesVersion = "21.0.1"

### ISSUE THREAD

**Issue by UraFIZ** [react-native-device-info/react-native-device-info#1629]
Hello! To use react-native-geolocation-service, I need to use `googlePlayServicesVersion = "21.0.1" in my build.gradle android file. You can read about it [here](https://stackoverflow.com/questions/77274148/could-not-invoke-rnfusedlocation-getcurrentposition-react-native-geolocation-s).  When I implement this update In my Android files I come across this error: 
<img width="1241" alt="image" src="https://github.com/react-native-device-info/react-native-device-info/assets/31358665/b7161f0a-5533-4456-9878-8780356db121">

Do you know if there is a workaround for this issue? I tried to follow your recommendations [here](https://github.com/react-native-device-info/react-native-device-info?tab=readme-ov-file#troubleshooting), but `exclude` did not work for me. BTW your code there is outdated. The correct syntax is    
 implementation(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms:play-services-location:'
 }
but it does not work for me :(
 
| React Native Version     |  0.73.6  |
| OS Version  | Android 14   |

**Comment by nick-casadei** [comment]
Same issue for me

**Comment by dalalmj** [comment]
Add following to android\build.gradle > buildscript > ext
googlePlayServicesIidVersion = "17.0.0"

**Comment by UraFIZ** [comment]
But I need to have 21.0.1

**Comment by dalalmj** [comment]
Yes, this was just addition. Here is what I have
        googlePlayServicesVersion = "21.0.1" 
        googlePlayServicesIidVersion = "17.0.0" //add this line

**Comment by mikehardy** [comment]
I have these lines in my build file and it works fine (note for future people or even current - the IidVersion will stay static forever as they are no longer developing it, the play-services-auth version will move over time)

```groovy
        googlePlayServicesIidVersion = '17.0.0'
        googlePlayServicesAuthVersion = '21.0.1' // play-services-auth
```
