### ISSUE TITLE
Could not get unknown property 'com' for extension 'android' of type com.android.build.gradle.LibraryExtension.

### ISSUE THREAD

**Issue by serezha13** [react-native-device-info/react-native-device-info#1630]
## Summary

|             |     |
| ----------- | --- |
| Version     | ?   |
| Affected OS | Android   |
| OS Version  | ?   |

## Current behavior

After installing this package, I can't build my app for android.

./gradlew clean

> Configure project :app

Installing unimodules:
 unimodules-core@7.1.2 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/@unimodules/core
 unimodules-react-native-adapter@6.2.2 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/@unimodules/react-native-adapter
 expo-application@2.4.1 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-application
 expo-av@9.2.3 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-av
 expo-constants@10.1.3 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/expo-constants
 expo-error-recovery@1.4.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-error-recovery
 expo-file-system@11.0.2 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-file-system
 expo-font@8.4.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-font
 expo-image-loader@2.1.1 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-image-loader
 expo-image-manipulator@9.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-image-manipulator
 expo-permissions@12.0.1 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/expo-permissions
 expo-image-picker@10.0.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-image-picker
 expo-media-library@12.0.2 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-images-picker/node_modules/expo-media-library
 unimodules-permissions-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-permissions-interface
 expo-keep-awake@8.4.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-keep-awake
 expo-linear-gradient@8.4.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-linear-gradient
 expo-local-authentication@9.5.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-local-authentication
 expo-location@10.0.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-location
 expo-modules-core@0.2.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-modules-core
 expo-secure-store@9.3.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-secure-store
 expo-splash-screen@0.8.1 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-splash-screen
 expo-sqlite@8.5.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-sqlite
 expo-web-browser@8.6.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/expo-web-browser
 unimodules-app-loader@2.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-app-loader
 unimodules-barcode-scanner-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-barcode-scanner-interface
 unimodules-camera-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-camera-interface
 unimodules-constants-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-constants-interface
 unimodules-face-detector-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-face-detector-interface
 unimodules-file-system-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-file-system-interface
 unimodules-font-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-font-interface
 unimodules-image-loader-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-image-loader-interface
 unimodules-sensors-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-sensors-interface
 unimodules-task-manager-interface@6.1.0 from /Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-unimodules/node_modules/unimodules-task-manager-interface

Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-media-library, expo-permissions, unimodules-react-native-adapter, expo-file-system, unimodules-core, expo-constants, unimodules-permissions-interface, unimodules-app-loader, unimodules-barcode-scanner-interface, unimodules-camera-interface, unimodules-constants-interface, unimodules-face-detector-interface, unimodules-file-system-interface, unimodules-font-interface, unimodules-image-loader-interface, unimodules-sensors-interface, unimodules-task-manager-interface

> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/serezha13/Desktop/projects/parkupkeep-mobile-app/node_modules/react-native-device-info/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':react-native-device-info'.
> Could not get unknown property 'com' for extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s

## Expected behavior

App build.

**Comment by mikehardy** [comment]
Hi there, it builds fine in CI, and in my app. This will be a project-specific problem and I won't have time to help you with it, apologies.
