### ISSUE TITLE
Get information about auto time and auto timezone

### ISSUE THREAD

**Issue by sanduluca** [react-native-device-info/react-native-device-info#1631]
## Description

It will be great to have the api for getting the info about android/ios auto time & auto timezone (it it is on or off)
 
I see that android has this apis but could not find the appropriate one for iOS. I didn't searched for other platforms.
https://developer.android.com/reference/android/provider/Settings.Global#AUTO_TIME
https://developer.android.com/reference/android/provider/Settings.Global#AUTO_TIME_ZONE

I also found this repo that says that they implemented this but as a flutter plugin

## Use Case

We had a use case where we needed the user to have the same exact time as time servers. We could check if the user dont have it with auto, we could limit his acces to some features in app that require him to have exact time

**Comment by mikehardy** [comment]
Hi there!

No, use react-native-localize
