### ISSUE TITLE
Components that depend on useIsHeadphonesConnected on Android don't re-render when bluethooth headphones are connected/disconnected.

### ISSUE THREAD

**Issue by eedeebee** [react-native-device-info/react-native-device-info#1633]
## Summary

`useIsHeadphonesConnected` hook doesn't trigger re-renderings when BT headphones are connected/disconnected on Android.
This works fine on iOS.

## Current behavior

If you have a react component that uses this hook, it will not re-render anything that depends on the value of this hook on Android, when you connect/disconnect BT headphones.  

## Expected behavior

I can provide an example if that is helpful.

**Comment by mikehardy** [comment]
Hi there! A PR would be helpful, this isn't a use case of mine so someone will have to determine the root cause and code up a fix

**Comment by paulwellnerbou** [comment]
I have a similar issue on Android, `useIsHeadphonesConnected` does not trigger any event at all. I use

```javascript
const deviceInfoEmitter = new NativeEventEmitter(NativeModules.RNDeviceInfo);
const listener = deviceInfoEmitter.addListener('RNDeviceInfo_headphoneConnectionDidChange', (headphone) => { ... })
```

instead.

**Comment by AlexLerman** [comment]
@paulwellnerbou Does that work for you? I've tried both ways and neither does anything. I don't receive any events.

**Comment by paulwellnerbou** [comment]
@AlexLerman , yes it works for me (Android).

**Comment by AlexLerman** [comment]
No, unfortunately I ended up writing my own implementation.

**Comment by NicolasD27** [comment]
@AlexLerman would you mind sharing it please ? Or give me a hint ?

**Comment by AlexLerman** [comment]
@NicolasD27 Sorry for the delayed response. You can see my implementation here:
https://github.com/AlexLerman/voice/blob/master/android/src/main/java/com/wenkesj/voice/VoiceModule.java

I ended up just using an event listener instead of a hook. 

Here's the code that uses it

`    Voice.isBluetoothInputConnected()
      .then(enabled => {
        if (enabled) {
          //BT device connected, do something.
        }
      })
      .catch(error => {
        console.log(error);
      });

    const eventEmitter = new NativeEventEmitter(NativeModules.Voice);
    let eventListener = eventEmitter.addListener('BTCONNECT', e => {
      if (e.event.code === '1') {
        //Earpiece connected
      } else {
        //Speaker connected;
      }
    });`
