### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes

### ISSUE THREAD

**Issue by virat07** [react-native-device-info/react-native-device-info#1637]
## Summary

|             |     |
| ----------- | --- |
| Version     | 18.2.0  |
| Affected OS |  17.0.4   |
| OS Version  | 17.0.4   |

## Current behavior
 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument., js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered.
![Screenshot 2024-04-24 at 11 01 44 PM](https://github.com/react-native-device-info/react-native-device-info/assets/36244814/dcd0fb99-9271-4987-8f7b-12939752c581)

While making the build getting this error. 
![Screenshot 2024-04-24 at 11 04 33 PM](https://github.com/react-native-device-info/react-native-device-info/assets/36244814/44f8fcb9-c471-4a5f-a377-5675ab3d95f0)

## Expected behavior

Being able to use the methods in this package without errors

**Comment by mikehardy** [comment]
Hi there - what version of react-native are you using? Is there anything else you can think of to include that would help figure out why you are seeing this but it works for me ? (https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by virat07** [comment]
@mikehardy Thank you for your response.
{
  "name": "awesomeproject",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/material-top-tabs": "^6.6.13",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "expo": "^51.0.1",
    "expo-status-bar": "~1.11.1",
    "expo-updates": "~0.24.12",
    "firebase": "^10.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-animatable": "^1.4.0",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-get-random-values": "^1.11.0",
    "react-native-pager-view": "^6.2.3",
    "react-native-paper": "^5.12.3",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-webview": "13.8.6",
    "react-native-youtube-iframe": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
this the package json, I got that issue when I install https://www.npmjs.com/package/react-native-pdf package.

**Comment by mikehardy** [comment]
Sounds like you should open an issue in react-native-pdf, I don't even see our package here

Strangely I don't see react-native-pdf in your list of dependencies either, so... how did you install it, without it being in your dependencies 🤔 

react-native-pdf doesn't include this package as a transitive dependency either? https://github.com/wonday/react-native-pdf/blob/master/package.json

You're not making it easy to help

I don't see any reference to this package anywhere in any of the information you've provided, so this isn't actionable, and I don't have a lot of time, certainly not to spend looking at non-actionable things

**Comment by imp87** [comment]
Hi everyone. Got the same error when i am importing react-native-device-info
![image](https://github.com/react-native-device-info/react-native-device-info/assets/95252622/c0a670b0-e62b-4fbe-b5b4-2abdb30265a2)


My package.json

`{
  "name": "controldesk-app",
  "version": "1.0.1",
  "main": "app.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web --tunnel --clear"
  },
  "dependencies": {
    "@awesome.me/kit-dfa7f715e4": "^1.0.7",
    "@expo/ngrok": "^4.1.3",
    "@expo/vector-icons": "^14.0.0",
    "@fortawesome/pro-solid-svg-icons": "^6.5.1",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.6.14",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.25",
    "@react-navigation/stack": "^6.3.29",
    "axios": "^1.6.8",
    "crypto-js": "^4.2.0",
    "expo": "^51.0.12",
    "expo-dev-client": "~3.3.11",
    "expo-device": "^5.9.3",
    "expo-notifications": "~0.27.6",
    "expo-status-bar": "~1.11.1",
    "nativewind": "4.0.1",
    "react": "18.2.0",
    "react_native_mqtt": "^1.3.1",
    "react-icons": "^5.0.1",
    "react-native": "^0.73.6",
    "react-native-alert-notification": "^0.4.0",
    "react-native-device-info": "^11.1.0",
    "react-native-dropdown-select-list": "^2.0.5",
    "react-native-element-dropdown": "^2.10.2",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-logs": "^5.1.0",
    "react-native-notifications": "^5.1.0",
    "react-native-reanimated": "^3.10.1",
    "react-native-safe-area-context": "^4.8.2",
    "react-native-screens": "^3.29.0",
    "react-native-svg": "^15.1.0",
    "react-native-svg-transformer": "^1.3.0",
    "react-native-web": "~0.19.10",
    "tailwindcss": "^3.4.1",
    "twrnc": "^4.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
`

Already tried with the version 10, but got the same error
