### ISSUE TITLE
can't find com.google.android.gms:play-services-iid:21.0.1

### ISSUE THREAD

**Issue by sharived** [react-native-device-info/react-native-device-info#1640]
## Summary

|             |     |
| ----------- | --- |
| Version     | 11.1.0   |
| Affected OS | Android   |
| OS Version  | 34   |

## Current behavior

When building my app for android it is unable to find com.google.android.gms:play-services-iid:21.0.1. (My app uses googlePlay 21.0.1) My understanding is that there isn't a version since 17.0. See related issues #1584 and #802

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-iid:21.0.1.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - https://repo.maven.apache.org/maven2/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - file:/Users/shari/pd-mobile-app/node_modules/jsc-android/dist/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - https://www.jitpack.io/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
     Required by:
         project :app
   > Could not find com.google.android.gms:play-services-iid:21.0.1.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - https://repo.maven.apache.org/maven2/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - file:/Users/shari/pd-mobile-app/node_modules/jsc-android/dist/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
       - https://www.jitpack.io/com/google/android/gms/play-services-iid/21.0.1/play-services-iid-21.0.1.pom
     Required by:
         project :app > project :react-native-device-info

I
## Expected behavior

Should not be looking for 21.0.1 and should build

**Comment by fabioruxo** [comment]
Same for me

**Comment by prince-d-simform** [comment]
same issue

**Comment by virajpsimformsolutions** [comment]
@sharived  @fabioruxo  @prince-d-simform 
You can place these root settings in your project-level build.gradle file (at android/build.gradle), in the buildscript section:

```
 buildscript {
    ext {
        googlePlayServicesIidVersion = "17.0.0"
        ....
    }
```

**Comment by Rahulmalik123** [comment]
same

**Comment by mikehardy** [comment]
The answer from @mspvirajpatel is the correct answer
