### ISSUE TITLE
Same Device ID issue in IOS

### ISSUE THREAD

**Issue by pranita-kale-sneo** [react-native-device-info/react-native-device-info#1646]
We are using getUniqueId for identifying unique mobile users but multiple devices are giving same getUniqueId.  We are testing with following  scenario like

1.  Same Apple ID in both devices - Same ID
2.  Device migrated with old device and keychain file is also copied - Same ID
3. Using syncUniqueId() which is generating new device id/random string but we want to preserve the logs - Every time Diff ID after app install and uninstall

Also confirmed by users they are not using same Apple ID still they are getting same getUniqueId.

**Comment by mikehardy** [comment]
This is fixed by #1642, and released
