### ISSUE TITLE
Implement Rooted Device Check 

### ISSUE THREAD

**Issue by 5cientist** [react-native-device-info/react-native-device-info#1647]
## Description

Implement a feature to check if a device is rooted or jailbroken 

let isRooted = DeviceInfo.isRooted();
// true

## Use Case

When users launch the app, the feature will run a quick check to detect any rooted or jailbroken devices. If a rooted device is identified, appropriate steps will be taken to ensure the security and integrity of the app environment.

**Comment by zaferatli** [comment]
Is it on the plan, i can create this feature @mikehardy

**Comment by mikehardy** [comment]
Nothing is on the plan, it's open source
Propose a PR
