### ISSUE TITLE
Android Performance class

### ISSUE THREAD

**Issue by AdamGerthel** [react-native-device-info/react-native-device-info#1648]
## Description

I'm interested in getting the device's performance class (see https://developer.android.com/topic/performance/performance-class) in order to be able to set certain default app settings related to performance. Since Android seems to support such a system, would it be able to expose those values through RN device info? 

## Use Case

I make games using RN and I need a way to classify devices into performance brackets, specifically on Android. iOS has never been an issue, all Apple's devices tend to perform very well.

**Comment by mikehardy** [comment]
Hey there - thanks for the link to the docs
Based on those, it appears that you can either use an AndroidX dependency and a bunch of code or...

You could just grab this value https://developer.android.com/reference/android/os/Build.VERSION#MEDIA_PERFORMANCE_CLASS and use it directly as an integer, tailoring the experience based on the information in [this section](https://developer.android.com/topic/performance/performance-class#class-14) (and below) and the Android CDD for really fine details as needed

Something like this code block would do it

https://github.com/react-native-device-info/react-native-device-info/blob/78b70a07bc1248d16eb286416b78e9328cb493b4/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L941-L949

but for API >= 31 (when MEDIA_PERFORMANCE_CLASS was added) and with the correct property of course

If you make a PR for this, add it to the typescript so it's available in javascript layer (of course) and make an entry for the new function in the docs (noting as android only) and add it to the example app as well (which should be useful to do as you are testing it anyway, so you can see it working... - `yarn dev-sync` is how to get the local module changes copied into the dev app before running `yarn android` inside the example directory again)

**Comment by AdamGerthel** [comment]
I've decided to go a different route for the time being, but I appreciate the help!
