### ISSUE TITLE
How to translate old / new unique ID

### ISSUE THREAD

**Issue by ps-dmaksimovic** [react-native-device-info/react-native-device-info#1661]
I have used this library version 11 until today when I upgraded it, and I used  getUniqueId as the primary user identifier.
After I upgraded to v12, the unique ID is reporting a different value, at least on iOS. All my users would now  effectively lose their account if I continue. How do I map the old values to the new ones, or the new to the old? 

Thanks in advance

**Comment by mikehardy** [comment]
Please read the release notes --> https://github.com/react-native-device-info/react-native-device-info/releases/tag/v12.0.0

If you relied on the behavior of cross-device uniqueId, you'll want to use react-native-keychain to persist your cross-device userid

Note that on android it was never cross-device, it was per-device. So this behavior is now standardized across both platforms, but with react-native-keychain you may simulate the old iOS behavior / platform difference

**Comment by dimaischenko** [comment]
@mikehardy it turns out that the user needs to at least once enter the application with the old version of `react-native-device-info` with the logic of saving the old `unique id` to Keychain, so as not to lose it during the update. Because after updating `react-native-device-info` access to the old `unique id` will be lost forever? Or am I wrong?

**Comment by mikehardy** [comment]
@dimaischenko that is certainly one way, though it seems like a lot of coordination 🤔 

perhaps if you used react-native-keychain to access the previous key in the exact same way it was accessed before, you would get the value from the cloud keychain just like before?

The previous key was `deviceUUID` 

https://github.com/react-native-device-info/react-native-device-info/blob/b5517cbc1362792abe4f44a27ca03029f5c40b73/ios/RNDeviceInfo/DeviceUID.m#L15

And the same string was used for the service:

https://github.com/react-native-device-info/react-native-device-info/blob/b5517cbc1362792abe4f44a27ca03029f5c40b73/ios/RNDeviceInfo/DeviceUID.m#L50

So with some creative / careful use of react-native-keychain you *should* be able to get the identifier in the same way? Something like https://oblador.github.io/react-native-keychain/docs/usage#ios

**Comment by dimaischenko** [comment]
@mikehardy sounds very realistic, I will try to do something like that soon. Thanks for the idea and the answer!
