### ISSUE TITLE
Not able to get the value of lowpowermode in 24H2 OS

### ISSUE THREAD

**Issue by dileeps14** [react-native-device-info/react-native-device-info#1662]
## Summary
Working on Windows application.
usePowerState().lowPowerMode is returning always 'false' in 24H2 OS.

Note: This works properly in 23H2 OS

Windows Settings => Power & Battery => Battery Saver (ON)

![image](https://github.com/user-attachments/assets/4ae2253a-91c6-4bbd-98ca-81e932cb121c)

|             |     |
| ----------- | --- |
| Version     | 10.9.0 and 13.0.0   |
| Affected OS | Windows   |
| OS Version  | 24H2   |

## Current behavior

Getting 'false' always

## Expected behavior

It should be 'true' when battery saver/ Energy Saver is turned ON

**Comment by mikehardy** [comment]
I'm just not sure how this line could go wrong:

https://github.com/react-native-device-info/react-native-device-info/blob/78b70a07bc1248d16eb286416b78e9328cb493b4/windows/code/RNDeviceInfoCPP.h#L328C35-L328C90

We appear to be using it as documented:
https://learn.microsoft.com/en-us/uwp/api/windows.system.power.powermanager.energysaverstatus?view=winrt-26100
https://learn.microsoft.com/en-us/uwp/api/windows.system.power.energysaverstatus?view=winrt-26100

Additionally, we appear to be subscribing correctly for changes to use in hooks:

https://github.com/react-native-device-info/react-native-device-info/blob/78b70a07bc1248d16eb286416b78e9328cb493b4/windows/code/RNDeviceInfoCPP.h#L29-L30

... delegating back to the original getPowerState method on change events:

https://github.com/react-native-device-info/react-native-device-info/blob/78b70a07bc1248d16eb286416b78e9328cb493b4/windows/code/RNDeviceInfoCPP.h#L891-L894

and we're listening correctly I think https://github.com/react-native-device-info/react-native-device-info/blob/78b70a07bc1248d16eb286416b78e9328cb493b4/src/index.ts#L825-L828

You might try comparing the information you get from calling the API methods directly vs in hooks, and/or you might try adding debug / printout code into the windows implementation to see what it is doing (that is, log that the method is called, log all return values etc

It appears @jaimecbernardo was the original implementer but that was nearly 4 years ago! So Jaime may know something, or may have forgotten completely about this 😆 

I won't be able to assist further, apologies, but PRs are happily accepted.
