### ISSUE TITLE
isHeadphonesConnected()  isBluetoothHeadphonesConnected() not working as expected

### ISSUE THREAD

**Issue by E3lleyyaa** [react-native-device-info/react-native-device-info#1668]
RN version : 0.74.1
Arch: both
Platform: IOS
IOS version : 18.1
These methods always return false, even when airpods connected. I've tried with different headphones but its still return false every time.

**Comment by mikehardy** [comment]
I don't have airpods, so you'll have to dig in to the native method, add some logging output, run that altered build on a real device while it is plugged in to your dev machine and watch Console.app to see your logging output. Log all the API calls and parameters and return values and such to the native APIs and see why, post a PR and I'll be happy to merge it

**Comment by KovtonyckIlya** [comment]
> I don't have airpods, so you'll have to dig in to the native method, add some logging output, run that altered build on a real device while it is plugged in to your dev machine and watch Console.app to see your logging output. Log all the API calls and parameters and return values and such to the native APIs and see why, post a PR and I'll be happy to merge it

I tested this on an iPhone 14 and an iPhone X using AirPods and a large Bluetooth headset, and the result is the same. I created a native module with the code from your library, but for some reason, when using AVAudioSession, it always returns "Speaker" as the only available output instead of the connected device:

<AVAudioSessionPortDescription: 0x30135d820, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>

Unfortunately, I don't have an adapter to test with a wired headset.

**Comment by KovtonyckIlya** [comment]
> I don't have airpods, so you'll have to dig in to the native method, add some logging output, run that altered build on a real device while it is plugged in to your dev machine and watch Console.app to see your logging output. Log all the API calls and parameters and return values and such to the native APIs and see why, post a PR and I'll be happy to merge it

Looks like found how to fix that.
`- (BOOL)isBluetoothHeadphonesConnected {
    NSError *error = nil;
    AVAudioSession *audioSession = [AVAudioSession sharedInstance];
    
    // Setup session for supporting Bluetooth devices
    [audioSession setCategory:AVAudioSessionCategoryPlayAndRecord
                  withOptions:AVAudioSessionCategoryOptionDefaultToSpeaker | AVAudioSessionCategoryOptionMixWithOthers | AVAudioSessionCategoryOptionAllowBluetooth
                        error:&error];
    if (error) {
        NSLog(@"Error setting AVAudioSession category: %@", error);
        return NO;
    }
    
    // Session activation
    BOOL success = [audioSession setActive:YES error:&error];
    if (!success) {
        NSLog(@"Failed to activate AVAudioSession: %@", error);
        return NO;
    }
    
    // Get current route
    AVAudioSessionRouteDescription* route = [audioSession currentRoute];
    NSLog(@"Current Route: %@", route);
    
    // check whole outputs
    for (AVAudioSessionPortDescription* desc in [route outputs]) {
        NSString *portType = desc.portType;
        NSLog(@"Detected output port: %@, name: %@", portType, desc.portName);
        
        // Extendent list of ports
        if ([portType isEqualToString:AVAudioSessionPortBluetoothA2DP] ||
            [portType isEqualToString:AVAudioSessionPortBluetoothHFP] ||
            [portType isEqualToString:AVAudioSessionPortBluetoothLE] ||
            [portType isEqualToString:AVAudioSessionPortAirPlay] ||
            [desc.portName containsString:@"AirPods"] ||
            [desc.portName containsString:@"Bluetooth"]) {
            NSLog(@"Bluetooth headphones detected: %@", desc.portName);
            return YES;
        }
    }
    
    NSLog(@"No Bluetooth headphones detected");
    return NO;
}
`
With this code, it returns
`Current Route: <AVAudioSessionRouteDescription: 0x301a403d0, 
inputs = (
    "<AVAudioSessionPortDescription: 0x301a40370, type = BluetoothHFP; name = AirPods \U043a\U043e\U0440\U0438\U0441\U0442\U0443\U0432\U0430\U0447\U0430 Ilya Kovtonyck; UID = B8:81:FA:DD:EB:F1-tsco; selectedDataSource = (null)>"
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x301a40130, type = BluetoothHFP; name = AirPods \U043a\U043e\U0440\U0438\U0441\U0442\U0443\U0432\U0430\U0447\U0430 Ilya Kovtonyck; UID = B8:81:FA:DD:EB:F1-tsco; selectedDataSource = (null)>"
)>`

instead of 
`Current Route: <AVAudioSessionRouteDescription: 0x30135d400, 
inputs = (
    "<AVAudioSessionPortDescription: 0x30135d890, type = MicrophoneBuiltIn; name = iPhone Microphone; UID = Built-In Microphone; selectedDataSource = Bottom>"
); 
outputs = (
    "<AVAudioSessionPortDescription: 0x30135d820, type = Speaker; name = Speaker; UID = Speaker; selectedDataSource = (null)>"
)>`

To me this solution is more of a crutch and I don't know if it's worth posting, but maybe it will help you in your fix.

**Comment by mikehardy** [comment]
I won't have a fix 😆  - this isn't a use case of mine
if it fixes the problem for you - and it sounds like it does? -  I'm open to a PR as I said
if it feels hacky or crutchy, just remember that most software is just well documented hacks that have proven to work over time...

**Comment by E3lleyyaa** [comment]
> I won't have a fix 😆 - this isn't a use case of mine if it fixes the problem for you - and it sounds like it does? - I'm open to a PR as I said if it feels hacky or crutchy, just remember that most software is just well documented hacks that have proven to work over time...

Got you, will do PR soon.
