### ISSUE TITLE
Return `true` by default for `hasNotch()` on unsupported new iOS device models

### ISSUE THREAD

**Issue by Stafox** [react-native-device-info/react-native-device-info#1669]
## Description

Can we return `true` by default for `hasNotch()` on iOS in case checked device model does not supported by the library?  
New devices  likely will have the notch or smth similar

## Use Case

User migrate to new device with app version that does not has recent device-info and as result can't provide correct information about hasNotch() 

Any opinions why it can be bad a practice?

**Comment by mikehardy** [comment]
This seems reasonable, I would likely accept a PR for this

However! And this is important, I would only accept it with something else I have been wanting for a very long time (but is thankfully also easy)

The API itself should be marked deprecated, and a huge deprecation warning should be added in the docs for it, and it should point to https://github.com/th3rdwave/react-native-safe-area-context

No one should use hasNotch anymore, it's a terrible idea in the modern world and react-native-safe-area-context is what we should all be using these days

Same for hasDynamicIsland
