### ISSUE TITLE
Version 13.1.0 getFreeDiskStorage breaks tvOS support

### ISSUE THREAD

**Issue by Duell10111** [react-native-device-info/react-native-device-info#1670]
## Summary

Since Version 13.1.0 the library does not support tvOS anymore since the getFreeDiskStorage implementation uses unsupported classes on tvOS.
The previous version 13.0.0 works fine.

|             |     |
| ----------- | --- |
| Version     | 13.1.0   |
| Affected OS | tvOS  |
| OS Version  | 18.0   |

## Current behavior

Compile fails on tvOS, as unsupported classes are used.
<img width="1830" alt="image" src="https://github.com/user-attachments/assets/50183f3a-3cc7-44ec-b169-0aa87d8c9cde">

## Expected behavior

Compile works again on tvOS.

**Comment by mikehardy** [comment]
Ah, sorry about that. Probably as easy to post a PR as it is to post an issue since it appears you have a working tvOS compile environment? I don't at the moment. If you could put the proper IFDEFs in there and/or a correct tvOS implementation I'd be more than happy to merge it
