### ISSUE TITLE
Not supported by Apple Appstore anymore

### ISSUE THREAD

**Issue by Themrpie** [react-native-device-info/react-native-device-info#1672]
## Summary

I love this library, I've used in many apps that I've released, but for the first time I got a problem with Apple developers.
When I submit my new app I got this:

> 
> Please correct the following issues and upload a new binary to App Store Connect.
> 
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

I didn't know that I was using UIWebview, so I did:
`grep -r "UIWebView" node_modules/`

And got:

> node_modules//react-native-device-info/ios/RNDeviceInfo/RNDeviceInfo.m:    UIWebView* webView = [[UIWebView alloc] initWithFrame:CGRectZero];

So it seems that is react-native-device-info who is using it. And for what I'm reading now it should be using WKWebView.
Is there any way to solve this? I tried by editing the RNDeviceInfo.m file but it didn't work.

Thank you
## Current behavior

It's being rejected by Apple
## Expected behavior
It should be accepted

**Comment by mikehardy** [comment]
https://github.com/search?q=repo%3Areact-native-device-info%2Freact-native-device-info%20UIWebView&type=code

what version are you using ?

It doesn't exist in the code

**Comment by mikehardy** [comment]
(used to tho)

**Comment by Themrpie** [comment]
Oh thank now I updated the library and it's working again. But I let you know that using "react-native-device-info": "^14.0.0"
I was getting the same error:

> [TypeError: _nativeInterface.default.getUniqueId is not a function (it is undefined)]

But then I installed the version 9 and it's working perfectly :).

Thanks again

**Comment by mikehardy** [comment]
Little of that makes sense as something to do on purpose - using old APIs on new versions of the module, or just continuing to use old versions instead of updating, but sounds like there's no actual module problem here.
