### ISSUE TITLE
Can we update com.google.android.gms:play-services-basement from 17.0.0 to 18.0.2 above

### ISSUE THREAD

**Issue by smaidah** [react-native-device-info/react-native-device-info#1674]
Now secure Vulnerbility scan throwing error related to this. 
Outdated play-services-basement Library Contains Known Security Flaw

which should target 18.0.2 to be safe

**Comment by mikehardy** [comment]
Sure, we can do whatever we need to do. Test the change to make sure it works in the areas where it is used and a post a PR, happy to merge it and kick out a release. If this is the same area as #1673 it might be about to go away anyway? Could you check and see if this is the dependency you meant?
