### ISSUE TITLE
RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED - Android SDK 34+ for isLocationEnabled

### ISSUE THREAD

**Issue by ymanahov-wyn** [react-native-device-info/react-native-device-info#1680]
## Summary

|             |     |
| ----------- | --- |
| Version     | ^14.0.1   |
| Affected OS | ? Android 14 and up  |
| OS Version  | Android 14   |

## Current behavior

When trying to use isLocationEnabled method, getting the RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED  error. 
I saw there was a similar issue reported before:
https://github.com/react-native-device-info/react-native-device-info/issues/1628

It was fixed by adding a check for the SDK version. I would like to request the same fix for this please. 

## Expected behavior

The isLocationEnabled should work as expected without throwing that error.

**Comment by mikehardy** [comment]
Hey @ymanahov-wyn - no need to request a fix, post a PR, I can merge it and release it quickly

**Comment by ymanahov-wyn** [comment]
Okay, I will try to fix it using a similar method to the one you used in the other issue. Please let me know if there's anything you would like to change.

**Comment by ymanahov-wyn** [comment]
The thing is, I am a React Native developer, so I am not 100% familiar with Java code.

**Comment by ymanahov-wyn** [comment]
Update:
The issue might not be from this library whatsoever, disregard my previous comments.
