### ISSUE TITLE
getFreeDiskStorage does not return the same value as system setting in iOS

### ISSUE THREAD

**Issue by jcliang1212** [react-native-device-info/react-native-device-info#338]
when in iOS, use the express “getFreeDiskStorage()/1000000000” get 9.94GB, the "System Setting" show 9.73GB, and  use the express “getTotalDiskCapacity()/1000000000” get 13.23GB, the "System Setting" show 13.23GB. So, why getFreeDiskStorage() does not match the value of "System Setting" in iOS? Please help me, thanks. @crafterm @doochik @DracoBlue @stevemoser @jeveloper

**Comment by DracoBlue** [comment]
Hey! The value is a integer in java and a floating point „number“ in JavaScript. Since this is the case, you don’t get 100% accuracy for each digit.

A possible solution could be to add a new function, which returns the storage in kb or mb with everything after the `.` beeing the kb/bytes.

E.g: 1200000 becomes 1.2

**Comment by jcliang1212** [comment]
@DracoBlue , thanks for your answer. But why the getTotalDiskCapacity() matches the value of "System Setting" in iOS? And getFreeDiskStorage() is bigger than the value of "System Setting" in iOS in some iPad and is smaller than the value of "System Setting" in iOS on other iPad. I do not think it is the problem of different data type between JS and other languages.

**Comment by jcliang1212** [comment]
@DracoBlue , this problem does not happen in iOS simulator.

**Comment by DracoBlue** [comment]
This seems to be an issue with the way how iOS retrieves the amount of free disk space.

Can you try one of the alternative ways in this stackoverflow question: https://stackoverflow.com/questions/11717304/why-does-the-value-from-nsfilesystemfreesize-differ-from-the-free-size-reported ?

**Comment by jcliang1212** [comment]
@DracoBlue ，I agree with you, thanks! But I still do not find the solution. Here is another question: In Android, getTotalDiskCapacity()  do not get the right value, because "Integer" is not big enough, so I change the returned type of getTotalDiskCapacity() to Long, but It still not that right. The system setting show the total disk is 8.0GB, but I get 4.30 GB.
