### ISSUE TITLE
[Discussion] `getUniqueID` for Android should use another implementation

### ISSUE THREAD

**Issue by SandroMachado** [react-native-device-info/react-native-device-info#355]
`getUniqueID` function for android returns the constant `ANDROID_ID`. Based on an official [post](https://android-developers.googleblog.com/2011/03/identifying-app-installations.html) from Google at the android developers blog, the `ANDROID_ID` is not reliable.

> ANDROID_ID seems a good choice for a unique device identifier. There are downsides: First, it is not 100% reliable on releases of Android prior to 2.2 (“Froyo”). Also, there has been at least one widely-observed bug in a popular handset from a major manufacturer, where every instance has the same ANDROID_ID.

In another [document](https://developer.android.com/training/articles/user-data-ids.html) from google, they suggest to identify the app create a UUID and store it at the internal storage.

> In cases where an Instance ID isn't practical, custom globally unique IDs (GUIDs) can also be used to uniquely identify an app instance. The simplest way to do so is by generating your own GUID using the following code.

They also recommend to not use the `ANDROID_ID`.

> #1: Avoid using hardware identifiers. Hardware identifiers such as SSAID (Android ID) and IMEI can be avoided in most use-cases without limiting required functionality.

My suggestion is change the `getUniqueID` function to return a previously generate `UUID`. If there is no one available, generate it, store it and return that value. Basically is to implement the google's suggestion.

WDYT? I am offering to implement this.

\cc @machour 

Refs: https://github.com/rebeccahughes/react-native-device-info/issues/60

**Comment by machour** [comment]
@SandroMachado thank you so much for bringing this up. In fact, I was thinking of moving getUniqueID() from native to the javascript land and use the same implementation for the three platforms (we could also implement it for react-native-web if needed).

As this is a BC breaking changes, this will have to be shipped in 1.0.0. Have a look at #307 for the rest of the plans and don't hesitate to comment there and give more ideas!

**Comment by SandroMachado** [comment]
I think that we should keep this on native side, to take the advantage of the apple/iOS api, that is really well designed.

On Android, like I said before, I can make a PR to update this API to match the iOS behaviour (removing the vendor logic) since they have an API to generate UUID (`UUID.randomUUID().toString();`). WDYT?

Also, to generate a UUID on JS side, from my search, I didn't find any solution that does not relays on the random string generation method, that is not the most desirable solution since it can lead to collisions and that should not happens.

**Comment by machour** [comment]
I totally agree. Feel free to work on a PR for the implementation whenever you want :)

**Comment by SandroMachado** [comment]
Done #358.

**Comment by schumannd** [comment]
When will this be merged? I can see the current behavior causing bugs for people, as it did for me.
Not only does the android `getUniqueID()` not produce a valid UUID like the iOS version does, it doesn't even reliably produce a 16 length hex. Some models (maybe even all?) drop leading zeroes. Sure, it was my fault for assuming it didn't do that, but I can see this happening to other people as well. So +1 to this PR

**Comment by mikehardy** [comment]
I'm looking into this now in the context of #602, but if we're going to do this I'd like to with a non-native implementation as we're just handling UUIDs here. Something like https://github.com/react-native-community/react-native-device-info/issues/60#issue-163782044 should be simple and sufficient?
