### ISSUE TITLE
iPhone XS etc support

### ISSUE THREAD

**Issue by Jahans3** [react-native-device-info/react-native-device-info#513]
## Summary
Not detecting iPhone XR, XS, XS Max on simulator. I am not sure if this is simulator-specific since I don't have access to any of the newer phones.

I have seen #499 but assuming that is working on devices it is currently not working on simulators.

| ----------- | --- |
| Version     |  0.24.0 |
| Affected OS | iOS  |
| OS Version  | 12  |

## Current behavior
Instead of `DeviceInfo.getModel()` returning `iPhone XS` as expected, it just returns `iPhone`.

## Expected behavior
Should return correct string for device.

**Comment by machour** [comment]
Hey @duro, could you possibly have a look at this?

**Comment by tclarke-scottlogic** [comment]
This doesn't match my experience inside simulators....
![screen shot 2018-10-12 at 12 23 17 2](https://user-images.githubusercontent.com/35029405/46874419-0a84e100-ce31-11e8-8ad1-db92bb228cd4.png)
