### ISSUE TITLE
Introduce method .hasCutHole() 

### ISSUE THREAD

**Issue by wmonecke** [react-native-device-info/react-native-device-info#594]
**## Description**

With cut holes being introduced in 2019 (Samsung S10) it would be great to have a `.hasCutHole()` method that would return an Array with where the cut holes are located or an empty array if no cut holes are present. However, it might be more appropriate to maybe add this to the `.hasNotch` method. Returning an object describing if it is a cut hole or a notch and if it is a cut hole, specifying its location.

if left and right cut holes -> `['left', 'right']` // Mi Mix 4 patents show dual cut holes
if only left -> `['left']`
no cut holes -> `[]`

**## Use Case**

Some of my Apps hide the Status Bar and the newly introduced cut holes now interfere with some critical buttons.

**Comment by mikehardy** [comment]
Huh - I hadn't even seen that this was a thing :-). But it is, [just a little non-displayable-area at the top right on the S10](https://www.xda-developers.com/files/2019/03/s10-wallpapers.jpeg)

This whole "your display is a rectangle" to "your display is a rectangle with 0 or more parts missing" seems like it needs a more generic solution than "notch", "punch-hole" (what the press is calling the S10 thing), or "multiple punch-holes" (like the maybe-Mi Mix 4)

Seems like the phrase "sensor areas" would describe *what* they are, then there should be a lookup takes a device brand/model and returns an array of sensor areas as well as their locations. Seems like people might want the actual pixel locations of the bounding box describing the sensor area as well as a vague description of "top-left" and "top-right" and "top-center" etc?

Then the existing hasNotch API could easily be mapped to it if we wanted backwards compatibility but whatever complicated thing Samsung or Mi Mix 4 wanted to do, we could handle easily?

Am I overthinking this?

**Comment by wmonecke** [comment]
No, I think its definitely in the right direction!

Sensor area sounds about right. And yes, I would love to have the width and height of the punch holes but since `hasNotch` only returned true or false, this was enough for me to correctly handle my app layout.

However, I am still a bit confused about how backward compatibility would work on `.hasNotch` without changing the return value?

Do you mean if `hasNotch` returns true a new method `sensorAreas` should describe the sensor areas on the phone?

[Here](https://en.gizchina.it/2019/02/xiaomi-patent-dual-selfie-camera/) you can see the layouts Xiaomi is considering.

**Comment by machour** [comment]
I'm also discovering the thing, wow :D 

About BC: we will be releasing 1.0.0 soon (#307) and adopting a strict semantical release after that. 
So no harm would be done if we raise to 2.0

But I've got a feeling that after notch, cut hole, punch-hole, something else will soon emerge.

I also don't like at all how hasNotch() is implemented right now: a growing list of devices, sometimes it's the same, but spelled differently. I'd hate to see this replicated for punch hole.

Maybe it's time to rethink the static data structure a bit, and be able to handle hasNotch, hasCutHole, and all future derivatives from a single point.

```js
const devicesFeatures = {
  `oneplus`: [
      {
          // one of the declination, easy to understand for us
          model: '6',
          // could be enhanced by dynamically removing the brand
          aliases: ['ONEPLUS A6000', 'ONEPLUS A6013', 'A6000'] 
          // hardcoded features, absence means false
          notch: true,
          foldable: true,
          punch: false,  // <- could be skipped
      },
      // ..
   ],
  // ..
}
```

WDYT?

**Comment by wmonecke** [comment]
I like that you already included the foldable prop 😃. I am definitely for it.

**Comment by mikehardy** [comment]
foldable, ha! But yes

That data structure or similar was what I was thinking yes. Then what I meant by "mapping" the previous API to it, is just to say that you could have "hasNotch" look in the data structure and if it sees notch: true, it could return true, to maintain that API.

I am *not* saying that backwards-compatibility is some specific goal - I don't personally care at this point as long as it respects semantic versioning, I was just thinking out loud that it should be possible if desired

**Comment by mikehardy** [comment]
There is upstream work for this - there's a PR that might land soon that would allow for layout that respects sensor clusters
https://github.com/facebook/react-native/pull/20999

**Comment by mikehardy** [comment]
This looks like it might be the way to go - it is a small lib focused on returning the set of display insets for a device https://github.com/th3rdwave/react-native-safe-area-context

I have not tested it but it may support punch-holes ('displayCutout' in Android API parlance https://developer.android.com/reference/android/view/Display#getCutout()) out of the box just not labeled specifically 

@janicduplessis we have been thinking of a way to support our existing hasNotch() API here and extend to cover punch-holes and the like and I wonder if we're just duplicating your effort. Would you be interested in collaborating with the APIs in your repo or over here? Your implementation is far superior at the moment at minimum (actual device inspection + events vs a simple lookup table - no contest)

**Comment by janicduplessis** [comment]
Hmm we could expose info about display cutouts in rn-safe-area-context. https://developer.android.com/reference/android/view/DisplayCutout.html#getBoundingRects() seems to be what we want. What is punch holes? Is it a different API?

**Comment by mikehardy** [comment]
@janicduplessis a 'punch hole' is what the tech press is calling these cutouts that are fully standalone with display between the edge and the cutout - the samsung galaxy s10 is an example https://image-us.samsung.com/us/smartphones/galaxy-s10/v2/design/images/galaxy-s10_design_amoled.jpg - I think the Android OS must handle them the same as any cutout though? As in they are not safe to display over but the display can sort of be stretched to fill them (for background) if desired? Because there's no fresh API to handle them in the Android APIs (I just looked prior to my comment before)

And yes - right now rn-safe-area-context is all about generating the safe area to draw on but if there was also sort of an inspection ability where you could ask for the list of EdgeInsets (I think that is your object name?) then it would cover everything I think?

**Comment by janicduplessis** [comment]
This api I'm thinking of would actually return a list of Rect objects (top, left, width, height). This would be like DisplayCutout.getBoundingRects. I guess the use case for this is to draw around the cutouts?

**Comment by mikehardy** [comment]
The current react-native-device-info use case is mostly just to answer the question `hasNotch()`? (currently answered via a lookup table) https://github.com/react-native-community/react-native-device-info#hasNotch - it is very simplistic but important to people

A tangential requested use case is to support answering that question in emulators (which hints that the implementation should really not be a lookup table...) #732 

Those two seem like easy-to-understand easy-to-handle APIs from react-native-safe-area-context

The request in this specific issue is to support '.hasCutHole()' but I think the real urge is just that they are named slightly differently so it's not clear that the underlying system doesn't care what you call them, they are all just boundedareas you can't safely draw on to near edges except backgrounds (at your option), right?

So if I understand that right then yes it's just getting the BoundingRects for any/all cutouts, and the use case is to alter layout and/or draw around them yes

**Comment by wmonecke** [comment]
Any updates on this?

**Comment by mikehardy** [comment]
The beauty of open source being that it is obvious when there are no updates ;-)
Propose a PR, ideally to react-native-safe-area-context (or see if there are updates there?) - but nothing happening here
