### ISSUE TITLE
Support instance ID on iOS (this package currently has a java impl for android)

### ISSUE THREAD

**Issue by mehcode** [react-native-device-info/react-native-device-info#60]
From what I understand the purpose is an ID that is specific to the install of an application.

``` js
  async getInstanceID() {
    // // Check for an existing ID
    let id = await AsyncStorage.getItem("instance-id");
    if (id != null) return id;

    // Generate a new UUID
    id = UUID();

    // Save the ID
    await AsyncStorage.setItem("instance-id", id);

    return id;
  }
```

That should do it across all platforms. Don't have time to make it look nice / work so I'm opening the issue.

**Comment by danielfx90** [comment]
I see that now Google provides support for the InstanceID on iOS as well:
https://developers.google.com/instance-id/guides/ios-implementation

The library could use that in the `getInstanceID()` method.

**Comment by mikehardy** [comment]
As part of the deprecation of GCM #602 I'd like to convert to app-specific/app-local GUIDs as described here with the sample implementation above. Seems preferable to bringing in even a reflective / optional Firebase dependency to replace GCM
