### ISSUE TITLE
Install / configure CI

### ISSUE THREAD

**Issue by mikehardy** [react-native-device-info/react-native-device-info#614]
I'd like to have CI configured to provide a bit more comfort with releases.

I know with Travis at least we can do Node and Android things, but not Mac and Windows, I think that might be the standard.

Unless someone objects since I am more familiar with Travis I will setup CI with them and have some node images do type checks and bundles on the main repository as well as the example app, and I'll try to have a full react-native + android app build for the example in a separate image

**Comment by mikehardy** [comment]
Flow check:
https://github.com/react-native-community/react-native-device-info/issues/613

**Comment by machour** [comment]
Could also be a chance to implement [semantic-release](https://github.com/semantic-release/semantic-release) on this repo and automate the release process.

**Comment by mikehardy** [comment]
You and I think alike! I was hoping to do that, and also maybe some bots like dependabot and maybe a stale bit for feedback requests... One step at a time

**Comment by mikehardy** [comment]
I read a lot of documentation, and in the process collect links that are not actionable immediately for lack of time but relate to some other problem - here is one on how to set up CircleCI + semantic-release + GitHub + npmjs.org for auto-releasing when a PR successfully merges https://github.com/infinitered/open-source/blob/master/Continuous-Deployment-Setup-NPM.md

**Comment by mikehardy** [comment]
and these folks are doing it from Travis https://github.com/react-native-sensors/react-native-sensors/blob/master/.travis.yml

**Comment by mikehardy** [comment]
The react-native community appears to *really* like CircleCI, and when I checked it looked like they could do linux mac and maybe even windows, with evidence mac can be free for open source projects (like this). There is community support for CI building blocks in CircleCI documented here https://github.com/react-native-community/react-native-circleci-orb

And Travis currently has a problem where I can't even get the emulators to start anymore on a project that used to be fine - https://travis-ci.community/t/android-emulators-not-starting-for-the-last-few-days-late-march-2019/2871

So maybe it's time for me to learn CircleCI unless there is already a master that wants to take this up?

**Comment by mikehardy** [comment]
These are the instructions for setting up community-managed eslint+prettier https://github.com/react-native-community/meta/pull/22/files

**Comment by mikehardy** [comment]
I have been sort of waiting for this, the community proviced "CirlceCI Orb" for react-native - it apparently nukes most of the boilerplate work https://github.com/react-native-community/react-native-circleci-orb?reddit=1

I believe you still need to ask on Discord in the react-native-community channels to have CI set up if you are a community project, but once they enable it, you use this (and I think react-native-device-info is probably a good example) and everything should work?

**Comment by mikehardy** [comment]
Here's another implementation of CircleCI from react-native-community - this time with semantic-release setup, looks pretty easy but I need to examine .releaserc to see what exactly they all do: https://github.com/react-native-community/react-native-modal/pull/300

Then in the react-native-community discord they ask for the CircleCI and NPM API tokens to be added to the github repo to finish the hookup

**Comment by mikehardy** [comment]
Travis is no longer recommended - they push hard for money now, understandably.
Not a fan of Circle.
New style would be on Github Actions which is already largely done here for jest and windows
Need a github workflow that runs on macOS and does the iOS and android compiles at least

**Comment by schie** [comment]
@mikehardy, I can work on this.

The easiest way, in my experience, is to use [fastlane](https://fastlane.tools) for building. If you're not familiar w/ it, it's a pretty handy tool for building, deploying, and managing certs for applications.

I'll update the example project w/ fastlane configs, then work on the workflows.

Both MacOS and Linux GH Action environments have it already built-in, so it should be fairly straight forward.

**Comment by mikehardy** [comment]
Yes, I use fastlane for my work projects. +1

**Comment by schie** [comment]
To Do:
- [ ] Add a machine user account to the org. (Bender, Jarvis, Alfred, etc...)
- [ ] Use a personal access token from machine user as `GH_TOKEN` secret

**Comment by mikehardy** [comment]
Hey @schie - you asked separately if I had experience using github bots etc - I do not unfortunately. I'd inquire with react-native-webview and specifically @Titozzz as I believe he is the semantic-release wizard behind react-native-webview + has helped others in the react-native maintainer community get this stuff set up to free up our lives :-)

**Comment by Titozzz** [comment]
Hello @mikehardy 👋what do you need me for

**Comment by schie** [comment]
Hi @Titozzz !

how'd you setup semantic-release for react-native-webview?

Currently, we have it setup in a GitHub Action, but the default `GITHUB_TOKEN` secret doesn't allow for pushing into protected branches, so we have to use a PAT. This is a security concern for any private orgs or repos the owner of the PAT is a part of.

**Comment by schie** [comment]
@mikehardy , 

Are we fine w/ just making a machine user w/ the needed permissions? If so, I'll make one.

This is what we have for my work and also what folks at [semantic-release are doing](https://github.com/semantic-release/semantic-release/discussions/1859).

**Comment by mikehardy** [comment]
@schie - yes, that sounds reasonable objectively and if that's also the most visible examples, definitely

**Comment by schie** [comment]
@mikehardy, machine user, @rndi-bot, has been made and added.

**Comment by mikehardy** [comment]
Of course, your contribution graph will be less awesome this easy 😏, but it's the right way, thanks!

**Comment by schie** [comment]
To make sure our Dev Dependencies are up-to-date, we should probably start using dependabot or something similar. 

Do we care that devdeps are on the latest and greatest?

Thoughts?

**Comment by mikehardy** [comment]
Oh yea - I use dependabot everywhere else. I typically like all updates to be latest and greatest unless there is some reason not too (e.g., metro-react-native-babel-preset I think has to track react-native version as does the react version, and if the example is still on react-native 0.64 then bumping m-r-n-b-preset to 0.65.0 or whatever does not work I think?) but in the general case I bump everything.

**Comment by schie** [comment]
from https://github.com/react-native-device-info/react-native-device-info/pull/1213
>@schie this was actually a case I was curious about - I remember you asked "do we want dependabot for dev dependencies as well?" and I thought "I want to see it to see how it goes", it was pretty noisy at first but I thought if it settled down (which it still might do) then sure.
>
>But it appears that we can have cascading PRs (this one started in the dependency where they have a dependency-gardening bot running) and I'm not sure if there is really value here.
>
>At this point I think I would turn off PRs on dev dependencies, but I'm unsure if that binary stance is a negative in the other direction too - perhaps there is a middle ground where some were tracked (how to pick them? which ones?) but not all
>
>But right now this seems like it was interesting to see - I'm glad I saw it - but maybe not 100% useful


Per the [documentation](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#allow), it looks like we may be able to white-list certain dependency types, or black-list by name.

Since there are no direct dependencies and `*react*` deps are a manual thing, we don't get much out of it.

**Comment by schie** [comment]
@mikehardy,
I've been getting a number of CircleCI emails regarding failed runs, is this project still using that?

**Comment by mikehardy** [comment]
Haha no, not a bit. All github actions AFAIK

**Comment by schie** [comment]
I'll take a look to see what's going on

**Comment by schie** [comment]
While @rndi-bot does have write permissions, it have the permission to write directly into master (bypass the protected branch rules). I've updated them to allow RNDI to do so

**Comment by schie** [comment]
I changed @rndi-bot 's permissions to `owner` the other day to set a baseline for `pushing-to-master`. I've downgraded the bot back down to `member`, but with `maintainer` access on the repo. 

Let's see if this is good enough. 🤞

**Comment by mikehardy** [comment]
I'm about to set up two more repos for various reasons (maybe 3) so this is all a valuable learning experience - thanks, and yes :crossed_fingers:

**Comment by schie** [comment]
we should ignore the `/example` path in the release action. I'll update this soon.

**Comment by mikehardy** [comment]
I'm hoping to figure out why the example extension isn't compiling - and worse! - why it's false positive :sweat_smile: #1191 - that offends me as an otherwise-purist for CI haha
