### ISSUE TITLE
Update getFontScale to work in iOS App Extensions

### ISSUE THREAD

**Issue by lnikkila** [react-native-device-info/react-native-device-info#625]
## Summary

|             |     |
| ----------- | --- |
| Version     | master   |
| Affected OS | iOS   |
| OS Version  | any   |

## Current behavior

Following up #408, we’ve patched the library to compile with iOS App Extensions, however getFontScale always returns 1.0 since the shared application cannot be accessed. A potential (iOS 10+) workaround is described in https://github.com/react-native-community/react-native-device-info/pull/408#issuecomment-462807763.

## Expected behavior

getFontScale should probably return the font scale on iOS 10+ and fall back to 1.0 or use a different workaround with older versions.

**Comment by mikehardy** [comment]
Following up on this: the proposal in the linked comment was:

```
RCTSharedApplication() returns nil when ran in an app extension.
I suggest using the following:

NSString *contentSize = [[UIScreen mainScreen] traitCollection].preferredContentSizeCategory;

However it would imply dropping iOS 9 support. Or maybe we could just default the contentSize to 1 on that version?
```

I will not drop iOS 9 support until the main react-native platform does, and I have not heard of any dates where this will happen.

However, if this is a need for someone and they are motivated I will happily accept a PR (if it is possible) that ifdef's around the ios9 vs ios10 compatibility and includes the current implementation for ios9 only, and moves to the above proposal for ios10+

I personally do not need this so I will not implement it myself but I'll help land it if someone else is

Cheersy

**Comment by schie** [comment]
@mikehardy,
Since the release of RN 0.63, [support for iOS 13 has been dropped](https://reactnative.dev/blog/2020/07/06/version-0.63#dropping-ios-9-and-nodejs-8-support).

Currently, this project points to RN 0.62.2, so would this project have to upgrade to 0.63 to definitively say, "hey, we're in that iOS 10+ gang" ?  I'm not sure if that matters though. I think the link above, at the time of its writing, also states that iOS 9's market share is ~ 1%.

With that being said, I can work on this if need be.

**Comment by mikehardy** [comment]
I am okay with dropping ios9 now as a breaking change and just saying if you need to use ios9 stick with an older version of the library, with a possibly less drastic step being to say this API specifically only works on ios10+ and returns the default (or a fallback) on ios9

**Comment by schie** [comment]
@mikehardy, 

Would this technically be a breaking change since the lib won't be supporting iOS 9?

...Just trying to figure-out my commit messages.

**Comment by mikehardy** [comment]
if we drop ios9 it's breaking yes, I'm willing to do it - react-native dropped 9 in 0.63 https://github.com/facebook/react-native/commit/674b591809cd1275b5f1c4d203c2f0ec52303396 which has been out quite a while and I already have a couple other major packages which are 10+

**Comment by schie** [comment]
sounds good; PR should be good-to-go
