### ISSUE TITLE
Android: Support for simulated cutout option in developer tools

### ISSUE THREAD

**Issue by petekp** [react-native-device-info/react-native-device-info#732]
# Feature Request

Android dev tools provide a setting that allows you to simulate a device cutout / notch on any device. Wondering if it might be possible for `DeviceInfo.hasNotch()` to recognize whether this setting is enabled and to return `true` if it is enabled.

<img src="https://user-images.githubusercontent.com/950779/61735610-2c54b200-ad39-11e9-9944-406b1ddda771.png" width="300" />

## Why it is needed

It would allow a developer to use a single simulator for testing UI changes both with and without a notch. Otherwise, two simulators are necessary.

**Comment by mikehardy** [comment]
Oh that's cool - I didn't even know that existed. I'd love for that to be possible and would merge a PR for that immediately but I'm traveling right now so don't have time to look at it myself

**Comment by mikehardy** [comment]
I think you might like https://github.com/th3rdwave/react-native-safe-area-context - there's a handy tutorial linked at the bottom of the README that shows it working on an emulator even
