### ISSUE TITLE
com.google.android.c2dm.permission.RECEIVE

### ISSUE THREAD

**Issue by Rebsos** [react-native-device-info/react-native-device-info#893]
Somewhere between version 0.9.3 and 0.11.0 this package adds this permission: com.google.android.c2dm.permission.RECEIVE
I can't determine which exactly, because the build fails there and I can't find the code which adds this and why.
1. Can it be removed from this package?
2. Is it safe to exclude this permission from my build or what downsides are there?

**Comment by mikehardy** [comment]
We're on version 5.x, bugs on older versions aren't valid, please do whatever you need to for your work project unless you can reproduce on current versions

**Comment by Rebsos** [comment]
@mikehardy 

Sorry, I explained it wrong. Since 0.9.3 or 0.11.0 AND above (including 2.x, 3.x, 4.x, 5.x), this package adds "com.google.android.c2dm.permission.RECEIVE". I reproduced it on a new project with react-native version 0.61.4. This permission will be added at least with version 0.11.0 and above. If you choose 0.9.3 and below, this permission won't be added. 

Short: 5.3.0 (current) adds "com.google.android.c2dm.permission.RECEIVE"

**Comment by mikehardy** [comment]
Ah, okay.

**Comment by mikehardy** [comment]
So, when you use the Manifest Merger tool in Android Studio, what does it tell you? Where did it come from? If you use tools:remove on the permission to take it out, does it work?

like this

```xml

    <uses-permission tools:node="remove" android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission tools:node="remove" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission tools:node="remove" android:name="android.permission.WRITE_CALENDAR" />

```

**Comment by Rebsos** [comment]
I can't see this permission in the Merger. I also can't find anything in the code of react-native-device-info. It's just in the apk file if you add react-native-device-info.

<img width="578" alt="Screenshot 2019-11-17 at 05 20 38" src="https://user-images.githubusercontent.com/17834477/69003028-2f346d80-08fb-11ea-8ed2-cd67d4c3017b.png">


The permission is visible if you run
> adb shell dumpsys package com.rn_0_61_4

or upload the .apk file to the Playstore.

It'll be added in debug and production mode.

Reproducable e.g. with a new RN 61 project and install the latest of this package (5.3.0)

**Comment by mikehardy** [comment]
Interesting. I see it too.

```
(base) mike@kunashir:~/work/react-random/react-native-device-info/example (master) % apkanalyzer manifest print android/app/build/outputs/apk/debug/app-debug.apk |grep RECEIVE
        android:name="com.google.android.c2dm.permission.RECEIVE" />
```

So, how did it go when you removed it via tools:remove?

I imagine it's from the unique id stuff (our google library dependency), which is definitely required for many. Strange it doesn't show up when you merge manifests, whereas apkanalyzer does see it.

**Comment by Rebsos** [comment]
tools:remove works and removes the permission in debug and production mode, 
but 1. I didn't released it yet and don't know if there will be some problems on other devices and 2. I just use getVersion() and getBuildNumber()

**Comment by mikehardy** [comment]
should be fine then. I use tools:remove to shrink the permissions in my project all the time. DeviceInfo itself doesn't receive cloud messages either so it should be fine. I can't use the ID functions at all from firebase/google cloud messaging without having a dependency on the library so it is unfortunately "working as intended", and with a workaround I'm not sure what more there is to do?
