### ISSUE TITLE
Improve used memory reporting

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-device-info/react-native-device-info#895]
# Feature Request

Both iOS and Android used memory seem quite far away from their real values. On Android, it looks like it is only counting the JS used memory. On iOS, it is not that bad; however, it doesn't seem to be counting memory from Core Foundation (explanation below).

We've just discovered a memory leak due to some CF objects not being released. Oddly enough, this library was reporting "normal" memory usage, and it would even decrease the higher the memory leak was! This lead us to think memory was not an issue initially.

## Why it is needed

More accurate values could be used for improved debugging.

## Possible implementation
Here's a Swift answer that claims to be "better" than the accepted one: https://stackoverflow.com/questions/787160/programmatically-retrieve-memory-usage-on-iphone

### Code sample
-

**Comment by mikehardy** [comment]
Happy to accept PRs, but I don't have extra maintainer time to implement this myself. I believe there are some other issues (or PRs) in this area, if anyone wants to implement it and see what the community has discussed prior

**Comment by cristianoccazinsp** [comment]
I definitely will if this becomes a requirement or I have some free time!
Just tossing up the idea here in case someone faced the same.
