### ISSUE TITLE
web chargingtime/dischargingtime are deprecated and maybe incorrect

### ISSUE THREAD

**Issue by MoOx** [react-native-device-info/react-native-device-info#901]
# Feature Request

chargingtime/dischargingtime should be removed

See deprecation notice here https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API

Also it should be `chargingTime` and `dischargingTime` so not sure this is even working...

## Why it is needed

typo issue + non standard web stuff (discouraged for many reasons if I am correct, to avoid abuse etc)

## Possible implementation

Just revert https://github.com/react-native-community/react-native-device-info/commit/692c50e1ad7d5f53c5aa12f866b4c667ed09fbcc

**Comment by mikehardy** [comment]
Thanks @MoOx - I'm still coming up to speed on the web side of things but I am using it in a project now so it will transform from 2nd class citizen to 1st class support. In the meantime I'm definitely relying on the community to make web work. 

@robertherber what do you think of reverting that patch?

Seems like the reasonable thing based on the Mozilla docs but I'm not sure what state of the art on the web is. If we want to support it while it exists (deprecated or not) I could see keeping it but only if the code was tolerant of the API not being available at any time and there was a way to suppress deprecation warnings with an indication we know it's deprecated but still provide all device info available while available (which is how native works at the moment)

**Comment by robertherber** [comment]
My mistake - reverting it sounds like the reasonable thing to do. Especially since those are not values exposed in the iOS/Android implementations.

Still I think fairly well-supported web APIs make sense to include, and of course provide fallback (as is the case here) when not supported. It's a bit sad web APIs that provide value for the web as a platform are deprecated because of tracking - I think a good permission UX would be better than simply deprecating stuff which I think is the case here..

**Comment by mikehardy** [comment]
I am with you philosophically, and no mistake I think, can't fault a person for trying and actually implementing things :-). I'll see what I can do on this in a few days @MoOx but of course if you want to patch-package it locally until then (if it is pressing) you can trust it will converge as we seem to have consensus here.

**Comment by MoOx** [comment]
No rush, I don't need this. I am just writing bindings without this 2 things for now :)
