### ISSUE TITLE
When would device id get changed on iOS?

### ISSUE THREAD

**Issue by hopewise** [react-native-device-info/react-native-device-info#904]
# Question

What are the known cases were device id got from `getUniqueId ` would be changed? ex: when app got removed and installed again? what other cases would there be?

I found some questions on SO but I could not find if the id would get changed while the app is already installed?

**Comment by mikehardy** [comment]
Very API dependent I think? As in the old android versions behave differently than the new ones. And it may change again in the future. You'll have to refer to primary documentation (android SDK docs) and/or stackoverflow on this one though, I am not an expert as I haven't needed stability of these ids in my work project so haven't paid too much attention personally.

I'll leave this open for a while though in case an actual expert turns up.

**Comment by mikehardy** [comment]
Also - I would *test* *test* and *re-test* if it's a key part of the app that the id behavior is well-understood. I marked it android but I suppose it could be iOS as well? You might be specific on that, as well with what specific version range you care about

**Comment by hopewise** [comment]
I found this for iOS https://developer.apple.com/documentation/devicecheck#overview but I am not sure if this would get persistent id??

**Comment by grit96** [comment]
@mikehardy is the new `getDeviceToken()` likely to be more persistent than `getUniqueId()` on iOS?

**Comment by mikehardy** [comment]
I would not even hazard a guess, uniquely identifying specific devices is a dark art and generally discouraged so :man_shrugging: - but I'll expose the APIs if possible :-)

**Comment by AntoineDoubovetzky** [comment]
@grit96 The new `getDeviceToken()` uses the DeviceCheck API (https://developer.apple.com/documentation/devicecheck#overview).

The documentation says:
> Your app uses the DeviceCheck APIs to generate an ephemeral token that identifies a device.

So no, it won't be persistent :)

**Comment by hopewise** [comment]
As its not persistent, and I don't know when it would be invalid, what use cases would it be useful in?!

**Comment by mikehardy** [comment]
It may not be any more. Remember these APIs change every OS release for privacy reasons. I imagine it was useful before and simply still exists.

**Comment by BenjaminSAILcloud** [comment]
So is there a way to get an unchanging devide id ?

**Comment by mikehardy** [comment]
@BenjaminSAILcloud I would expect device IDs to only be stable for a while. They should be stable during a single installation of the app, but are subject to change if the app is removed and reinstalled. This is a good thing for your privacy and is the point of the API changes the vendors have put in
