### ISSUE TITLE
Improved documentation on listeners

### ISSUE THREAD

**Issue by SirKadogan** [react-native-device-info/react-native-device-info#962]
Hi! I'd like to suggest that the documentation on listeners be updated. My suggestion is specifically for the power state, but I feel the other listeners are a bit neglected as well. 

Currently it is like this:
```
import { NativeEventEmitter, NativeModules } from 'react-native'
const deviceInfoEmitter = new NativeEventEmitter(NativeModules.RNDeviceInfo)

deviceInfoEmitter.addListener('RNDeviceInfo_powerStateDidChange', { batteryState } => {
  // 'charging'
});
```
My suggestion is to return the whole object and let the user handle the cases. While that opens more possibilities where the listener might return the battery level, it also makes it clearer on what information we have available. Testing battery connection is a pain, since disconnecting the cable on a device disconnects from the debugger and all sorts of problems. I actually had to go dig through the library code to figure out the returned data.

```
import { NativeEventEmitter, NativeModules } from 'react-native'
const deviceInfoEmitter = new NativeEventEmitter(NativeModules.RNDeviceInfo)

this.batteryListener = deviceInfoEmitter.addListener('RNDeviceInfo_powerStateDidChange', status => {
//status = {lowPowerMode: false, batteryLevel: 0.9996343, batteryState: 'charging'} 
//batteryState = 'charging'  || 'unplugged' || 'full'
});

//Remove Listener
this.batteryListener.remove();
```

I'd be happy to send a PR request. I just havent ever done that, so I'll need a bit of orientation here.

**Comment by mikehardy** [comment]
Hi there! I'm open to non-breaking changes like this, that is if you want to add a listener / event combo that is similar to the current ones but returns something with a more generic / all-info-at-once shape, that's fine. I'm traveling so I don't have a lot of time for PR help but it's not too hard I think (hopefully not famous last words). Fork the repo, clone it to a dev machine, then as a development cycle how we work here is to run yarn in the example so it's ready to go, and actually run it in android and ios to make sure it is working. Then make your changes in the parent / actual code area and run 'yarn dev-sync' in there to copy your changes into the example, rebuild it and test it. That also enforces that you've updated the example with the new code sample. Polish up the work and update the documentation and propose the PR and you're set

**Comment by SirKadogan** [comment]
I haven't had time to look into it, but it's a change to documentation only. The code already returns everything I mentioned :) 
I'll come back to it as soon as I can. I'm a bit excited about my first PR hehe

**Comment by MarcoDeJong** [comment]
This issue was more helpful than the original documentation. Thank you, Sir!
