### ISSUE TITLE
isEmulator and isEmulatorSync improvement

### ISSUE THREAD

**Issue by dorw123** [react-native-device-info/react-native-device-info#994]
# Feature Request - isEmulator and isEmulatorSync improvement

## Why it is needed

Additional check to verify if the device is a Genymotion or BlueStacks emulator. 
"Considering that reading Android properties might be hooked or
circumvented by an expert attacker, we complement it with an additional lightweight implementation. "

## Possible implementation

"Manually analyzing the Genymotion emulator and the Bluestacks, we listed some file-system
paths and files that are unique to these emulators and, thus, can be
used to identify these emulators. "

/dev/vboxguest
/dev/vboxuser
/fstab.vbox86
/init.vbox86.rc
/data/bluestacks.prop
/data/data/com.bluestacks.appsettings
com.bluestacks.settings.apk

Reference: https://selab.fbk.eu/ceccato/papers/2019/ssprew2019.pdf

**Comment by mikehardy** [comment]
There's already a PR for this #721 - it's just sitting there with unaddressed comments, bring it to completion and I'll merge

**Comment by wellmonge** [comment]
@dorw123 Hello, I've been while off, I'm trying address this additional checks to Genymotion or BlueStacks.
